package main

import (
	"strings"
	"testing"

	methodassets "github.com/mixofreality-studio/archistrator-platform/method-assets"
)

// fixture is one valid lifecycle that exercises every formatting branch: a
// property over prettier's width (broken after the colon), a string holding an
// apostrophe (double-quoted), an empty and a non-empty dependsOn, and the
// optional properties present on one task and absent on the other.
func fixture() methodassets.Lifecycle {
	return methodassets.Lifecycle{
		Type: "fixture",
		Phases: []methodassets.LifecyclePhase{{
			ID: "a", Label: "A", Weight: 100, Gate: "aReview",
			ExitCriterion: "The plan's scenarios are written, every one of them traced to a use case, and the trace passes review",
		}},
		Tasks: []methodassets.LifecycleTask{
			{ID: "aDraft", Kind: methodassets.LifecycleTaskDispatch, Title: "Draft A", Phase: "a", DependsOn: []string{}, Command: "mission-draft", WorkerClass: "system-architect", ArtifactKind: "A"},
			{ID: "aReview", Kind: methodassets.LifecycleTaskReview, Title: "Review A", Phase: "a", DependsOn: []string{"aDraft"}, Reviews: "aDraft"},
		},
	}
}

const wantFixtureData = `export const LIFECYCLES: readonly LifecycleDef[] = [
  {
    type: 'fixture',
    phases: [
      {
        id: 'a',
        label: 'A',
        weight: 100,
        gate: 'aReview',
        exitCriterion:
          "The plan's scenarios are written, every one of them traced to a use case, and the trace passes review",
      },
    ],
    tasks: [
      {
        id: 'aDraft',
        kind: 'dispatch',
        title: 'Draft A',
        phase: 'a',
        dependsOn: [],
        revisionGroup: 'aDraft',
        command: 'mission-draft',
        workerClass: 'system-architect',
        artifactKind: 'A',
      },
      {
        id: 'aReview',
        kind: 'review',
        title: 'Review A',
        phase: 'a',
        dependsOn: ['aDraft'],
        revisionGroup: 'aDraft',
        reviews: 'aDraft',
      },
    ],
  },
];
`

func TestRender_FixtureDataIsPrettierShaped(t *testing.T) {
	got, err := render([]methodassets.Lifecycle{fixture()})
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(got, "// Code generated by server/cmd/gen-lifecycles. DO NOT EDIT.\n") {
		t.Errorf("missing the generated-code header, got %q…", got[:60])
	}
	if !strings.Contains(got, "\nexport type LifecycleTypeKey = 'fixture';\n") {
		t.Error("a union that fits on one line must stay on one line, as prettier keeps it")
	}
	from := strings.Index(got, "export const LIFECYCLES")
	to := strings.Index(got, "\n/** The lifecycle for an activity-type key")
	if from < 0 || to < from {
		t.Fatalf("LIFECYCLES const or lifecycleFor missing:\n%s", got)
	}
	if data := got[from:to]; data != wantFixtureData {
		t.Errorf("LIFECYCLES data =\n%s\nwant\n%s", data, wantFixtureData)
	}
	if !strings.HasSuffix(got, "  return LIFECYCLES.find((l) => l.type === typeKey);\n}\n") {
		t.Error("lifecycleFor must close the file, newline-terminated")
	}
}

func TestRender_RefusesInvalidData(t *testing.T) {
	bad := fixture()
	bad.Phases[0].Weight = 90
	if _, err := render([]methodassets.Lifecycle{bad}); err == nil || !strings.Contains(err.Error(), "sum to 90") {
		t.Errorf("render must refuse data ValidateLifecycle rejects, got err = %v", err)
	}
	if _, err := render(nil); err == nil {
		t.Error("render must refuse an empty lifecycle set rather than emit an empty table")
	}
}

func TestRender_PinnedDataIsCompleteAndDeterministic(t *testing.T) {
	first, err := render(methodassets.Lifecycles())
	if err != nil {
		t.Fatal(err)
	}
	second, _ := render(methodassets.Lifecycles())
	if first != second {
		t.Error("two renders of the same data differ")
	}
	if !strings.Contains(first, "export type LifecycleTypeKey =\n  | 'requirements'\n  | 'architecture'\n") {
		t.Error("the fourteen-member key union is wider than 100 characters and must break one member per line")
	}
	for _, l := range methodassets.Lifecycles() {
		if !strings.Contains(first, "    type: "+tsString(l.Type)+",\n") {
			t.Errorf("lifecycle %q was not emitted", l.Type)
		}
	}
	for _, never := range []string{"someConstruction", "testClient"} {
		if strings.Contains(first, never) {
			t.Errorf("%s is a conditional sub-attempt, never a lifecycle node", never)
		}
	}
}

func TestTsString_QuotesTheWayPrettierDoes(t *testing.T) {
	cases := map[string]string{
		"SRS Review":       `'SRS Review'`,
		"the plan's trace": `"the plan's trace"`,
		`say "go"`:         `'say "go"'`,
		`'tis 'x' "y"`:     `"'tis 'x' \"y\""`,
		`a\b`:              `'a\\b'`,
	}
	for in, want := range cases {
		if got := tsString(in); got != want {
			t.Errorf("tsString(%q) = %s, want %s", in, got, want)
		}
	}
}

// Prettier measures a line in characters. The copy carries "—" and "·" (multi-byte
// in UTF-8), so a byte count would break lines prettier keeps whole.
func TestWriteProp_MeasuresCharactersNotBytes(t *testing.T) {
	// 4 indent + "k" + ": " + quoted literal (2 + 80 + 10) + "," = exactly 100 characters.
	literal := tsString(strings.Repeat("a", 80) + strings.Repeat("—", 10))
	var b strings.Builder
	writeProp(&b, "    ", "k", literal)
	if want := "    k: " + literal + ",\n"; b.String() != want {
		t.Errorf("a 100-character line was broken:\n%q\nwant\n%q", b.String(), want)
	}
	longer := tsString(strings.Repeat("a", 81) + strings.Repeat("—", 10))
	b.Reset()
	writeProp(&b, "    ", "k", longer)
	if want := "    k:\n      " + longer + ",\n"; b.String() != want {
		t.Errorf("a 101-character line was not broken:\n%q\nwant\n%q", b.String(), want)
	}
}
