// Code generated by cmd/modelgen from the service-contract interface; DO NOT EDIT.
// Edit project.json's `interface` and re-run `make gen-fakes` instead.

package billingfake

import (
	fweng "github.com/mixofreality-studio/archistrator-platform/framework-go/engine"
	"github.com/mixofreality-studio/archistrator/server/internal/engine/billing"
)

// FakeBillingEngine is a generated test double for billing.BillingEngine: set the Fn field(s)
// a test needs; calling a method whose Fn is unset panics.
type FakeBillingEngine struct {
	ComputeNetFn                                  func(rc fweng.Context, revenue billing.CycleRevenue, usage billing.CycleUsage, terms billing.BillingTerms) (billing.BillingResult, error)
	ProjectCommitTimeRevenueShareAndComputeCostFn func(rc fweng.Context, option billing.ProjectOption) (billing.Projection, error)
	RecomputeNetFn                                func(rc fweng.Context, affectedCycle billing.ReBillingInput) (billing.BillingResult, error)
}

func (f *FakeBillingEngine) ComputeNet(rc fweng.Context, revenue billing.CycleRevenue, usage billing.CycleUsage, terms billing.BillingTerms) (billing.BillingResult, error) {
	if f.ComputeNetFn == nil {
		panic("FakeBillingEngine.ComputeNetFn not set")
	}
	return f.ComputeNetFn(rc, revenue, usage, terms)
}

func (f *FakeBillingEngine) ProjectCommitTimeRevenueShareAndComputeCost(rc fweng.Context, option billing.ProjectOption) (billing.Projection, error) {
	if f.ProjectCommitTimeRevenueShareAndComputeCostFn == nil {
		panic("FakeBillingEngine.ProjectCommitTimeRevenueShareAndComputeCostFn not set")
	}
	return f.ProjectCommitTimeRevenueShareAndComputeCostFn(rc, option)
}

func (f *FakeBillingEngine) RecomputeNet(rc fweng.Context, affectedCycle billing.ReBillingInput) (billing.BillingResult, error) {
	if f.RecomputeNetFn == nil {
		panic("FakeBillingEngine.RecomputeNetFn not set")
	}
	return f.RecomputeNetFn(rc, affectedCycle)
}

var _ billing.BillingEngine = (*FakeBillingEngine)(nil)
