// Code generated by cmd/modelgen from contract.schema.json; DO NOT EDIT.
// Edit the schema and re-run `make gen-models` instead.

package estimation

import (
	fweng "github.com/mixofreality-studio/archistrator-platform/framework-go/engine"
)

type ActivityItem struct {
	Name       string  `json:"name"`
	EffortDays float64 `json:"effortDays"`
}

type ActivityList struct {
	Activities []ActivityItem `json:"activities"`
}

type ActivityListDeltas struct {
	Overrides          []ActivityOverride  `json:"overrides,omitempty"`
	Additive           []AdditiveActivity  `json:"additive,omitempty"`
	AdditiveMilestones []AdditiveMilestone `json:"additiveMilestones,omitempty"`
}

type ActivityNetwork struct {
	Activities   []OptionActivity    `json:"activities"`
	Dependencies []NetworkDependency `json:"dependencies,omitempty"`
	Milestones   []NetworkMilestone  `json:"milestones,omitempty"`
}

type ActivityOverride struct {
	Activity      string   `json:"activity"`
	EffortDays    *float64 `json:"effortDays,omitempty"`
	RiskBucket    *int64   `json:"riskBucket,omitempty"`
	Justification string   `json:"justification"`
}

type AdditiveActivity struct {
	Name          string   `json:"name"`
	Title         string   `json:"title"`
	EffortDays    float64  `json:"effortDays"`
	RiskBucket    int64    `json:"riskBucket"`
	WorkerClass   string   `json:"workerClass"`
	Coding        bool     `json:"coding"`
	DependsOn     []string `json:"dependsOn,omitempty"`
	ComponentID   *string  `json:"componentId,omitempty"`
	Justification string   `json:"justification"`
}

type AdditiveMilestone struct {
	Id            string   `json:"id"`
	DependsOn     []string `json:"dependsOn,omitempty"`
	Justification string   `json:"justification"`
}

type ConstructionEstimate struct {
	DurationDays float64   `json:"DurationDays"`
	BuildCost    Money     `json:"BuildCost"`
	Risk         RiskScore `json:"Risk"`
	DirectCost   Money     `json:"DirectCost"`
	IndirectCost Money     `json:"IndirectCost"`
}

type DerivedActivity struct {
	Name        string  `json:"name"`
	Title       string  `json:"title"`
	EffortDays  float64 `json:"effortDays"`
	RiskBucket  int64   `json:"riskBucket"`
	WorkerClass string  `json:"workerClass"`
	Coding      bool    `json:"coding"`
	ComponentID string  `json:"componentId"`
	Derived     bool    `json:"derived"`
}

type DerivedPlan struct {
	Activities   []DerivedActivity   `json:"activities"`
	Dependencies []NetworkDependency `json:"dependencies"`
	Milestones   []NetworkMilestone  `json:"milestones,omitempty"`
}

type EVCurve struct {
	Weeks   []int64   `json:"weeks"`
	Earned  []float64 `json:"earned"`
	Planned []float64 `json:"planned"`
	SPI     float64   `json:"spi"`
}

type Money struct {
	MinorUnits int64  `json:"minorUnits"`
	Currency   string `json:"currency"`
}

type Network struct {
	Dependencies []NetworkDependency `json:"dependencies"`
	Milestones   []NetworkMilestone  `json:"milestones,omitempty"`
}

type NetworkDependency struct {
	Activity  string   `json:"activity"`
	DependsOn []string `json:"dependsOn"`
}

type NetworkMilestone struct {
	Id        string   `json:"id"`
	DependsOn []string `json:"dependsOn,omitempty"`
}

type NetworkMilestoneSolution struct {
	ID             string  `json:"ID"`
	OnCriticalPath bool    `json:"OnCriticalPath"`
	EventTime      float64 `json:"EventTime"`
}

type NetworkNode struct {
	EarliestStart  float64 `json:"EarliestStart"`
	EarliestFinish float64 `json:"EarliestFinish"`
	LatestStart    float64 `json:"LatestStart"`
	LatestFinish   float64 `json:"LatestFinish"`
	TotalFloat     float64 `json:"TotalFloat"`
	FreeFloat      float64 `json:"FreeFloat"`
	OnCriticalPath bool    `json:"OnCriticalPath"`
	NearCritical   bool    `json:"NearCritical"`
	Band           string  `json:"Band"`
	Column         int64   `json:"Column"`
}

type NetworkSolution struct {
	Nodes      map[string]NetworkNode     `json:"Nodes"`
	Milestones []NetworkMilestoneSolution `json:"Milestones"`
	Summary    NetworkSummary             `json:"Summary"`
}

type NetworkSummary struct {
	TotalDurationDays         float64 `json:"TotalDurationDays"`
	CriticalPathActivityCount int64   `json:"CriticalPathActivityCount"`
	CriticalPathDays          float64 `json:"CriticalPathDays"`
	MaxFloat                  float64 `json:"MaxFloat"`
	NearCriticalCount         int64   `json:"NearCriticalCount"`
}

type OptionActivity struct {
	ActivityId     string  `json:"activityId"`
	EffortDays     float64 `json:"effortDays"`
	WorkerClass    string  `json:"workerClass"`
	OnCriticalPath bool    `json:"onCriticalPath"`
	RiskBucket     int64   `json:"riskBucket"`
}

type OptionID string

type ProjectOption struct {
	OptionId            OptionID        `json:"optionId"`
	Network             ActivityNetwork `json:"network"`
	WorkerMix           WorkerMix       `json:"workerMix"`
	CalendarDaysPerWeek float64         `json:"calendarDaysPerWeek"`
	IndirectDailyRate   Money           `json:"indirectDailyRate"`
	BufferDays          float64         `json:"bufferDays"`
	CriticalSpeedup     float64         `json:"criticalSpeedup"`
}

type RiskScore struct {
	Composite       float64 `json:"Composite"`
	CriticalityRisk float64 `json:"CriticalityRisk"`
	ActivityRisk    float64 `json:"ActivityRisk"`
}

type SystemComponent struct {
	ID                  string `json:"id"`
	Name                string `json:"name"`
	Kind                string `json:"kind"`
	ConstructionProfile string `json:"constructionProfile"`
	Provisioning        string `json:"provisioning"`
	UiSurface           bool   `json:"uiSurface"`
}

type SystemRelationship struct {
	From string `json:"from"`
	To   string `json:"to"`
}

type SystemView struct {
	Components     []SystemComponent    `json:"components"`
	Relationships  []SystemRelationship `json:"relationships,omitempty"`
	CoreUseCaseIDs []string             `json:"coreUseCaseIds,omitempty"`
}

type WorkerMix struct {
	ClassRates  map[string]Money `json:"classRates"`
	StaffingCap int64            `json:"staffingCap"`
}

// EstimationEngine is the generated service-contract interface for this component.
type EstimationEngine interface {
	ComputeEarnedValue(rc fweng.Context, activities ActivityList, network Network, integrated []string, totalWeeks int64, calendarDaysPerWeek int64) (EVCurve, error)
	ComputeNetwork(rc fweng.Context, activities ActivityList, network Network) (NetworkSolution, error)
	EstimateForOption(rc fweng.Context, option ProjectOption) (ConstructionEstimate, error)
	DerivePlan(rc fweng.Context, system SystemView, deltas ActivityListDeltas) (DerivedPlan, error)
}

// EstimationEngineImpl is the generated concrete EstimationEngine. Engines are pure (no
// dependencies), so the impl carries no fields and the constructor takes none.
// The interface methods are hand-written on this struct.
type EstimationEngineImpl struct{}

// NewEstimationEngine returns the production EstimationEngine.
func NewEstimationEngine() EstimationEngine { return EstimationEngineImpl{} }

var _ EstimationEngine = EstimationEngineImpl{}
