// Code generated by cmd/modelgen from contract.schema.json; DO NOT EDIT.
// Edit the schema and re-run `make gen-models` instead.

package estimation

type ActivityItem struct {
	Name       string  `json:"name"`
	EffortDays float64 `json:"effortDays"`
}

type ActivityList struct {
	Activities []ActivityItem `json:"activities"`
}

type ActivityNetwork struct {
	Activities []OptionActivity `json:"activities"`
}

type ConstructionEstimate struct {
	DurationDays float64   `json:"DurationDays"`
	BuildCost    Money     `json:"BuildCost"`
	Risk         RiskScore `json:"Risk"`
}

type Money struct {
	MinorUnits int64  `json:"minorUnits"`
	Currency   string `json:"currency"`
}

type Network struct {
	Dependencies []NetworkDependency `json:"dependencies"`
	Milestones   []NetworkMilestone  `json:"milestones,omitempty"`
}

type NetworkDependency struct {
	Activity  string   `json:"activity"`
	DependsOn []string `json:"dependsOn"`
}

type NetworkMilestone struct {
	Id        string   `json:"id"`
	DependsOn []string `json:"dependsOn,omitempty"`
}

type NetworkMilestoneSolution struct {
	ID             string  `json:"ID"`
	OnCriticalPath bool    `json:"OnCriticalPath"`
	EventTime      float64 `json:"EventTime"`
}

type NetworkNode struct {
	EarliestStart  float64 `json:"EarliestStart"`
	EarliestFinish float64 `json:"EarliestFinish"`
	LatestStart    float64 `json:"LatestStart"`
	LatestFinish   float64 `json:"LatestFinish"`
	TotalFloat     float64 `json:"TotalFloat"`
	FreeFloat      float64 `json:"FreeFloat"`
	OnCriticalPath bool    `json:"OnCriticalPath"`
	NearCritical   bool    `json:"NearCritical"`
	Band           string  `json:"Band"`
	Column         int64   `json:"Column"`
}

type NetworkSolution struct {
	Nodes      map[string]NetworkNode     `json:"Nodes"`
	Milestones []NetworkMilestoneSolution `json:"Milestones"`
	Summary    NetworkSummary             `json:"Summary"`
}

type NetworkSummary struct {
	TotalDurationDays         float64 `json:"TotalDurationDays"`
	CriticalPathActivityCount int64   `json:"CriticalPathActivityCount"`
	CriticalPathDays          float64 `json:"CriticalPathDays"`
	MaxFloat                  float64 `json:"MaxFloat"`
	NearCriticalCount         int64   `json:"NearCriticalCount"`
}

type OptionActivity struct {
	ActivityId     string  `json:"activityId"`
	EffortDays     float64 `json:"effortDays"`
	WorkerClass    string  `json:"workerClass"`
	OnCriticalPath bool    `json:"onCriticalPath"`
	RiskBucket     int64   `json:"riskBucket"`
}

type OptionID string

type ProjectOption struct {
	OptionId            OptionID        `json:"optionId"`
	Network             ActivityNetwork `json:"network"`
	WorkerMix           WorkerMix       `json:"workerMix"`
	CalendarDaysPerWeek float64         `json:"calendarDaysPerWeek"`
}

type RiskScore struct {
	Composite       float64 `json:"Composite"`
	CriticalityRisk float64 `json:"CriticalityRisk"`
	ActivityRisk    float64 `json:"ActivityRisk"`
}

type WorkerMix struct {
	ClassRates  map[string]Money `json:"classRates"`
	StaffingCap int64            `json:"staffingCap"`
}

// EstimationEngine is the generated service-contract interface for this component.
type EstimationEngine interface {
	ComputeNetwork(activities ActivityList, network Network) (NetworkSolution, error)
	EstimateForOption(option ProjectOption) (ConstructionEstimate, error)
}
