// Code generated by cmd/modelgen from contract.schema.json; DO NOT EDIT.
// Edit the schema and re-run `make gen-models` instead.

package merchantgateway

import (
	"github.com/google/uuid"
	fwra "github.com/mixofreality-studio/archistrator-platform/framework-go/resourceaccess"
)

type GatewayBinding struct {
	ConnectedAccountID string `json:"ConnectedAccountID"`
}

type Money struct {
	MinorUnits int64  `json:"MinorUnits"`
	Currency   string `json:"Currency"`
}

// MerchantGatewayAccess is the generated service-contract interface for this component.
type MerchantGatewayAccess interface {
	ChargeCustomer(rc fwra.Context, customerID uuid.UUID, amount Money, idempotencyKey string) error
	CreateConnectedAccount(rc fwra.Context, customerID uuid.UUID, idempotencyKey string) (GatewayBinding, error)
	PayoutCustomer(rc fwra.Context, customerID uuid.UUID, amount Money, idempotencyKey string) error
	ValidateStoredInstrument(rc fwra.Context, customerID uuid.UUID, idempotencyKey string) error
}

// stubMerchantGatewayAccess is the generated not-implemented MerchantGatewayAccess. The component is contracted
// but not yet built, so every method returns a not-implemented error; the bodies
// are replaced when the component is constructed.
type stubMerchantGatewayAccess struct{}

// NewMerchantGatewayAccess returns the not-implemented MerchantGatewayAccess. It takes no arguments
// (the component has no infrastructure binding yet).
func NewMerchantGatewayAccess() MerchantGatewayAccess { return &stubMerchantGatewayAccess{} }

var _ MerchantGatewayAccess = (*stubMerchantGatewayAccess)(nil)

func (*stubMerchantGatewayAccess) ChargeCustomer(_ fwra.Context, _ uuid.UUID, _ Money, _ string) error {
	return fwra.New(fwra.Unknown, "not implemented")
}

func (*stubMerchantGatewayAccess) CreateConnectedAccount(_ fwra.Context, _ uuid.UUID, _ string) (GatewayBinding, error) {
	var zero GatewayBinding
	return zero, fwra.New(fwra.Unknown, "not implemented")
}

func (*stubMerchantGatewayAccess) PayoutCustomer(_ fwra.Context, _ uuid.UUID, _ Money, _ string) error {
	return fwra.New(fwra.Unknown, "not implemented")
}

func (*stubMerchantGatewayAccess) ValidateStoredInstrument(_ fwra.Context, _ uuid.UUID, _ string) error {
	return fwra.New(fwra.Unknown, "not implemented")
}
