// Code generated by cmd/modelgen from the service-contract interface; DO NOT EDIT.
// Edit project.json's `interface` and re-run `make gen-fakes` instead.

package estimationfake

import (
	fweng "github.com/mixofreality-studio/archistrator-platform/framework-go/engine"
	"github.com/mixofreality-studio/archistrator/server/internal/engine/estimation"
)

// FakeEstimationEngine is a generated test double for estimation.EstimationEngine: set the Fn field(s)
// a test needs; calling a method whose Fn is unset panics.
type FakeEstimationEngine struct {
	ComputeEarnedValueFn func(rc fweng.Context, activities estimation.ActivityList, network estimation.Network, integrated []string, totalWeeks int64, calendarDaysPerWeek int64) (estimation.EVCurve, error)
	ComputeNetworkFn     func(rc fweng.Context, activities estimation.ActivityList, network estimation.Network) (estimation.NetworkSolution, error)
	EstimateForOptionFn  func(rc fweng.Context, option estimation.ProjectOption) (estimation.ConstructionEstimate, error)
}

func (f *FakeEstimationEngine) ComputeEarnedValue(rc fweng.Context, activities estimation.ActivityList, network estimation.Network, integrated []string, totalWeeks int64, calendarDaysPerWeek int64) (estimation.EVCurve, error) {
	if f.ComputeEarnedValueFn == nil {
		panic("FakeEstimationEngine.ComputeEarnedValueFn not set")
	}
	return f.ComputeEarnedValueFn(rc, activities, network, integrated, totalWeeks, calendarDaysPerWeek)
}

func (f *FakeEstimationEngine) ComputeNetwork(rc fweng.Context, activities estimation.ActivityList, network estimation.Network) (estimation.NetworkSolution, error) {
	if f.ComputeNetworkFn == nil {
		panic("FakeEstimationEngine.ComputeNetworkFn not set")
	}
	return f.ComputeNetworkFn(rc, activities, network)
}

func (f *FakeEstimationEngine) EstimateForOption(rc fweng.Context, option estimation.ProjectOption) (estimation.ConstructionEstimate, error) {
	if f.EstimateForOptionFn == nil {
		panic("FakeEstimationEngine.EstimateForOptionFn not set")
	}
	return f.EstimateForOptionFn(rc, option)
}

var _ estimation.EstimationEngine = (*FakeEstimationEngine)(nil)
