// Code generated by cmd/clientgen (mcpemit). DO NOT EDIT.
// Source contract:

package operations

import (
	"context"
	"errors"
	"fmt"

	"github.com/google/jsonschema-go/jsonschema"
	"github.com/modelcontextprotocol/go-sdk/mcp"

	"github.com/google/uuid"

	fwmanager "github.com/mixofreality-studio/archistrator-platform/framework-go/manager"
	"github.com/mixofreality-studio/archistrator-platform/framework-go/utilities/security"
	mgr "github.com/mixofreality-studio/archistrator/server/internal/manager/operations"
)

// Handler binds the OperationsManager manager to MCP tools.
type Handler struct {
	Manager mgr.OperationsManager
}

// Register adds every operation as an mcp.Tool on srv, each carrying an
// explicit human description and an explicit input JSON Schema (enum values +
// meanings, REST-matching optionality) so an agentic consumer needs no source.
func (h *Handler) Register(srv *mcp.Server) {
	mcp.AddTool(srv, &mcp.Tool{Name: "operationsApplyDelinquencyPolicy", Description: "Apply the billing-delinquency policy to a customer (e.g. suspend or restore their operated systems) given the current delinquency context.", InputSchema: applyDelinquencyPolicyInputSchema()}, h.handleApplyDelinquencyPolicy)
	mcp.AddTool(srv, &mcp.Tool{Name: "operationsDeployAfterConstruction", Description: "Deploy a desired-state change to an operated application once its construction completes. Returns the deployment outcome.", InputSchema: deployAfterConstructionInputSchema()}, h.handleDeployAfterConstruction)
	mcp.AddTool(srv, &mcp.Tool{Name: "operationsQueryCostProjection", Description: "Project the operating cost of an operated application, optionally across scale/what-if points. requestID idempotently identifies the query. Read-only.", InputSchema: queryCostProjectionInputSchema()}, h.handleQueryCostProjection)
	mcp.AddTool(srv, &mcp.Tool{Name: "operationsQueryOperatedSystemView", Description: "Return the live operated-system view (runtime status and topology) for an operated application. requestID idempotently identifies the query. Read-only.", InputSchema: queryOperatedSystemViewInputSchema()}, h.handleQueryOperatedSystemView)
	mcp.AddTool(srv, &mcp.Tool{Name: "operationsReconcileOperatedState", Description: "Reconcile the actual operated state toward the desired state across the given scope (or everything when omitted). tickID idempotently identifies the reconcile tick.", InputSchema: reconcileOperatedStateInputSchema()}, h.handleReconcileOperatedState)
	mcp.AddTool(srv, &mcp.Tool{Name: "operationsWithdrawSystem", Description: "Withdraw and tear down an operated application (identified by its deploy changeID) for the given reason. Returns the withdrawal outcome.", InputSchema: withdrawSystemInputSchema()}, h.handleWithdrawSystem)
}

type applyDelinquencyPolicyInput struct {
	CustomerID         uuid.UUID              `json:"customerID"`
	DelinquencyContext mgr.DelinquencyContext `json:"delinquencyContext"`
}

type applyDelinquencyPolicyOutput struct{}

type deployAfterConstructionInput struct {
	OperatedAppID uuid.UUID              `json:"operatedAppID"`
	Change        mgr.DesiredStateChange `json:"change"`
}

type deployAfterConstructionOutput struct {
	Result mgr.DeployResult `json:"result"`
}

type queryCostProjectionInput struct {
	OperatedAppID uuid.UUID              `json:"operatedAppID"`
	RequestID     string                 `json:"requestID"`
	Points        *mgr.ScaleWhatIfPoints `json:"points,omitempty"`
}

type queryCostProjectionOutput struct {
	Result mgr.CostProjectionSeam `json:"result"`
}

type queryOperatedSystemViewInput struct {
	OperatedAppID uuid.UUID `json:"operatedAppID"`
	RequestID     string    `json:"requestID"`
}

type queryOperatedSystemViewOutput struct {
	Result mgr.OperatedSystemView `json:"result"`
}

type reconcileOperatedStateInput struct {
	TickID string              `json:"tickID"`
	Scope  *mgr.ReconcileScope `json:"scope,omitempty"`
}

type reconcileOperatedStateOutput struct {
	Result mgr.ReconcileResult `json:"result"`
}

type withdrawSystemInput struct {
	OperatedAppID uuid.UUID          `json:"operatedAppID"`
	ChangeID      string             `json:"changeID"`
	Reason        mgr.WithdrawReason `json:"reason"`
}

type withdrawSystemOutput struct {
	Result mgr.WithdrawResult `json:"result"`
}

// applyDelinquencyPolicyInputSchema is the explicit MCP input schema for the ApplyDelinquencyPolicy operation.
func applyDelinquencyPolicyInputSchema() *jsonschema.Schema {
	s := objectSchema[applyDelinquencyPolicyInput]()
	s.Required = []string{"customerID", "delinquencyContext"}
	return s
}

// deployAfterConstructionInputSchema is the explicit MCP input schema for the DeployAfterConstruction operation.
func deployAfterConstructionInputSchema() *jsonschema.Schema {
	s := objectSchema[deployAfterConstructionInput]()
	s.Required = []string{"operatedAppID", "change"}
	return s
}

// queryCostProjectionInputSchema is the explicit MCP input schema for the QueryCostProjection operation.
func queryCostProjectionInputSchema() *jsonschema.Schema {
	s := objectSchema[queryCostProjectionInput]()
	s.Required = []string{"operatedAppID", "requestID"}
	return s
}

// queryOperatedSystemViewInputSchema is the explicit MCP input schema for the QueryOperatedSystemView operation.
func queryOperatedSystemViewInputSchema() *jsonschema.Schema {
	s := objectSchema[queryOperatedSystemViewInput]()
	s.Required = []string{"operatedAppID", "requestID"}
	return s
}

// reconcileOperatedStateInputSchema is the explicit MCP input schema for the ReconcileOperatedState operation.
func reconcileOperatedStateInputSchema() *jsonschema.Schema {
	s := objectSchema[reconcileOperatedStateInput]()
	s.Required = []string{"tickID"}
	return s
}

// withdrawSystemInputSchema is the explicit MCP input schema for the WithdrawSystem operation.
func withdrawSystemInputSchema() *jsonschema.Schema {
	s := objectSchema[withdrawSystemInput]()
	s.Required = []string{"operatedAppID", "changeID", "reason"}
	return s
}

// handleApplyDelinquencyPolicy is the MCP tool handler for the ApplyDelinquencyPolicy operation.
func (h *Handler) handleApplyDelinquencyPolicy(ctx context.Context, _ *mcp.CallToolRequest, in applyDelinquencyPolicyInput) (*mcp.CallToolResult, applyDelinquencyPolicyOutput, error) {
	var out applyDelinquencyPolicyOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	if err := h.Manager.ApplyDelinquencyPolicy(rc, in.CustomerID, in.DelinquencyContext); err != nil {
		return nil, out, mapManagerError(err)
	}
	return nil, out, nil
}

// handleDeployAfterConstruction is the MCP tool handler for the DeployAfterConstruction operation.
func (h *Handler) handleDeployAfterConstruction(ctx context.Context, _ *mcp.CallToolRequest, in deployAfterConstructionInput) (*mcp.CallToolResult, deployAfterConstructionOutput, error) {
	var out deployAfterConstructionOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.DeployAfterConstruction(rc, in.OperatedAppID, in.Change)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleQueryCostProjection is the MCP tool handler for the QueryCostProjection operation.
func (h *Handler) handleQueryCostProjection(ctx context.Context, _ *mcp.CallToolRequest, in queryCostProjectionInput) (*mcp.CallToolResult, queryCostProjectionOutput, error) {
	var out queryCostProjectionOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.QueryCostProjection(rc, in.OperatedAppID, in.RequestID, in.Points)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleQueryOperatedSystemView is the MCP tool handler for the QueryOperatedSystemView operation.
func (h *Handler) handleQueryOperatedSystemView(ctx context.Context, _ *mcp.CallToolRequest, in queryOperatedSystemViewInput) (*mcp.CallToolResult, queryOperatedSystemViewOutput, error) {
	var out queryOperatedSystemViewOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.QueryOperatedSystemView(rc, in.OperatedAppID, in.RequestID)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleReconcileOperatedState is the MCP tool handler for the ReconcileOperatedState operation.
func (h *Handler) handleReconcileOperatedState(ctx context.Context, _ *mcp.CallToolRequest, in reconcileOperatedStateInput) (*mcp.CallToolResult, reconcileOperatedStateOutput, error) {
	var out reconcileOperatedStateOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.ReconcileOperatedState(rc, in.TickID, in.Scope)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleWithdrawSystem is the MCP tool handler for the WithdrawSystem operation.
func (h *Handler) handleWithdrawSystem(ctx context.Context, _ *mcp.CallToolRequest, in withdrawSystemInput) (*mcp.CallToolResult, withdrawSystemOutput, error) {
	var out withdrawSystemOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.WithdrawSystem(rc, in.OperatedAppID, in.ChangeID, in.Reason)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// --- helpers ---------------------------------------------------------------

// objectSchema infers the base object JSON Schema for a tool input struct via
// the SDK's reflection (the same inference the SDK would run for a nil input
// schema), so nested object/array params keep their structural shape; callers
// then override the required list and any enum properties. It panics on an
// un-inferrable type — a build-time contract error surfaced at server start.
func objectSchema[T any]() *jsonschema.Schema {
	s, err := jsonschema.For[T](nil)
	if err != nil {
		panic(fmt.Sprintf("mcp input schema inference: %v", err))
	}
	if s.Properties == nil {
		s.Properties = map[string]*jsonschema.Schema{}
	}
	return s
}

func mapManagerError(err error) error {
	var me *fwmanager.Error
	if errors.As(err, &me) {
		return fmt.Errorf("%s: %s", me.Kind.String(), me.Detail)
	}
	return err
}
