// Code generated by cmd/modelgen from contract.schema.json; DO NOT EDIT.
// Edit the schema and re-run `make gen-models` instead.

package handoff

import (
	fweng "github.com/mixofreality-studio/archistrator-platform/framework-go/engine"
)

type ActivityKind int

const (
	ActivityKindUnknown        ActivityKind = 0
	ActivityKindDetailedDesign ActivityKind = 1
	ActivityKindConstruction   ActivityKind = 2
	ActivityKindIntegration    ActivityKind = 3
	ActivityKindNoncoding      ActivityKind = 4
)

type ConstructionActivity struct {
	ActivityID   string       `json:"ActivityID"`
	Kind         ActivityKind `json:"Kind"`
	ComponentID  string       `json:"ComponentID"`
	Layer        string       `json:"Layer"`
	EstimateDays float64      `json:"EstimateDays"`
}

type HandOffPolicy struct {
	PreferAI         bool     `json:"PreferAI"`
	SeniorOnlyLayers []string `json:"SeniorOnlyLayers"`
}

type WorkerClass int

const (
	WorkerClassUnknown WorkerClass = 0
	AIWorker           WorkerClass = 1
	HumanSeniorWorker  WorkerClass = 2
	HumanJuniorWorker  WorkerClass = 3
	ArchitectOnly      WorkerClass = 4
)

// HandOffEngine is the generated service-contract interface for this component.
type HandOffEngine interface {
	PickWorkerClass(rc fweng.Context, activity ConstructionActivity, policy HandOffPolicy) (WorkerClass, error)
}

// HandOffEngineImpl is the generated concrete HandOffEngine. Engines are pure (no
// dependencies), so the impl carries no fields and the constructor takes none.
// The interface methods are hand-written on this struct.
type HandOffEngineImpl struct{}

// NewHandOffEngine returns the production HandOffEngine.
func NewHandOffEngine() HandOffEngine { return HandOffEngineImpl{} }

var _ HandOffEngine = HandOffEngineImpl{}
