// Code generated by temporalgen. DO NOT EDIT.

package systemdesign

import (
	"context"
	"fmt"

	"go.temporal.io/sdk/activity"

	fwmanager "github.com/mixofreality-studio/archistrator-platform/framework-go/manager"
	fwra "github.com/mixofreality-studio/archistrator-platform/framework-go/resourceaccess"

	"github.com/mixofreality-studio/archistrator/server/internal/resourceaccess/constructionpipeline"
	"github.com/mixofreality-studio/archistrator/server/internal/resourceaccess/projectstate"
	"github.com/mixofreality-studio/archistrator/server/internal/resourceaccess/sourcecontrol"
)

// genActivities hosts one Temporal Activity per operation of each
// ResourceAccess component dependency — the manager's architecture-approved
// call surface. Fields are the contract interfaces, threaded by RegisterWorker.
type genActivities struct {
	ProjectState  projectstate.ProjectStateAccess
	Pipeline      constructionpipeline.ConstructionPipelineAccess
	Rail          sourcecontrol.SourceControlAccess
	DesignSession projectstate.DesignSessionAccess
}

// genActivityIdempotencyKey derives the run-scoped 3-part key
// workflowID:runID:activityID (stable per logical write within a run,
// distinct across runs of the same workflow ID).
func genActivityIdempotencyKey(ctx context.Context) fwra.IdempotencyKey {
	info := activity.GetInfo(ctx)
	return fwra.IdempotencyKey(fmt.Sprintf("%s:%s:%s",
		info.WorkflowExecution.ID, info.WorkflowExecution.RunID, info.ActivityID))
}

// ProjectStateAcknowledgeStaleBasis wraps projectStateAccess.acknowledgeStaleBasis.
// Registered as "projectStateAccess.acknowledgeStaleBasis".
func (a *genActivities) ProjectStateAcknowledgeStaleBasis(ctx context.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, kind projectstate.ArtifactKind, note string) (projectstate.Version, error) {
	v, err := a.ProjectState.AcknowledgeStaleBasis(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, projectID, expectedVersion, kind, note, genActivityIdempotencyKey(ctx))
	return v, fwmanager.MapError(err)
}

// ProjectStateAdvancePhase wraps projectStateAccess.advancePhase.
// Registered as "projectStateAccess.advancePhase".
func (a *genActivities) ProjectStateAdvancePhase(ctx context.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version) (projectstate.Version, error) {
	v, err := a.ProjectState.AdvancePhase(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, projectID, expectedVersion)
	return v, fwmanager.MapError(err)
}

// ProjectStateCommitArtifact wraps projectStateAccess.commitArtifact.
// Registered as "projectStateAccess.commitArtifact".
func (a *genActivities) ProjectStateCommitArtifact(ctx context.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, kind projectstate.ArtifactKind) (projectstate.Version, error) {
	v, err := a.ProjectState.CommitArtifact(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, projectID, expectedVersion, kind)
	return v, fwmanager.MapError(err)
}

// ProjectStateCreateProject wraps projectStateAccess.createProject.
// Registered as "projectStateAccess.createProject".
func (a *genActivities) ProjectStateCreateProject(ctx context.Context, projectID projectstate.ProjectID, owner projectstate.OwnerScope, name string) (projectstate.Version, error) {
	v, err := a.ProjectState.CreateProject(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, projectID, owner, name)
	return v, fwmanager.MapError(err)
}

// ProjectStateListProjects wraps projectStateAccess.listProjects.
// Registered as "projectStateAccess.listProjects".
func (a *genActivities) ProjectStateListProjects(ctx context.Context, owner projectstate.OwnerScope) ([]projectstate.ProjectSummary, error) {
	v, err := a.ProjectState.ListProjects(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, owner)
	return v, fwmanager.MapError(err)
}

// ProjectStateReadProject wraps projectStateAccess.readProject.
// Registered as "projectStateAccess.readProject".
func (a *genActivities) ProjectStateReadProject(ctx context.Context, projectID projectstate.ProjectID) (projectstate.Project, error) {
	v, err := a.ProjectState.ReadProject(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, projectID)
	return v, fwmanager.MapError(err)
}

// ProjectStateReadProjectOnBranch wraps projectStateAccess.readProjectOnBranch.
// Registered as "projectStateAccess.readProjectOnBranch".
func (a *genActivities) ProjectStateReadProjectOnBranch(ctx context.Context, projectID projectstate.ProjectID, branch string) (projectstate.Project, error) {
	v, err := a.ProjectState.ReadProjectOnBranch(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, projectID, branch)
	return v, fwmanager.MapError(err)
}

// ProjectStateReadProjectVersion wraps projectStateAccess.readProjectVersion.
// Registered as "projectStateAccess.readProjectVersion".
func (a *genActivities) ProjectStateReadProjectVersion(ctx context.Context, projectID projectstate.ProjectID) (projectstate.Version, error) {
	v, err := a.ProjectState.ReadProjectVersion(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, projectID)
	return v, fwmanager.MapError(err)
}

// ProjectStateReconcileBranchFromMain wraps projectStateAccess.reconcileBranchFromMain.
// Registered as "projectStateAccess.reconcileBranchFromMain".
func (a *genActivities) ProjectStateReconcileBranchFromMain(ctx context.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, branch string, kind projectstate.ArtifactKind) (projectstate.Version, error) {
	v, err := a.ProjectState.ReconcileBranchFromMain(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, projectID, expectedVersion, branch, kind, genActivityIdempotencyKey(ctx))
	return v, fwmanager.MapError(err)
}

// ProjectStateRejectArtifact wraps projectStateAccess.rejectArtifact.
// Registered as "projectStateAccess.rejectArtifact".
func (a *genActivities) ProjectStateRejectArtifact(ctx context.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, kind projectstate.ArtifactKind, notes string) (projectstate.Version, error) {
	v, err := a.ProjectState.RejectArtifact(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, projectID, expectedVersion, kind, notes)
	return v, fwmanager.MapError(err)
}

// ProjectStateRejectArtifactOnBranch wraps projectStateAccess.rejectArtifactOnBranch.
// Registered as "projectStateAccess.rejectArtifactOnBranch".
func (a *genActivities) ProjectStateRejectArtifactOnBranch(ctx context.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, branch string, kind projectstate.ArtifactKind, notes string) (projectstate.Version, error) {
	v, err := a.ProjectState.RejectArtifactOnBranch(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, projectID, expectedVersion, branch, kind, notes, genActivityIdempotencyKey(ctx))
	return v, fwmanager.MapError(err)
}

// ProjectStateRejectArtifactOnBranchWithComments wraps projectStateAccess.rejectArtifactOnBranchWithComments.
// Registered as "projectStateAccess.rejectArtifactOnBranchWithComments".
func (a *genActivities) ProjectStateRejectArtifactOnBranchWithComments(ctx context.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, branch string, kind projectstate.ArtifactKind, notes string, round int64, comments []projectstate.ReviewComment) (projectstate.Version, error) {
	v, err := a.ProjectState.RejectArtifactOnBranchWithComments(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, projectID, expectedVersion, branch, kind, notes, round, comments, genActivityIdempotencyKey(ctx))
	return v, fwmanager.MapError(err)
}

// ProjectStateSeedReviewCommentsOnBranch wraps projectStateAccess.seedReviewCommentsOnBranch.
// Registered as "projectStateAccess.seedReviewCommentsOnBranch".
func (a *genActivities) ProjectStateSeedReviewCommentsOnBranch(ctx context.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, branch string, kind projectstate.ArtifactKind, round int64, comments []projectstate.ReviewComment) (projectstate.Version, error) {
	v, err := a.ProjectState.SeedReviewCommentsOnBranch(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, projectID, expectedVersion, branch, kind, round, comments, genActivityIdempotencyKey(ctx))
	return v, fwmanager.MapError(err)
}

// ProjectStateSetOperatingModel wraps projectStateAccess.setOperatingModel.
// Registered as "projectStateAccess.setOperatingModel".
func (a *genActivities) ProjectStateSetOperatingModel(ctx context.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, model projectstate.OperatingModel) (projectstate.Version, error) {
	v, err := a.ProjectState.SetOperatingModel(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, projectID, expectedVersion, model)
	return v, fwmanager.MapError(err)
}

// ProjectStateSetResearchInput wraps projectStateAccess.setResearchInput.
// Registered as "projectStateAccess.setResearchInput".
func (a *genActivities) ProjectStateSetResearchInput(ctx context.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, research projectstate.ResearchInput) (projectstate.Version, error) {
	v, err := a.ProjectState.SetResearchInput(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, projectID, expectedVersion, research)
	return v, fwmanager.MapError(err)
}

// ProjectStateSetReviewCommentStatusOnBranch wraps projectStateAccess.setReviewCommentStatusOnBranch.
// Registered as "projectStateAccess.setReviewCommentStatusOnBranch".
func (a *genActivities) ProjectStateSetReviewCommentStatusOnBranch(ctx context.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, branch string, kind projectstate.ArtifactKind, commentID string, status string) (projectstate.Version, error) {
	v, err := a.ProjectState.SetReviewCommentStatusOnBranch(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, projectID, expectedVersion, branch, kind, commentID, status, genActivityIdempotencyKey(ctx))
	return v, fwmanager.MapError(err)
}

// ProjectStateStageArtifactForReview wraps projectStateAccess.stageArtifactForReview.
// Registered as "projectStateAccess.stageArtifactForReview".
func (a *genActivities) ProjectStateStageArtifactForReview(ctx context.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, model projectstate.ArtifactModel) (projectstate.Version, error) {
	v, err := a.ProjectState.StageArtifactForReview(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, projectID, expectedVersion, model)
	return v, fwmanager.MapError(err)
}

// ProjectStateStageArtifactForReviewOnBranch wraps projectStateAccess.stageArtifactForReviewOnBranch.
// Registered as "projectStateAccess.stageArtifactForReviewOnBranch".
func (a *genActivities) ProjectStateStageArtifactForReviewOnBranch(ctx context.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, branch string, model projectstate.ArtifactModel) (projectstate.Version, error) {
	v, err := a.ProjectState.StageArtifactForReviewOnBranch(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, projectID, expectedVersion, branch, model, genActivityIdempotencyKey(ctx))
	return v, fwmanager.MapError(err)
}

// ProjectStateWithdrawArtifact wraps projectStateAccess.withdrawArtifact.
// Registered as "projectStateAccess.withdrawArtifact".
func (a *genActivities) ProjectStateWithdrawArtifact(ctx context.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, kind projectstate.ArtifactKind, notes string) (projectstate.Version, error) {
	v, err := a.ProjectState.WithdrawArtifact(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, projectID, expectedVersion, kind, notes)
	return v, fwmanager.MapError(err)
}

// ProjectStateWithdrawArtifactOnBranch wraps projectStateAccess.withdrawArtifactOnBranch.
// Registered as "projectStateAccess.withdrawArtifactOnBranch".
func (a *genActivities) ProjectStateWithdrawArtifactOnBranch(ctx context.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, branch string, kind projectstate.ArtifactKind, notes string) (projectstate.Version, error) {
	v, err := a.ProjectState.WithdrawArtifactOnBranch(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, projectID, expectedVersion, branch, kind, notes, genActivityIdempotencyKey(ctx))
	return v, fwmanager.MapError(err)
}

// PipelineCancelConstructionPipeline wraps constructionPipelineAccess.cancelConstructionPipeline.
// Registered as "constructionPipelineAccess.cancelConstructionPipeline".
func (a *genActivities) PipelineCancelConstructionPipeline(ctx context.Context, handle constructionpipeline.PipelineHandle) error {
	err := a.Pipeline.CancelConstructionPipeline(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, handle)
	return fwmanager.MapError(err)
}

// PipelineObserveConstructionPipeline wraps constructionPipelineAccess.observeConstructionPipeline.
// Registered as "constructionPipelineAccess.observeConstructionPipeline".
func (a *genActivities) PipelineObserveConstructionPipeline(ctx context.Context, handle constructionpipeline.PipelineHandle) (constructionpipeline.PipelineObservation, error) {
	v, err := a.Pipeline.ObserveConstructionPipeline(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, handle)
	return v, fwmanager.MapError(err)
}

// PipelineSubmitConstructionPipeline wraps constructionPipelineAccess.submitConstructionPipeline.
// Registered as "constructionPipelineAccess.submitConstructionPipeline".
func (a *genActivities) PipelineSubmitConstructionPipeline(ctx context.Context, spec constructionpipeline.PipelineSpec) (constructionpipeline.PipelineHandle, error) {
	v, err := a.Pipeline.SubmitConstructionPipeline(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, spec)
	return v, fwmanager.MapError(err)
}

// RailAdoptProjectRepo wraps sourceControlAccess.adoptProjectRepo.
// Registered as "sourceControlAccess.adoptProjectRepo".
func (a *genActivities) RailAdoptProjectRepo(ctx context.Context, spec sourcecontrol.RepoAdoptionSpec) (sourcecontrol.RepoRef, error) {
	v, err := a.Rail.AdoptProjectRepo(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, spec)
	return v, fwmanager.MapError(err)
}

// RailCommitManagedFiles wraps sourceControlAccess.commitManagedFiles.
// Registered as "sourceControlAccess.commitManagedFiles".
func (a *genActivities) RailCommitManagedFiles(ctx context.Context, repo sourcecontrol.RepoRef, files []sourcecontrol.ManagedFile, cred sourcecontrol.RepoCredential) (sourcecontrol.CommitRef, error) {
	v, err := a.Rail.CommitManagedFiles(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, repo, files, cred)
	return v, fwmanager.MapError(err)
}

// RailConfigureBranchProtection wraps sourceControlAccess.configureBranchProtection.
// Registered as "sourceControlAccess.configureBranchProtection".
func (a *genActivities) RailConfigureBranchProtection(ctx context.Context, repo sourcecontrol.RepoRef, cred sourcecontrol.RepoCredential) error {
	err := a.Rail.ConfigureBranchProtection(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, repo, cred)
	return fwmanager.MapError(err)
}

// RailGetInstallationToken wraps sourceControlAccess.getInstallationToken.
// Registered as "sourceControlAccess.getInstallationToken".
func (a *genActivities) RailGetInstallationToken(ctx context.Context, repo sourcecontrol.RepoRef) (sourcecontrol.RepoCredential, error) {
	v, err := a.Rail.GetInstallationToken(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, repo)
	return v, fwmanager.MapError(err)
}

// RailGetPullRequestStatus wraps sourceControlAccess.getPullRequestStatus.
// Registered as "sourceControlAccess.getPullRequestStatus".
func (a *genActivities) RailGetPullRequestStatus(ctx context.Context, repo sourcecontrol.RepoRef, pr sourcecontrol.PullRequestRef, cred sourcecontrol.RepoCredential) (sourcecontrol.PullRequestStatus, error) {
	v, err := a.Rail.GetPullRequestStatus(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, repo, pr, cred)
	return v, fwmanager.MapError(err)
}

// RailInstallAuthorizeApp wraps sourceControlAccess.installAuthorizeApp.
// Registered as "sourceControlAccess.installAuthorizeApp".
func (a *genActivities) RailInstallAuthorizeApp(ctx context.Context, account sourcecontrol.AccountRef) (sourcecontrol.Installation, error) {
	v, err := a.Rail.InstallAuthorizeApp(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, account)
	return v, fwmanager.MapError(err)
}

// RailMergePullRequest wraps sourceControlAccess.mergePullRequest.
// Registered as "sourceControlAccess.mergePullRequest".
func (a *genActivities) RailMergePullRequest(ctx context.Context, repo sourcecontrol.RepoRef, pr sourcecontrol.PullRequestRef, cred sourcecontrol.RepoCredential) (sourcecontrol.MergeResult, error) {
	v, err := a.Rail.MergePullRequest(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, repo, pr, cred)
	return v, fwmanager.MapError(err)
}

// RailOpenBranch wraps sourceControlAccess.openBranch.
// Registered as "sourceControlAccess.openBranch".
func (a *genActivities) RailOpenBranch(ctx context.Context, repo sourcecontrol.RepoRef, branch sourcecontrol.BranchName, cred sourcecontrol.RepoCredential) (sourcecontrol.BranchRef, error) {
	v, err := a.Rail.OpenBranch(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, repo, branch, cred)
	return v, fwmanager.MapError(err)
}

// RailOpenPullRequest wraps sourceControlAccess.openPullRequest.
// Registered as "sourceControlAccess.openPullRequest".
func (a *genActivities) RailOpenPullRequest(ctx context.Context, repo sourcecontrol.RepoRef, spec sourcecontrol.PullRequestSpec, cred sourcecontrol.RepoCredential) (sourcecontrol.PullRequestRef, error) {
	v, err := a.Rail.OpenPullRequest(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, repo, spec, cred)
	return v, fwmanager.MapError(err)
}

// RailPostReview wraps sourceControlAccess.postReview.
// Registered as "sourceControlAccess.postReview".
func (a *genActivities) RailPostReview(ctx context.Context, repo sourcecontrol.RepoRef, pr sourcecontrol.PullRequestRef, review sourcecontrol.ReviewSubmission, cred sourcecontrol.RepoCredential) error {
	err := a.Rail.PostReview(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, repo, pr, review, cred)
	return fwmanager.MapError(err)
}

// RailSyncManagedScaffold wraps sourceControlAccess.syncManagedScaffold.
// Registered as "sourceControlAccess.syncManagedScaffold".
func (a *genActivities) RailSyncManagedScaffold(ctx context.Context, repo sourcecontrol.RepoRef, cred sourcecontrol.RepoCredential) (bool, error) {
	v, err := a.Rail.SyncManagedScaffold(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, repo, cred)
	return v, fwmanager.MapError(err)
}

// DesignSessionCommitArtifactWithProvenance wraps designSessionAccess.commitArtifactWithProvenance.
// Registered as "designSessionAccess.commitArtifactWithProvenance".
func (a *genActivities) DesignSessionCommitArtifactWithProvenance(ctx context.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, kind projectstate.ArtifactKind, approvedBy string, draftedBy string) (projectstate.Version, error) {
	v, err := a.DesignSession.CommitArtifactWithProvenance(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, projectID, expectedVersion, kind, approvedBy, draftedBy)
	return v, fwmanager.MapError(err)
}

// DesignSessionReadProjectOnBranch wraps designSessionAccess.readProjectOnBranch.
// Registered as "designSessionAccess.readProjectOnBranch".
func (a *genActivities) DesignSessionReadProjectOnBranch(ctx context.Context, projectID projectstate.ProjectID, branch string) (projectstate.ProjectEnvelope, error) {
	v, err := a.DesignSession.ReadProjectOnBranch(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, projectID, branch)
	return v, fwmanager.MapError(err)
}

// DesignSessionReconcileBranchFromMain wraps designSessionAccess.reconcileBranchFromMain.
// Registered as "designSessionAccess.reconcileBranchFromMain".
func (a *genActivities) DesignSessionReconcileBranchFromMain(ctx context.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, branch string, kind projectstate.ArtifactKind) (projectstate.Version, error) {
	v, err := a.DesignSession.ReconcileBranchFromMain(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, projectID, expectedVersion, branch, kind, genActivityIdempotencyKey(ctx))
	return v, fwmanager.MapError(err)
}

// DesignSessionRejectArtifactOnBranchWithComments wraps designSessionAccess.rejectArtifactOnBranchWithComments.
// Registered as "designSessionAccess.rejectArtifactOnBranchWithComments".
func (a *genActivities) DesignSessionRejectArtifactOnBranchWithComments(ctx context.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, branch string, kind projectstate.ArtifactKind, notes string, round int64, comments []projectstate.ReviewComment) (projectstate.Version, error) {
	v, err := a.DesignSession.RejectArtifactOnBranchWithComments(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, projectID, expectedVersion, branch, kind, notes, round, comments, genActivityIdempotencyKey(ctx))
	return v, fwmanager.MapError(err)
}

// DesignSessionSeedReviewCommentsOnBranch wraps designSessionAccess.seedReviewCommentsOnBranch.
// Registered as "designSessionAccess.seedReviewCommentsOnBranch".
func (a *genActivities) DesignSessionSeedReviewCommentsOnBranch(ctx context.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, branch string, kind projectstate.ArtifactKind, round int64, comments []projectstate.ReviewComment) (projectstate.Version, error) {
	v, err := a.DesignSession.SeedReviewCommentsOnBranch(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, projectID, expectedVersion, branch, kind, round, comments, genActivityIdempotencyKey(ctx))
	return v, fwmanager.MapError(err)
}

// DesignSessionSetReviewCommentStatusOnBranch wraps designSessionAccess.setReviewCommentStatusOnBranch.
// Registered as "designSessionAccess.setReviewCommentStatusOnBranch".
func (a *genActivities) DesignSessionSetReviewCommentStatusOnBranch(ctx context.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, branch string, kind projectstate.ArtifactKind, commentID string, status string) (projectstate.Version, error) {
	v, err := a.DesignSession.SetReviewCommentStatusOnBranch(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, projectID, expectedVersion, branch, kind, commentID, status, genActivityIdempotencyKey(ctx))
	return v, fwmanager.MapError(err)
}

// DesignSessionStageArtifactForReviewOnBranch wraps designSessionAccess.stageArtifactForReviewOnBranch.
// Registered as "designSessionAccess.stageArtifactForReviewOnBranch".
func (a *genActivities) DesignSessionStageArtifactForReviewOnBranch(ctx context.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, branch string, model projectstate.ModelEnvelope) (projectstate.Version, error) {
	v, err := a.DesignSession.StageArtifactForReviewOnBranch(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, projectID, expectedVersion, branch, model, genActivityIdempotencyKey(ctx))
	return v, fwmanager.MapError(err)
}

// DesignSessionWithdrawArtifactOnBranch wraps designSessionAccess.withdrawArtifactOnBranch.
// Registered as "designSessionAccess.withdrawArtifactOnBranch".
func (a *genActivities) DesignSessionWithdrawArtifactOnBranch(ctx context.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, branch string, kind projectstate.ArtifactKind, notes string) (projectstate.Version, error) {
	v, err := a.DesignSession.WithdrawArtifactOnBranch(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, projectID, expectedVersion, branch, kind, notes, genActivityIdempotencyKey(ctx))
	return v, fwmanager.MapError(err)
}
