// Code generated by cmd/modelgen from contract.schema.json; DO NOT EDIT.
// Edit the schema and re-run `make gen-models` instead.

package systemdesign

import (
	"encoding/json"
	fwm "github.com/mixofreality-studio/archistrator-platform/framework-go/manager"
)

type AnchoredComment struct {
	JSONPath string `json:"jsonPath"`
	Text     string `json:"text"`
}

type ArtifactKind int

const (
	KindMission              ArtifactKind = 0
	KindGlossary             ArtifactKind = 1
	KindScrubbedRequirements ArtifactKind = 2
	KindVolatilities         ArtifactKind = 3
	KindCoreUseCases         ArtifactKind = 4
	KindSystem               ArtifactKind = 5
	KindOperationalConcepts  ArtifactKind = 6
	KindStandardCheck        ArtifactKind = 7
	KindPlanningAssumptions  ArtifactKind = 8
	KindActivityList         ArtifactKind = 9
	KindNetwork              ArtifactKind = 10
	KindNormalSolution       ArtifactKind = 11
	KindSubcriticalSolution  ArtifactKind = 12
	KindCompressedSolution   ArtifactKind = 13
	KindDecompressedSolution ArtifactKind = 14
	KindRiskModel            ArtifactKind = 15
	KindSdpReview            ArtifactKind = 16
)

type DraftModel struct {
	Kind  string           `json:"kind"`
	Model *json.RawMessage `json:"model,omitempty"`
}

type Finding struct {
	RuleID   RuleID    `json:"ruleId"`
	Severity Severity  `json:"severity"`
	Message  string    `json:"message"`
	Location *Location `json:"location,omitempty"`
}

type Location struct {
	Ordinal int64  `json:"ordinal"`
	Section string `json:"section"`
}

type PhaseAdvanceResult struct {
	Advanced         bool           `json:"advanced"`
	MissingArtifacts []ArtifactKind `json:"missingArtifacts"`
}

type ProjectID string

type ResearchInput struct {
	Sources []ResearchSource `json:"sources"`
}

type ResearchSource struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type ReviewDecision int

const (
	ReviewDecisionUnknown ReviewDecision = 0
	ReviewApprove         ReviewDecision = 1
	ReviewReject          ReviewDecision = 2
	ReviewWithdraw        ReviewDecision = 3
)

type ReviewFeedback struct {
	Notes    string            `json:"notes"`
	Comments []AnchoredComment `json:"comments,omitempty"`
}

type RuleID string

type SessionRef string

type SessionStage int

const (
	SessionStageUnknown SessionStage = 0
	StageDrafting       SessionStage = 1
	StageAwaitingReview SessionStage = 2
	StageRedrafting     SessionStage = 3
	StageCommitted      SessionStage = 4
	StageWithdrawn      SessionStage = 5
	StageRefused        SessionStage = 6
	StageDraftFailed    SessionStage = 7
)

type SessionStateView struct {
	ProjectID     ProjectID    `json:"projectId"`
	ArtifactKind  ArtifactKind `json:"artifactKind"`
	Stage         SessionStage `json:"stage"`
	Draft         DraftModel   `json:"draft"`
	Findings      []Finding    `json:"findings,omitempty"`
	FailureReason *string      `json:"failureReason,omitempty"`
}

type Severity string

const (
	SeverityInfo    Severity = "info"
	SeverityWarning Severity = "warning"
	SeverityError   Severity = "error"
)

type Version int64

// SystemDesignManager is the generated service-contract interface for this component.
type SystemDesignManager interface {
	AdvancePhase(rc fwm.Context, projectID ProjectID) (PhaseAdvanceResult, error)
	GetSessionState(rc fwm.Context, projectID ProjectID, kind ArtifactKind) (SessionStateView, error)
	RequestArtifactDraft(rc fwm.Context, projectID ProjectID, kind ArtifactKind, feedback *ReviewFeedback) (SessionRef, error)
	SetResearchInput(rc fwm.Context, projectID ProjectID, research ResearchInput) (Version, error)
	StartSystemDesign(rc fwm.Context, projectID ProjectID) (SessionRef, error)
	SubmitReviewDecision(rc fwm.Context, projectID ProjectID, kind ArtifactKind, decision ReviewDecision, feedback *ReviewFeedback) error
}
