/**
 * Centralized UI test identifiers (data-testid). No magic strings in components
 * or tests — reference these. The future black-box uitests Playwright package
 * selects interactive elements by these stable ids.
 */
export const UI_IDENTIFIERS = {
  Shell: {
    APP_BAR: 'app-bar',
    APP_SHELL: 'app-shell',
    BRAND: 'app-shell-brand',
    PROJECT_MENU: 'project-menu',
    projectMenuItem: (projectId: string) => `project-menu-item-${projectId}`,
    PROJECT_MENU_NEW: 'project-menu-new',
    ACCOUNT_MENU_BUTTON: 'account-menu-button',
    ACCOUNT_MENU_HOME: 'account-menu-home',
    ACCOUNT_MENU_ALL_PROJECTS: 'account-menu-all-projects',
    ACCOUNT_MENU_CHANGES: 'account-menu-changes',
    ACCOUNT_MENU_BILLING: 'account-menu-billing',
    ACCOUNT_MENU_TEAM: 'account-menu-team',
    TEAM_NAV: 'team-nav',
    USER_LABEL: 'user-label',
    LOGOUT_BUTTON: 'logout-button',
    DEV_MODE_BADGE: 'dev-mode-badge',
    THEME_SWITCHER: 'theme-switcher',
    themeOption: (key: string) => `theme-option-${key}`,
  },
  ProjectsLanding: {
    SCREEN: 'projects-landing-screen',
    GRID: 'projects-grid',
    EMPTY_STATE: 'empty-state',
    NEW_PROJECT_CARD: 'new-project-card',
    NEW_PROJECT_BUTTON: 'new-project-button',
    CREATE_PROJECT_DIALOG: 'create-project-dialog',
    NEW_PROJECT_NAME_INPUT: 'new-project-name-input',
    CREATE_PROJECT_SUBMIT: 'create-project-submit',
    CREATE_PROJECT_CANCEL: 'create-project-cancel',
    CREATE_PROJECT_PREREQS: 'create-project-prereqs',
    projectCard: (projectId: string) => `project-card-${projectId}`,
  },
  HomeBase: {
    SCREEN: 'home-base-screen',
    RESUME_DESIGN: 'resume-design',
    ECONOMICS_STRIP: 'economics-strip',
    ARTIFACT_TOC: 'artifact-toc',
    ARTIFACT_PROSE: 'artifact-prose',
    phaseCard: (phase: string) => `phase-card-${phase}`,
    tocRow: (kind: string) => `toc-row-${kind}`,
    OPEN_SYSTEM_DESIGN: 'open-system-design',
    OPEN_PROJECT_DESIGN: 'open-project-design',
  },
  DesignWizard: {
    SCREEN: 'design-wizard-screen',
    artifactStep: (kind: string) => `artifact-step-${kind}`,
  },
  DesignExperience: {
    ROOT: 'design-experience',
    CLOSE: 'design-close',
    SLIM_SPINE: 'slim-spine',
    spineStep: (kind: string) => `spine-step-${kind}`,
    REQUEST_DRAFT: 'request-draft',
    RESEARCH_INPUT: 'research-input',
    RESEARCH_INPUT_TITLE: 'research-input-title',
    RESEARCH_INPUT_TEXT: 'research-input-text',
    RESEARCH_INPUT_SUBMIT: 'research-input-submit',
    GENERATING_SCENE: 'generating-scene',
    CI_JOB_NOTICE: 'ci-job-notice',
    CI_JOB_LINK: 'ci-job-link',
    ARTIFACT_INTRO: 'artifact-intro',
    ARTIFACT_RENDER: 'artifact-render',
    DRAFT_FAILED: 'draft-failed',
    DRAFT_FAILURE_REASON: 'draft-failure-reason',
    RETRY_DRAFT: 'retry-draft',
    WITHDRAW_DRAFT: 'withdraw-draft',
  },
  Architecture: {
    VIEW_SWITCH: 'arch-view-switch',
    VIEW_STATIC: 'static',
    VIEW_DYNAMIC: 'dynamic',
    VIEW_PERSPECTIVE: 'perspective',
    DYNAMIC_PICKER: 'arch-dynamic-picker',
    PERSPECTIVE_PICKER: 'arch-perspective-picker',
  },
  Deployment: {
    PROFILE_SWITCH: 'deploy-profile-switch',
  },
  GatePanel: {
    ROOT: 'gate-panel',
    APPROVE: 'gate-approve',
    SENDBACK: 'gate-sendback',
    WITHDRAW: 'gate-withdraw',
    FINDINGS: 'findings',
  },
  Chat: {
    RAIL: 'chat-rail',
    TOGGLE: 'chat-toggle',
    SEND: 'chat-send',
    INPUT: 'chat-input',
    commentAnchor: (n: number) => `comment-anchor-${String(n)}`,
  },
  ProjectDesign: {
    SDP_ASSEMBLE: 'sdp-assemble',
    ADVANCE_CONSTRUCTION: 'advance-construction',
    ADVANCE_RESULT: 'advance-result',
  },
  Construction: {
    ROOT: 'construction-console',
    TAB_TRACKER: 'construction-tab-tracker',
    TAB_INTERVENTIONS: 'construction-tab-interventions',
    TAB_ARTIFACTS: 'construction-tab-artifacts',
    SUMMARY_STRIP: 'construction-summary-strip',
    TRACKER: 'construction-tracker',
    AWAITING: 'construction-awaiting',
    ACTIVE_DETAIL: 'construction-active-detail',
    INTERVENTIONS: 'construction-interventions',
    ARTIFACTS: 'construction-artifacts',
    BEGIN_BUTTON: 'construction-begin',
    PAUSE_BUTTON: 'construction-pause',
    PAUSE_REASON: 'construction-pause-reason',
    PAUSE_CONFIRM: 'construction-pause-confirm',
    OVERRIDE_BUTTON: 'construction-override',
    overrideKind: (kind: string) => `construction-override-${kind}`,
    OVERRIDE_NOTES: 'construction-override-notes',
    OVERRIDE_CONFIRM: 'construction-override-confirm',
    trackerNode: (id: string) => `construction-track-node-${id}`,
    ACTIVITY_LIFECYCLE_PANEL: 'construction-activity-lifecycle-panel',
    POLICY_PANEL: 'construction-policy-panel',
    policyRowToggle: (kind: string) => `construction-policy-toggle-${kind}`,
    PHASE_GATE_PANEL: 'construction-phase-gate-panel',
    PHASE_GATE_APPROVE: 'construction-phase-gate-approve',
    PHASE_GATE_SENDBACK: 'construction-phase-gate-sendback',
    // Intervention queue + drawer test IDs (U-SPA-INTERVENTION)
    INTERVENTION_QUEUE_COUNT: 'construction-intervention-queue-count',
    interventionQueueCard: (activityId: string) => `construction-intervention-card-${activityId}`,
    interventionReviewButton: (activityId: string) =>
      `construction-intervention-review-${activityId}`,
    INTERVENTION_DRAWER: 'construction-intervention-drawer',
    INTERVENTION_DRAWER_CLOSE: 'construction-intervention-drawer-close',
    INTERVENTION_OPERATOR_BAR: 'construction-intervention-operator-bar',
    interventionSteerButton: (kind: string) => `construction-intervention-steer-${kind}`,
  },
  // The GIT-FORWARD per-activity row cluster (U-SPA-GIT). The shared chrome the
  // construction tracker (and future CR/operations surfaces) render per
  // git-backed activity, keyed by ActivityID via gitFor(...).
  Git: {
    ROW_META: 'git-row-meta',
    PR_LINK: 'git-pr-link',
    BRANCH: 'git-branch',
    MERGED: 'git-merged',
    CR_LABEL: 'git-cr-label',
    ARCH_APPROVED: 'git-arch-approved',
    ciStatus: (status: string) => `git-ci-${status}`,
  },
  ServiceContract: {
    ROOT: 'service-contract-view',
    TAB_CODE: 'service-contract-tab-code',
    TAB_COMPONENT: 'service-contract-tab-component',
    TAB_DYNAMIC: 'service-contract-tab-dynamic',
    TAB_FACETS: 'service-contract-tab-facets',
    REVISION_HISTORY: 'service-contract-revision-history',
    revisionRow: (rev: string) => `service-contract-revision-${rev}`,
    COMPONENT_FLOW: 'service-contract-component-flow',
  },
  Operations: {
    ROOT: 'operations-console',
    TAB_STATUS: 'operations-tab-status',
    TAB_DEPLOYMENTS: 'operations-tab-deployments',
    TAB_SCALING: 'operations-tab-scaling',
    TAB_INTERVENTIONS: 'operations-tab-interventions',
    APP_SELECTOR: 'operations-app-selector',
    appOption: (id: string) => `operations-app-option-${id}`,
    STATUS_TAB: 'operations-status-tab',
    DEPLOYMENTS_TAB: 'operations-deployments-tab',
    SCALING_TAB: 'operations-scaling-tab',
    INTERVENTIONS_TAB: 'operations-interventions-tab',
    AWAITING: 'operations-awaiting',
    DEPLOY_BUTTON: 'operations-deploy',
    SCALE_BUTTON: 'operations-scale',
    AUTOSCALER_POLICY_BUTTON: 'operations-autoscaler-policy',
    WITHDRAW_BUTTON: 'operations-withdraw',
    BILLING_LINK: 'operations-billing-link',
  },
  ChangeRequests: {
    ROOT: 'change-requests-screen',
    CLOSE: 'change-requests-close',
    INTAKE_OPEN: 'change-requests-intake-open',
    INTAKE_TITLE: 'change-requests-intake-title',
    INTAKE_BODY: 'change-requests-intake-body',
    INTAKE_SUBMIT: 'change-requests-intake-submit',
    INTAKE_CANCEL: 'change-requests-intake-cancel',
    EMPTY_STATE: 'change-requests-empty',
    subprojectCard: (id: string) => `change-requests-subproject-${id}`,
  },
  Subproject: {
    ROOT: 'subproject-flow-screen',
    CLOSE: 'subproject-flow-close',
    NOT_READY: 'subproject-flow-not-ready',
    BACK: 'subproject-flow-back',
  },
  Billing: {
    ROOT: 'billing-screen',
    PENDING_STATE: 'billing-pending',
    HOME_LINK: 'billing-home-link',
  },
  Team: {
    ROOT: 'team-screen',
    roleCard: (id: string) => `team-role-card-${id}`,
    CHARTER_DRAWER: 'team-charter-drawer',
    CHARTER_CLOSE: 'team-charter-close',
    TOGGLE_PROMPT: 'team-charter-toggle-prompt',
  },
  SdpReview: {
    ROOT: 'sdp-review',
    GATE: 'sdp-gate',
    COMMIT: 'sdp-commit',
    REJECT_ALL: 'sdp-reject-all',
    REJECT_FEEDBACK: 'sdp-reject-feedback',
    REJECT_SUBMIT: 'sdp-reject-submit',
    optionCard: (optionId: string) => `sdp-option-${optionId}`,
  },
  Gate: {
    STAGE_CHIP: 'gate-stage-chip',
    REQUEST_DRAFT_BUTTON: 'gate-request-draft-button',
    DRAFT_DISPLAY: 'gate-draft-display',
    FINDINGS_LIST: 'gate-findings-list',
    APPROVE_BUTTON: 'gate-approve-button',
    REJECT_BUTTON: 'gate-reject-button',
    WITHDRAW_BUTTON: 'gate-withdraw-button',
    FEEDBACK_INPUT: 'gate-feedback-input',
  },
  Common: {
    ERROR_ALERT: 'error-alert',
    LOADING: 'loading-indicator',
  },
} as const;
