// Code generated by scripts/gen-ops.mjs. DO NOT EDIT.
/**
 * OpsClient — one call surface, two transports:
 *  - restOpsClient: REST over openapi-fetch (the standalone SPA, apiClient).
 *  - mcpOpsClient: MCP tool calls over App.callServerTool (the app hosted
 *    inside an MCP client via @modelcontextprotocol/ext-apps).
 *
 * OP_BINDINGS is mechanically derived from the server OAS at generation time
 * (see scripts/gen-ops.mjs): every '/api/v1/<mgr>/<op>[/{...}]' path yields an
 * OpId '<camelMgr><PascalOp>' bound to its {method, path, tool}. Hooks depend
 * only on OpsClient/OpId — never on which transport is live — via
 * useOpsClient() (src/api/opsContext.tsx).
 */
import type createClient from 'openapi-fetch';
import type { paths } from '../contracts/schema';
import type { App } from '@modelcontextprotocol/ext-apps';
// Runtime (value) import — needs the explicit .ts extension so this module also
// resolves under node --test's native type-stripping loader (which, unlike
// tsc's bundler moduleResolution, requires full specifiers). The type-only
// imports above are erased entirely and never hit Node's resolver, so they
// keep the extensionless convention the rest of the app uses.
import { ApiError, toApiError, type WireError } from '../contracts/errors.ts';

export const OP_BINDINGS = {
  constructionExecuteNextActivity: {
    method: 'POST',
    path: '/api/v1/construction/execute-next-activity/{projectID}',
    tool: 'constructionExecuteNextActivity',
  },
  constructionGetSessionState: {
    method: 'GET',
    path: '/api/v1/construction/get-session-state/{projectID}/{activityID}',
    tool: 'constructionGetSessionState',
  },
  constructionOverrideActivity: {
    method: 'POST',
    path: '/api/v1/construction/override-activity/{projectID}/{activityID}',
    tool: 'constructionOverrideActivity',
  },
  constructionPauseProject: {
    method: 'POST',
    path: '/api/v1/construction/pause-project/{projectID}',
    tool: 'constructionPauseProject',
  },
  constructionRunReplanSweep: {
    method: 'POST',
    path: '/api/v1/construction/run-replan-sweep/{projectID}',
    tool: 'constructionRunReplanSweep',
  },
  constructionSetReviewPolicy: {
    method: 'POST',
    path: '/api/v1/construction/set-review-policy/{projectID}',
    tool: 'constructionSetReviewPolicy',
  },
  constructionSubmitPhaseDecision: {
    method: 'POST',
    path: '/api/v1/construction/submit-phase-decision/{projectID}/{activityID}',
    tool: 'constructionSubmitPhaseDecision',
  },
  constructionUpdateReviewPolicy: {
    method: 'POST',
    path: '/api/v1/construction/update-review-policy/{projectID}',
    tool: 'constructionUpdateReviewPolicy',
  },
  operationsApplyDelinquencyPolicy: {
    method: 'POST',
    path: '/api/v1/operations/apply-delinquency-policy/{customerID}',
    tool: 'operationsApplyDelinquencyPolicy',
  },
  operationsDeployAfterConstruction: {
    method: 'POST',
    path: '/api/v1/operations/deploy-after-construction/{operatedAppID}',
    tool: 'operationsDeployAfterConstruction',
  },
  operationsQueryCostProjection: {
    method: 'POST',
    path: '/api/v1/operations/query-cost-projection/{operatedAppID}',
    tool: 'operationsQueryCostProjection',
  },
  operationsQueryOperatedSystemView: {
    method: 'GET',
    path: '/api/v1/operations/query-operated-system-view/{operatedAppID}',
    tool: 'operationsQueryOperatedSystemView',
  },
  operationsReconcileOperatedState: {
    method: 'POST',
    path: '/api/v1/operations/reconcile-operated-state',
    tool: 'operationsReconcileOperatedState',
  },
  operationsWithdrawSystem: {
    method: 'POST',
    path: '/api/v1/operations/withdraw-system/{operatedAppID}',
    tool: 'operationsWithdrawSystem',
  },
  projectDesignAcknowledgeStaleBasis: {
    method: 'POST',
    path: '/api/v1/project-design/acknowledge-stale-basis/{projectID}',
    tool: 'projectDesignAcknowledgeStaleBasis',
  },
  projectDesignAdvanceToConstruction: {
    method: 'POST',
    path: '/api/v1/project-design/advance-to-construction/{projectID}',
    tool: 'projectDesignAdvanceToConstruction',
  },
  projectDesignAskQuestions: {
    method: 'POST',
    path: '/api/v1/project-design/ask-questions/{projectID}',
    tool: 'projectDesignAskQuestions',
  },
  projectDesignGetSessionState: {
    method: 'GET',
    path: '/api/v1/project-design/get-session-state/{projectID}',
    tool: 'projectDesignGetSessionState',
  },
  projectDesignRequestArtifactDraft: {
    method: 'POST',
    path: '/api/v1/project-design/request-artifact-draft/{projectID}',
    tool: 'projectDesignRequestArtifactDraft',
  },
  projectDesignRequestSdpCommit: {
    method: 'POST',
    path: '/api/v1/project-design/request-sdp-commit/{projectID}',
    tool: 'projectDesignRequestSdpCommit',
  },
  projectDesignSetReviewCommentStatus: {
    method: 'POST',
    path: '/api/v1/project-design/set-review-comment-status/{projectID}',
    tool: 'projectDesignSetReviewCommentStatus',
  },
  projectDesignSubmitReviewDecision: {
    method: 'POST',
    path: '/api/v1/project-design/submit-review-decision/{projectID}',
    tool: 'projectDesignSubmitReviewDecision',
  },
  projectDesignSubmitSdpDecision: {
    method: 'POST',
    path: '/api/v1/project-design/submit-sdp-decision/{projectID}/{optionID}',
    tool: 'projectDesignSubmitSdpDecision',
  },
  systemDesignAcknowledgeStaleBasis: {
    method: 'POST',
    path: '/api/v1/system-design/acknowledge-stale-basis/{projectID}',
    tool: 'systemDesignAcknowledgeStaleBasis',
  },
  systemDesignAdvancePhase: {
    method: 'POST',
    path: '/api/v1/system-design/advance-phase/{projectID}',
    tool: 'systemDesignAdvancePhase',
  },
  systemDesignAskQuestions: {
    method: 'POST',
    path: '/api/v1/system-design/ask-questions/{projectID}',
    tool: 'systemDesignAskQuestions',
  },
  systemDesignCreateProject: {
    method: 'POST',
    path: '/api/v1/system-design/create-project',
    tool: 'systemDesignCreateProject',
  },
  systemDesignGetDesignHealth: {
    method: 'GET',
    path: '/api/v1/system-design/get-design-health/{projectID}',
    tool: 'systemDesignGetDesignHealth',
  },
  systemDesignGetProject: {
    method: 'GET',
    path: '/api/v1/system-design/get-project/{projectID}',
    tool: 'systemDesignGetProject',
  },
  systemDesignGetSessionState: {
    method: 'GET',
    path: '/api/v1/system-design/get-session-state/{projectID}',
    tool: 'systemDesignGetSessionState',
  },
  systemDesignListProjects: {
    method: 'GET',
    path: '/api/v1/system-design/list-projects',
    tool: 'systemDesignListProjects',
  },
  systemDesignRequestArtifactDraft: {
    method: 'POST',
    path: '/api/v1/system-design/request-artifact-draft/{projectID}',
    tool: 'systemDesignRequestArtifactDraft',
  },
  systemDesignSetOperatingModel: {
    method: 'POST',
    path: '/api/v1/system-design/set-operating-model/{projectID}',
    tool: 'systemDesignSetOperatingModel',
  },
  systemDesignSetResearchInput: {
    method: 'POST',
    path: '/api/v1/system-design/set-research-input/{projectID}',
    tool: 'systemDesignSetResearchInput',
  },
  systemDesignSetReviewCommentStatus: {
    method: 'POST',
    path: '/api/v1/system-design/set-review-comment-status/{projectID}',
    tool: 'systemDesignSetReviewCommentStatus',
  },
  systemDesignStartSystemDesign: {
    method: 'POST',
    path: '/api/v1/system-design/start-system-design/{projectID}',
    tool: 'systemDesignStartSystemDesign',
  },
  systemDesignSubmitReviewDecision: {
    method: 'POST',
    path: '/api/v1/system-design/submit-review-decision/{projectID}',
    tool: 'systemDesignSubmitReviewDecision',
  },
} as const;

export type OpId = keyof typeof OP_BINDINGS;

/**
 * Structural params for one op call. REST decomposes these into openapi-fetch's
 * `{ params: { path, query }, body }`; MCP flattens path+query+body into one
 * tool-arguments object (MCP tools take a single flat arguments record).
 */
export interface OpParams {
  path?: Record<string, string> | undefined;
  query?: Record<string, unknown> | undefined;
  body?: unknown;
}

export interface OpsClient {
  call<R = unknown>(op: OpId, params?: OpParams): Promise<R>;
}

interface RestResult {
  data?: unknown;
  error?: unknown;
  response: Response;
}

type RestFn = (
  path: string,
  options: {
    params: {
      path?: Record<string, string> | undefined;
      query?: Record<string, unknown> | undefined;
    };
    body?: unknown;
  }
) => Promise<RestResult>;

// openapi-fetch's client is keyed by HTTP verb (client.GET(...), client.POST(...),
// ...). OP_BINDINGS.method picks the right one at runtime; the cast below is the
// one place that trades static path-safety for the generic, table-driven dispatch
// every op needs (the OAS <-> OP_BINDINGS correspondence is guaranteed by
// gen-ops.mjs deriving both from the same source, not by this cast).
type RestMethodMap = Record<'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE', RestFn>;

export function restOpsClient(client: ReturnType<typeof createClient<paths>>): OpsClient {
  return {
    async call<R = unknown>(op: OpId, params: OpParams = {}): Promise<R> {
      const binding = OP_BINDINGS[op];
      const methods = client as unknown as RestMethodMap;
      const fn = methods[binding.method];
      const { data, error, response } = await fn(binding.path, {
        params: { path: params.path, query: params.query },
        body: params.body,
      });
      if (error !== undefined) throw toApiError(response.status, error as WireError);
      return data as R;
    },
  };
}

/** Not-found detection over a failed tool call's content blocks. The server's
 * manager errors serialize as `${Kind.String()}: ${message}` (see
 * server/internal/manager errors), so a NotFound tool error always reads
 * NotFound: no active design session for project "x" — no space between
 * "NotFound" and the colon. Match that exact grammar at the start of a block
 * first; keep a tolerant "not found"/"not_found" fallback (case-insensitive,
 * optional separator) for any other error shape so a wording drift elsewhere
 * doesn't silently fall back to 500. Anything else maps to 500 — MCP tool
 * errors do not carry a structured status code the way REST responses do. */
function isNotFoundToolError(content: unknown): boolean {
  if (!Array.isArray(content)) return false;
  return content.some((block) => {
    if (typeof block !== 'object' || block === null) return false;
    const text = (block as { text?: unknown }).text;
    if (typeof text !== 'string') return false;
    return text.startsWith('NotFound:') || /not[\s_]?found/i.test(text);
  });
}

function toolErrorMessage(content: unknown): string {
  if (!Array.isArray(content)) return 'tool call failed';
  const texts = content
    .map((block) => {
      if (typeof block !== 'object' || block === null) return undefined;
      const text = (block as { text?: unknown }).text;
      return typeof text === 'string' ? text : undefined;
    })
    .filter((text): text is string => text !== undefined);
  return texts.length > 0 ? texts.join(' ') : 'tool call failed';
}

/**
 * MCP flattens path+query+body into one arguments object; unlike REST (where
 * path/query/body are structurally separate), a key present in more than one
 * part would silently be decided by merge order (body over query over path).
 * Guard loudly instead: a collision aborts the call with an ApiError rather
 * than resolving to whichever part happened to merge last.
 */
function assertNoArgCollision(
  opId: string,
  path: Record<string, unknown>,
  query: Record<string, unknown>,
  body: Record<string, unknown>
): void {
  const seen = new Map<string, string[]>();
  for (const [partName, part] of [
    ['path', path],
    ['query', query],
    ['body', body],
  ] as const) {
    for (const key of Object.keys(part)) {
      const parts = seen.get(key) ?? [];
      parts.push(partName);
      seen.set(key, parts);
    }
  }
  const collidingKeys = [...seen.entries()]
    .filter(([, parts]) => parts.length > 1)
    .map(([key]) => key);
  if (collidingKeys.length > 0) {
    throw new ApiError(
      500,
      'argCollision',
      `argument key collision on ${opId}: ${collidingKeys.join(', ')}`
    );
  }
}

export function mcpOpsClient(app: App): OpsClient {
  return {
    async call<R = unknown>(op: OpId, params: OpParams = {}): Promise<R> {
      const binding = OP_BINDINGS[op];
      const pathArgs = (params.path ?? {}) as Record<string, unknown>;
      const queryArgs = params.query ?? {};
      const bodyArgs = (params.body ?? {}) as Record<string, unknown>;
      assertNoArgCollision(op, pathArgs, queryArgs, bodyArgs);
      const args = { ...pathArgs, ...queryArgs, ...bodyArgs };
      const result = await app.callServerTool({ name: binding.tool, arguments: args });
      if (result.isError === true) {
        const status = isNotFoundToolError(result.content) ? 404 : 500;
        const code = status === 404 ? 'not_found' : 'internal';
        throw new ApiError(status, code, toolErrorMessage(result.content));
      }
      // Transport parity (T11 finding F-T11-4): mcpemit wraps every op result in
      // a single-field envelope struct ({ "result": <value> }) for the MCP output
      // schema, while the REST handler returns the bare value. Unwrap so both
      // OpsClient transports hand hooks the identical shape. Void ops have no
      // envelope and fall through to {}.
      const sc = result.structuredContent as Record<string, unknown> | null | undefined;
      if (sc !== null && sc !== undefined && typeof sc === 'object' && 'result' in sc) {
        return sc['result'] as R;
      }
      return (sc ?? {}) as R;
    },
  };
}
