// Code generated by cmd/modelgen from the service-contract interface; DO NOT EDIT.
// Edit project.json's `interface` and re-run `make gen-fakes` instead.

package interventionfake

import (
	fweng "github.com/mixofreality-studio/archistrator-platform/framework-go/engine"
	"github.com/mixofreality-studio/archistrator/server/internal/engine/intervention"
)

// FakeInterventionEngine is a generated test double for intervention.InterventionEngine: set the Fn field(s)
// a test needs; calling a method whose Fn is unset panics.
type FakeInterventionEngine struct {
	ApplyPausePolicyFn          func(rc fweng.Context, ctx intervention.PauseRequestContext) (intervention.PausePlan, error)
	DecideOnHealthFn            func(rc fweng.Context, healthChange intervention.HealthChange) (intervention.HealthDirective, error)
	DecideOnSettlementFailureFn func(rc fweng.Context, failure intervention.SettlementFailure) (intervention.SettlementFailureDirective, error)
	DecideOnVarianceFn          func(rc fweng.Context, variance intervention.ConstructionVariance) (intervention.VarianceDirective, error)
}

func (f *FakeInterventionEngine) ApplyPausePolicy(rc fweng.Context, ctx intervention.PauseRequestContext) (intervention.PausePlan, error) {
	if f.ApplyPausePolicyFn == nil {
		panic("FakeInterventionEngine.ApplyPausePolicyFn not set")
	}
	return f.ApplyPausePolicyFn(rc, ctx)
}

func (f *FakeInterventionEngine) DecideOnHealth(rc fweng.Context, healthChange intervention.HealthChange) (intervention.HealthDirective, error) {
	if f.DecideOnHealthFn == nil {
		panic("FakeInterventionEngine.DecideOnHealthFn not set")
	}
	return f.DecideOnHealthFn(rc, healthChange)
}

func (f *FakeInterventionEngine) DecideOnSettlementFailure(rc fweng.Context, failure intervention.SettlementFailure) (intervention.SettlementFailureDirective, error) {
	if f.DecideOnSettlementFailureFn == nil {
		panic("FakeInterventionEngine.DecideOnSettlementFailureFn not set")
	}
	return f.DecideOnSettlementFailureFn(rc, failure)
}

func (f *FakeInterventionEngine) DecideOnVariance(rc fweng.Context, variance intervention.ConstructionVariance) (intervention.VarianceDirective, error) {
	if f.DecideOnVarianceFn == nil {
		panic("FakeInterventionEngine.DecideOnVarianceFn not set")
	}
	return f.DecideOnVarianceFn(rc, variance)
}

var _ intervention.InterventionEngine = (*FakeInterventionEngine)(nil)
