// Code generated by cmd/clientgen (mcpemit). DO NOT EDIT.
// Source contract:

package systemdesign

import (
	"context"
	"errors"
	"fmt"

	"github.com/google/jsonschema-go/jsonschema"
	"github.com/modelcontextprotocol/go-sdk/mcp"

	fwmanager "github.com/mixofreality-studio/archistrator-platform/framework-go/manager"
	"github.com/mixofreality-studio/archistrator-platform/framework-go/utilities/security"
	mgr "github.com/mixofreality-studio/archistrator/server/internal/manager/systemdesign"
)

// Handler binds the SystemDesignManager manager to MCP tools.
type Handler struct {
	Manager mgr.SystemDesignManager
}

// Register adds every operation as an mcp.Tool on srv, each carrying an
// explicit human description and an explicit input JSON Schema (enum values +
// meanings, REST-matching optionality) so an agentic consumer needs no source.
func (h *Handler) Register(srv *mcp.Server) {
	mcp.AddTool(srv, &mcp.Tool{Name: "systemDesignAdvancePhase", Description: "Advance the project from System Design (phase 1) to Project Design (phase 2). Requires every phase-1 artifact to be committed and reviewed; returns the resulting phase plus any reason the advance was gated.", InputSchema: advancePhaseInputSchema()}, h.handleAdvancePhase)
	mcp.AddTool(srv, &mcp.Tool{Name: "systemDesignCreateProject", Description: "Create a new archistrator project owned by the given owner scope, with the given display name, and return its generated project ID.", InputSchema: createProjectInputSchema()}, h.handleCreateProject)
	mcp.AddTool(srv, &mcp.Tool{Name: "systemDesignGetProject", Description: "Return the project head-state: its ID, current Method phase, name, owner, and high-level progress.", InputSchema: getProjectInputSchema()}, h.handleGetProject)
	mcp.AddTool(srv, &mcp.Tool{Name: "systemDesignGetSessionState", Description: "Return the current draft/review session state for one System-Design artifact (selected by kind): its stage, the latest AI draft, and any review feedback. Read-only.", InputSchema: getSessionStateInputSchema()}, h.handleGetSessionState)
	mcp.AddTool(srv, &mcp.Tool{Name: "systemDesignListProjects", Description: "List every project visible to the given owner scope, most-recently-updated first.", InputSchema: listProjectsInputSchema()}, h.handleListProjects)
	mcp.AddTool(srv, &mcp.Tool{Name: "systemDesignRequestArtifactDraft", Description: "Kick off (or re-run) the AI drafting of one System-Design artifact (selected by kind, e.g. the mission, glossary, or volatilities). Pass feedback to re-draft an existing artifact against review notes. Returns a handle to the asynchronous drafting session.", InputSchema: requestArtifactDraftInputSchema()}, h.handleRequestArtifactDraft)
	mcp.AddTool(srv, &mcp.Tool{Name: "systemDesignSetResearchInput", Description: "Attach or replace the raw research corpus the architect distils the mission, glossary, and volatilities from. Returns the new project state version.", InputSchema: setResearchInputInputSchema()}, h.handleSetResearchInput)
	mcp.AddTool(srv, &mcp.Tool{Name: "systemDesignStartSystemDesign", Description: "Begin the System-Design phase for a project, seeding the artifact spine (mission first). Returns a handle to the kickoff session.", InputSchema: startSystemDesignInputSchema()}, h.handleStartSystemDesign)
	mcp.AddTool(srv, &mcp.Tool{Name: "systemDesignSubmitReviewDecision", Description: "Record a review verdict (approve / reject / withdraw) on the current draft of a System-Design artifact (selected by kind). Reject and withdraw should carry feedback; approve commits the artifact and unblocks its successors.", InputSchema: submitReviewDecisionInputSchema()}, h.handleSubmitReviewDecision)
}

type advancePhaseInput struct {
	ProjectID mgr.ProjectID `json:"projectID"`
}

type advancePhaseOutput struct {
	Result mgr.PhaseAdvanceResult `json:"result"`
}

type createProjectInput struct {
	Owner mgr.OwnerScope `json:"owner"`
	Name  string         `json:"name"`
}

type createProjectOutput struct {
	Result mgr.ProjectID `json:"result"`
}

type getProjectInput struct {
	ProjectID mgr.ProjectID `json:"projectID"`
}

type getProjectOutput struct {
	Result mgr.ProjectState `json:"result"`
}

type getSessionStateInput struct {
	ProjectID mgr.ProjectID    `json:"projectID"`
	Kind      mgr.ArtifactKind `json:"kind"`
}

type getSessionStateOutput struct {
	Result mgr.SessionStateView `json:"result"`
}

type listProjectsInput struct {
	Owner mgr.OwnerScope `json:"owner"`
}

type listProjectsOutput struct {
	Result []mgr.ProjectSummary `json:"result"`
}

type requestArtifactDraftInput struct {
	ProjectID mgr.ProjectID       `json:"projectID"`
	Kind      mgr.ArtifactKind    `json:"kind"`
	Feedback  *mgr.ReviewFeedback `json:"feedback,omitempty"`
}

type requestArtifactDraftOutput struct {
	Result mgr.SessionRef `json:"result"`
}

type setResearchInputInput struct {
	ProjectID mgr.ProjectID     `json:"projectID"`
	Research  mgr.ResearchInput `json:"research"`
}

type setResearchInputOutput struct {
	Result mgr.Version `json:"result"`
}

type startSystemDesignInput struct {
	ProjectID mgr.ProjectID `json:"projectID"`
}

type startSystemDesignOutput struct {
	Result mgr.SessionRef `json:"result"`
}

type submitReviewDecisionInput struct {
	ProjectID mgr.ProjectID       `json:"projectID"`
	Kind      mgr.ArtifactKind    `json:"kind"`
	Decision  mgr.ReviewDecision  `json:"decision"`
	Feedback  *mgr.ReviewFeedback `json:"feedback,omitempty"`
}

type submitReviewDecisionOutput struct{}

// advancePhaseInputSchema is the explicit MCP input schema for the AdvancePhase operation.
func advancePhaseInputSchema() *jsonschema.Schema {
	s := objectSchema[advancePhaseInput]()
	s.Required = []string{"projectID"}
	return s
}

// createProjectInputSchema is the explicit MCP input schema for the CreateProject operation.
func createProjectInputSchema() *jsonschema.Schema {
	s := objectSchema[createProjectInput]()
	s.Required = []string{"owner", "name"}
	return s
}

// getProjectInputSchema is the explicit MCP input schema for the GetProject operation.
func getProjectInputSchema() *jsonschema.Schema {
	s := objectSchema[getProjectInput]()
	s.Required = []string{"projectID"}
	return s
}

// getSessionStateInputSchema is the explicit MCP input schema for the GetSessionState operation.
func getSessionStateInputSchema() *jsonschema.Schema {
	s := objectSchema[getSessionStateInput]()
	s.Required = []string{"projectID", "kind"}
	s.Properties["kind"] = enumSchemaArtifactKind()
	return s
}

// listProjectsInputSchema is the explicit MCP input schema for the ListProjects operation.
func listProjectsInputSchema() *jsonschema.Schema {
	s := objectSchema[listProjectsInput]()
	s.Required = []string{"owner"}
	return s
}

// requestArtifactDraftInputSchema is the explicit MCP input schema for the RequestArtifactDraft operation.
func requestArtifactDraftInputSchema() *jsonschema.Schema {
	s := objectSchema[requestArtifactDraftInput]()
	s.Required = []string{"projectID", "kind"}
	s.Properties["kind"] = enumSchemaArtifactKind()
	return s
}

// setResearchInputInputSchema is the explicit MCP input schema for the SetResearchInput operation.
func setResearchInputInputSchema() *jsonschema.Schema {
	s := objectSchema[setResearchInputInput]()
	s.Required = []string{"projectID", "research"}
	return s
}

// startSystemDesignInputSchema is the explicit MCP input schema for the StartSystemDesign operation.
func startSystemDesignInputSchema() *jsonschema.Schema {
	s := objectSchema[startSystemDesignInput]()
	s.Required = []string{"projectID"}
	return s
}

// submitReviewDecisionInputSchema is the explicit MCP input schema for the SubmitReviewDecision operation.
func submitReviewDecisionInputSchema() *jsonschema.Schema {
	s := objectSchema[submitReviewDecisionInput]()
	s.Required = []string{"projectID", "kind", "decision"}
	s.Properties["kind"] = enumSchemaArtifactKind()
	s.Properties["decision"] = enumSchemaReviewDecision()
	return s
}

// enumSchemaArtifactKind describes the ArtifactKind enum: its allowed values and their meanings.
func enumSchemaArtifactKind() *jsonschema.Schema {
	return &jsonschema.Schema{
		Type:        "integer",
		Enum:        []any{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16},
		Description: "ArtifactKind. Allowed values: 0=KindMission, 1=KindGlossary, 2=KindScrubbedRequirements, 3=KindVolatilities, 4=KindCoreUseCases, 5=KindSystem, 6=KindOperationalConcepts, 7=KindStandardCheck, 8=KindPlanningAssumptions, 9=KindActivityList, 10=KindNetwork, 11=KindNormalSolution, 12=KindSubcriticalSolution, 13=KindCompressedSolution, 14=KindDecompressedSolution, 15=KindRiskModel, 16=KindSdpReview.",
	}
}

// enumSchemaReviewDecision describes the ReviewDecision enum: its allowed values and their meanings.
func enumSchemaReviewDecision() *jsonschema.Schema {
	return &jsonschema.Schema{
		Type:        "integer",
		Enum:        []any{0, 1, 2, 3},
		Description: "ReviewDecision. Allowed values: 0=ReviewDecisionUnknown, 1=ReviewApprove, 2=ReviewReject, 3=ReviewWithdraw.",
	}
}

// handleAdvancePhase is the MCP tool handler for the AdvancePhase operation.
func (h *Handler) handleAdvancePhase(ctx context.Context, _ *mcp.CallToolRequest, in advancePhaseInput) (*mcp.CallToolResult, advancePhaseOutput, error) {
	var out advancePhaseOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.AdvancePhase(rc, in.ProjectID)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleCreateProject is the MCP tool handler for the CreateProject operation.
func (h *Handler) handleCreateProject(ctx context.Context, _ *mcp.CallToolRequest, in createProjectInput) (*mcp.CallToolResult, createProjectOutput, error) {
	var out createProjectOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.CreateProject(rc, in.Owner, in.Name)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleGetProject is the MCP tool handler for the GetProject operation.
func (h *Handler) handleGetProject(ctx context.Context, _ *mcp.CallToolRequest, in getProjectInput) (*mcp.CallToolResult, getProjectOutput, error) {
	var out getProjectOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.GetProject(rc, in.ProjectID)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleGetSessionState is the MCP tool handler for the GetSessionState operation.
func (h *Handler) handleGetSessionState(ctx context.Context, _ *mcp.CallToolRequest, in getSessionStateInput) (*mcp.CallToolResult, getSessionStateOutput, error) {
	var out getSessionStateOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.GetSessionState(rc, in.ProjectID, in.Kind)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleListProjects is the MCP tool handler for the ListProjects operation.
func (h *Handler) handleListProjects(ctx context.Context, _ *mcp.CallToolRequest, in listProjectsInput) (*mcp.CallToolResult, listProjectsOutput, error) {
	var out listProjectsOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.ListProjects(rc, in.Owner)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleRequestArtifactDraft is the MCP tool handler for the RequestArtifactDraft operation.
func (h *Handler) handleRequestArtifactDraft(ctx context.Context, _ *mcp.CallToolRequest, in requestArtifactDraftInput) (*mcp.CallToolResult, requestArtifactDraftOutput, error) {
	var out requestArtifactDraftOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.RequestArtifactDraft(rc, in.ProjectID, in.Kind, in.Feedback)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleSetResearchInput is the MCP tool handler for the SetResearchInput operation.
func (h *Handler) handleSetResearchInput(ctx context.Context, _ *mcp.CallToolRequest, in setResearchInputInput) (*mcp.CallToolResult, setResearchInputOutput, error) {
	var out setResearchInputOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.SetResearchInput(rc, in.ProjectID, in.Research)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleStartSystemDesign is the MCP tool handler for the StartSystemDesign operation.
func (h *Handler) handleStartSystemDesign(ctx context.Context, _ *mcp.CallToolRequest, in startSystemDesignInput) (*mcp.CallToolResult, startSystemDesignOutput, error) {
	var out startSystemDesignOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.StartSystemDesign(rc, in.ProjectID)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleSubmitReviewDecision is the MCP tool handler for the SubmitReviewDecision operation.
func (h *Handler) handleSubmitReviewDecision(ctx context.Context, _ *mcp.CallToolRequest, in submitReviewDecisionInput) (*mcp.CallToolResult, submitReviewDecisionOutput, error) {
	var out submitReviewDecisionOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	if err := h.Manager.SubmitReviewDecision(rc, in.ProjectID, in.Kind, in.Decision, in.Feedback); err != nil {
		return nil, out, mapManagerError(err)
	}
	return nil, out, nil
}

// --- helpers ---------------------------------------------------------------

// objectSchema infers the base object JSON Schema for a tool input struct via
// the SDK's reflection (the same inference the SDK would run for a nil input
// schema), so nested object/array params keep their structural shape; callers
// then override the required list and any enum properties. It panics on an
// un-inferrable type — a build-time contract error surfaced at server start.
func objectSchema[T any]() *jsonschema.Schema {
	s, err := jsonschema.For[T](nil)
	if err != nil {
		panic(fmt.Sprintf("mcp input schema inference: %v", err))
	}
	if s.Properties == nil {
		s.Properties = map[string]*jsonschema.Schema{}
	}
	return s
}

func mapManagerError(err error) error {
	var me *fwmanager.Error
	if errors.As(err, &me) {
		return fmt.Errorf("%s: %s", me.Kind.String(), me.Detail)
	}
	return err
}
