// Code generated by cmd/clientgen (mcpemit). DO NOT EDIT.
// Source contract:

package systemdesign

import (
	"context"
	"errors"
	"fmt"

	"github.com/google/jsonschema-go/jsonschema"
	"github.com/modelcontextprotocol/go-sdk/mcp"

	fwmanager "github.com/mixofreality-studio/archistrator-platform/framework-go/manager"
	"github.com/mixofreality-studio/archistrator-platform/framework-go/utilities/security"
	mgr "github.com/mixofreality-studio/archistrator/server/internal/manager/systemdesign"
)

// Handler binds the SystemDesignManager manager to MCP tools.
type Handler struct {
	Manager mgr.SystemDesignManager
}

// Register adds every operation as an mcp.Tool on srv, each carrying an
// explicit human description and an explicit input JSON Schema (enum values +
// meanings, REST-matching optionality) so an agentic consumer needs no source.
func (h *Handler) Register(srv *mcp.Server) {
	mcp.AddTool(srv, &mcp.Tool{Name: "systemDesignAdvancePhase", Description: "Advance the project from System Design (phase 1) to Project Design (phase 2). Requires every phase-1 artifact to be committed and reviewed; returns the resulting phase plus any reason the advance was gated.", InputSchema: advancePhaseInputSchema(), OutputSchema: advancePhaseOutputSchema()}, h.handleAdvancePhase)
	mcp.AddTool(srv, &mcp.Tool{Name: "systemDesignCreateProject", Description: "Create a new archistrator project owned by the given owner scope, with the given display name, and return its generated project ID.", InputSchema: createProjectInputSchema(), OutputSchema: createProjectOutputSchema()}, h.handleCreateProject)
	mcp.AddTool(srv, &mcp.Tool{Name: "systemDesignGetProject", Description: "Return the project head-state: its ID, current Method phase, name, owner, and high-level progress.", InputSchema: getProjectInputSchema(), OutputSchema: getProjectOutputSchema()}, h.handleGetProject)
	mcp.AddTool(srv, &mcp.Tool{Name: "systemDesignGetSessionState", Description: "Return the current draft/review session state for one System-Design artifact (selected by kind): its stage, the latest AI draft, and any review feedback. Read-only.", InputSchema: getSessionStateInputSchema(), OutputSchema: getSessionStateOutputSchema()}, h.handleGetSessionState)
	mcp.AddTool(srv, &mcp.Tool{Name: "systemDesignListProjects", Description: "List every project visible to the given owner scope, most-recently-updated first.", InputSchema: listProjectsInputSchema(), OutputSchema: listProjectsOutputSchema()}, h.handleListProjects)
	mcp.AddTool(srv, &mcp.Tool{Name: "systemDesignRequestArtifactDraft", Description: "Kick off (or re-run) the AI drafting of one System-Design artifact (selected by kind, e.g. the mission, glossary, or volatilities). Pass feedback to re-draft an existing artifact against review notes. Returns a handle to the asynchronous drafting session.", InputSchema: requestArtifactDraftInputSchema(), OutputSchema: requestArtifactDraftOutputSchema()}, h.handleRequestArtifactDraft)
	mcp.AddTool(srv, &mcp.Tool{Name: "systemDesignSetOperatingModel", Description: "Set the project's operating model — selfOperated (the customer runs the built app in their own infrastructure; the default) or archistratorOperated (archistrator operates the app on the platform, which constrains the deployment design to the platform palette: CNPG Postgres, Temporal, Keycloak, the otel stack, deployed to the platform Kubernetes cluster). Choose at creation, before starting System Design. Returns the new project state version.", InputSchema: setOperatingModelInputSchema(), OutputSchema: setOperatingModelOutputSchema()}, h.handleSetOperatingModel)
	mcp.AddTool(srv, &mcp.Tool{Name: "systemDesignSetResearchInput", Description: "Attach or replace the raw research corpus the architect distils the mission, glossary, and volatilities from. Returns the new project state version.", InputSchema: setResearchInputInputSchema(), OutputSchema: setResearchInputOutputSchema()}, h.handleSetResearchInput)
	mcp.AddTool(srv, &mcp.Tool{Name: "systemDesignAskQuestions", Description: "Ask one or more clarifying QUESTIONS about a System-Design artifact (selected by kind) addressed to a role (pm or architect), WITHOUT sending the draft back for a redraft. The questions are appended to the artifact's review ledger as question-type entries and a lightweight answer job is dispatched so the addressed role answers each in place. Works on a committed artifact too (seeds a question-only thread without opening an amendment). Unlike change-request comments, open questions do NOT block approve.", InputSchema: askQuestionsInputSchema(), OutputSchema: askQuestionsOutputSchema()}, h.handleAskQuestions)
	mcp.AddTool(srv, &mcp.Tool{Name: "systemDesignSetReviewCommentStatus", Description: "Change the status of one durable review-ledger comment on a System-Design artifact (selected by kind): waive an open comment to dismiss it, or reopen an addressed comment to send it back. Approve is blocked while any comment is still open.", InputSchema: setReviewCommentStatusInputSchema(), OutputSchema: setReviewCommentStatusOutputSchema()}, h.handleSetReviewCommentStatus)
	mcp.AddTool(srv, &mcp.Tool{Name: "systemDesignStartSystemDesign", Description: "Begin the System-Design phase for a project, seeding the artifact spine (mission first). Returns a handle to the kickoff session.", InputSchema: startSystemDesignInputSchema(), OutputSchema: startSystemDesignOutputSchema()}, h.handleStartSystemDesign)
	mcp.AddTool(srv, &mcp.Tool{Name: "systemDesignSubmitReviewDecision", Description: "Record a review verdict (approve / reject / withdraw) on the current draft of a System-Design artifact (selected by kind). Reject and withdraw should carry feedback; approve commits the artifact and unblocks its successors.", InputSchema: submitReviewDecisionInputSchema(), OutputSchema: submitReviewDecisionOutputSchema()}, h.handleSubmitReviewDecision)
}

type advancePhaseInput struct {
	ProjectID        mgr.ProjectID `json:"projectID"`
	AcknowledgeStale bool          `json:"acknowledgeStale"`
}

type advancePhaseOutput struct {
	Result mgr.PhaseAdvanceResult `json:"result"`
}

type createProjectInput struct {
	Owner mgr.OwnerScope `json:"owner"`
	Name  string         `json:"name"`
}

type createProjectOutput struct {
	Result mgr.ProjectID `json:"result"`
}

type getProjectInput struct {
	ProjectID mgr.ProjectID `json:"projectID"`
}

type getProjectOutput struct {
	Result mgr.ProjectState `json:"result"`
}

type getSessionStateInput struct {
	ProjectID mgr.ProjectID    `json:"projectID"`
	Kind      mgr.ArtifactKind `json:"kind"`
}

type getSessionStateOutput struct {
	Result mgr.SessionStateView `json:"result"`
}

type listProjectsInput struct {
	Owner mgr.OwnerScope `json:"owner"`
}

type listProjectsOutput struct {
	Result []mgr.ProjectSummary `json:"result"`
}

type requestArtifactDraftInput struct {
	ProjectID mgr.ProjectID       `json:"projectID"`
	Kind      mgr.ArtifactKind    `json:"kind"`
	Feedback  *mgr.ReviewFeedback `json:"feedback,omitempty"`
}

type requestArtifactDraftOutput struct {
	Result mgr.SessionRef `json:"result"`
}

type setOperatingModelInput struct {
	ProjectID mgr.ProjectID      `json:"projectID"`
	Model     mgr.OperatingModel `json:"model"`
}

type setOperatingModelOutput struct {
	Result mgr.Version `json:"result"`
}

type setResearchInputInput struct {
	ProjectID mgr.ProjectID     `json:"projectID"`
	Research  mgr.ResearchInput `json:"research"`
}

type setResearchInputOutput struct {
	Result mgr.Version `json:"result"`
}

type askQuestionsInput struct {
	ProjectID mgr.ProjectID         `json:"projectID"`
	Kind      mgr.ArtifactKind      `json:"kind"`
	Addressee string                `json:"addressee"`
	Questions []mgr.AnchoredComment `json:"questions"`
}

type askQuestionsOutput struct{}

type setReviewCommentStatusInput struct {
	ProjectID mgr.ProjectID    `json:"projectID"`
	Kind      mgr.ArtifactKind `json:"kind"`
	CommentID string           `json:"commentID"`
	Status    string           `json:"status"`
}

type setReviewCommentStatusOutput struct{}

type startSystemDesignInput struct {
	ProjectID mgr.ProjectID `json:"projectID"`
}

type startSystemDesignOutput struct {
	Result mgr.SessionRef `json:"result"`
}

type submitReviewDecisionInput struct {
	ProjectID mgr.ProjectID       `json:"projectID"`
	Kind      mgr.ArtifactKind    `json:"kind"`
	Decision  mgr.ReviewDecision  `json:"decision"`
	Feedback  *mgr.ReviewFeedback `json:"feedback,omitempty"`
}

type submitReviewDecisionOutput struct{}

// advancePhaseInputSchema is the explicit MCP input schema for the AdvancePhase operation.
func advancePhaseInputSchema() *jsonschema.Schema {
	s := objectSchema[advancePhaseInput]()
	relaxRawJSON(s)
	s.Required = []string{"projectID", "acknowledgeStale"}
	return s
}

// createProjectInputSchema is the explicit MCP input schema for the CreateProject operation.
func createProjectInputSchema() *jsonschema.Schema {
	s := objectSchema[createProjectInput]()
	relaxRawJSON(s)
	s.Required = []string{"owner", "name"}
	return s
}

// getProjectInputSchema is the explicit MCP input schema for the GetProject operation.
func getProjectInputSchema() *jsonschema.Schema {
	s := objectSchema[getProjectInput]()
	relaxRawJSON(s)
	s.Required = []string{"projectID"}
	return s
}

// getSessionStateInputSchema is the explicit MCP input schema for the GetSessionState operation.
func getSessionStateInputSchema() *jsonschema.Schema {
	s := objectSchema[getSessionStateInput]()
	relaxRawJSON(s)
	s.Required = []string{"projectID", "kind"}
	s.Properties["kind"] = enumSchemaArtifactKind()
	return s
}

// listProjectsInputSchema is the explicit MCP input schema for the ListProjects operation.
func listProjectsInputSchema() *jsonschema.Schema {
	s := objectSchema[listProjectsInput]()
	relaxRawJSON(s)
	s.Required = []string{"owner"}
	return s
}

// requestArtifactDraftInputSchema is the explicit MCP input schema for the RequestArtifactDraft operation.
func requestArtifactDraftInputSchema() *jsonschema.Schema {
	s := objectSchema[requestArtifactDraftInput]()
	relaxRawJSON(s)
	s.Required = []string{"projectID", "kind"}
	s.Properties["kind"] = enumSchemaArtifactKind()
	return s
}

// setOperatingModelInputSchema is the explicit MCP input schema for the SetOperatingModel operation.
func setOperatingModelInputSchema() *jsonschema.Schema {
	s := objectSchema[setOperatingModelInput]()
	relaxRawJSON(s)
	s.Required = []string{"projectID", "model"}
	return s
}

// setResearchInputInputSchema is the explicit MCP input schema for the SetResearchInput operation.
func setResearchInputInputSchema() *jsonschema.Schema {
	s := objectSchema[setResearchInputInput]()
	relaxRawJSON(s)
	s.Required = []string{"projectID", "research"}
	return s
}

// askQuestionsInputSchema is the explicit MCP input schema for the AskQuestions operation.
func askQuestionsInputSchema() *jsonschema.Schema {
	s := objectSchema[askQuestionsInput]()
	relaxRawJSON(s)
	s.Required = []string{"projectID", "kind", "addressee", "questions"}
	s.Properties["kind"] = enumSchemaArtifactKind()
	return s
}

// setReviewCommentStatusInputSchema is the explicit MCP input schema for the SetReviewCommentStatus operation.
func setReviewCommentStatusInputSchema() *jsonschema.Schema {
	s := objectSchema[setReviewCommentStatusInput]()
	relaxRawJSON(s)
	s.Required = []string{"projectID", "kind", "commentID", "status"}
	s.Properties["kind"] = enumSchemaArtifactKind()
	return s
}

// startSystemDesignInputSchema is the explicit MCP input schema for the StartSystemDesign operation.
func startSystemDesignInputSchema() *jsonschema.Schema {
	s := objectSchema[startSystemDesignInput]()
	relaxRawJSON(s)
	s.Required = []string{"projectID"}
	return s
}

// submitReviewDecisionInputSchema is the explicit MCP input schema for the SubmitReviewDecision operation.
func submitReviewDecisionInputSchema() *jsonschema.Schema {
	s := objectSchema[submitReviewDecisionInput]()
	relaxRawJSON(s)
	s.Required = []string{"projectID", "kind", "decision"}
	s.Properties["kind"] = enumSchemaArtifactKind()
	s.Properties["decision"] = enumSchemaReviewDecision()
	return s
}

// advancePhaseOutputSchema is the explicit MCP output schema for the AdvancePhase operation.
func advancePhaseOutputSchema() *jsonschema.Schema {
	s := objectSchema[advancePhaseOutput]()
	relaxRawJSON(s)
	return s
}

// createProjectOutputSchema is the explicit MCP output schema for the CreateProject operation.
func createProjectOutputSchema() *jsonschema.Schema {
	s := objectSchema[createProjectOutput]()
	relaxRawJSON(s)
	return s
}

// getProjectOutputSchema is the explicit MCP output schema for the GetProject operation.
func getProjectOutputSchema() *jsonschema.Schema {
	s := objectSchema[getProjectOutput]()
	relaxRawJSON(s)
	return s
}

// getSessionStateOutputSchema is the explicit MCP output schema for the GetSessionState operation.
func getSessionStateOutputSchema() *jsonschema.Schema {
	s := objectSchema[getSessionStateOutput]()
	relaxRawJSON(s)
	return s
}

// listProjectsOutputSchema is the explicit MCP output schema for the ListProjects operation.
func listProjectsOutputSchema() *jsonschema.Schema {
	s := objectSchema[listProjectsOutput]()
	relaxRawJSON(s)
	return s
}

// requestArtifactDraftOutputSchema is the explicit MCP output schema for the RequestArtifactDraft operation.
func requestArtifactDraftOutputSchema() *jsonschema.Schema {
	s := objectSchema[requestArtifactDraftOutput]()
	relaxRawJSON(s)
	return s
}

// setOperatingModelOutputSchema is the explicit MCP output schema for the SetOperatingModel operation.
func setOperatingModelOutputSchema() *jsonschema.Schema {
	s := objectSchema[setOperatingModelOutput]()
	relaxRawJSON(s)
	return s
}

// setResearchInputOutputSchema is the explicit MCP output schema for the SetResearchInput operation.
func setResearchInputOutputSchema() *jsonschema.Schema {
	s := objectSchema[setResearchInputOutput]()
	relaxRawJSON(s)
	return s
}

// askQuestionsOutputSchema is the explicit MCP output schema for the AskQuestions operation.
func askQuestionsOutputSchema() *jsonschema.Schema {
	s := objectSchema[askQuestionsOutput]()
	relaxRawJSON(s)
	return s
}

// setReviewCommentStatusOutputSchema is the explicit MCP output schema for the SetReviewCommentStatus operation.
func setReviewCommentStatusOutputSchema() *jsonschema.Schema {
	s := objectSchema[setReviewCommentStatusOutput]()
	relaxRawJSON(s)
	return s
}

// startSystemDesignOutputSchema is the explicit MCP output schema for the StartSystemDesign operation.
func startSystemDesignOutputSchema() *jsonschema.Schema {
	s := objectSchema[startSystemDesignOutput]()
	relaxRawJSON(s)
	return s
}

// submitReviewDecisionOutputSchema is the explicit MCP output schema for the SubmitReviewDecision operation.
func submitReviewDecisionOutputSchema() *jsonschema.Schema {
	s := objectSchema[submitReviewDecisionOutput]()
	relaxRawJSON(s)
	return s
}

// enumSchemaArtifactKind describes the ArtifactKind enum: its allowed values and their meanings.
func enumSchemaArtifactKind() *jsonschema.Schema {
	return &jsonschema.Schema{
		Type:        "integer",
		Enum:        []any{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16},
		Description: "ArtifactKind. Allowed values: 0=KindMission, 1=KindGlossary, 2=KindScrubbedRequirements, 3=KindVolatilities, 4=KindCoreUseCases, 5=KindSystem, 6=KindOperationalConcepts, 7=KindStandardCheck, 8=KindPlanningAssumptions, 9=KindActivityList, 10=KindNetwork, 11=KindNormalSolution, 12=KindSubcriticalSolution, 13=KindCompressedSolution, 14=KindDecompressedSolution, 15=KindRiskModel, 16=KindSdpReview.",
	}
}

// enumSchemaReviewDecision describes the ReviewDecision enum: its allowed values and their meanings.
func enumSchemaReviewDecision() *jsonschema.Schema {
	return &jsonschema.Schema{
		Type:        "integer",
		Enum:        []any{0, 1, 2, 3},
		Description: "ReviewDecision. Allowed values: 0=ReviewDecisionUnknown, 1=ReviewApprove, 2=ReviewReject, 3=ReviewWithdraw.",
	}
}

// handleAdvancePhase is the MCP tool handler for the AdvancePhase operation.
func (h *Handler) handleAdvancePhase(ctx context.Context, _ *mcp.CallToolRequest, in advancePhaseInput) (*mcp.CallToolResult, advancePhaseOutput, error) {
	var out advancePhaseOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.AdvancePhase(rc, in.ProjectID, in.AcknowledgeStale)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleCreateProject is the MCP tool handler for the CreateProject operation.
func (h *Handler) handleCreateProject(ctx context.Context, _ *mcp.CallToolRequest, in createProjectInput) (*mcp.CallToolResult, createProjectOutput, error) {
	var out createProjectOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.CreateProject(rc, in.Owner, in.Name)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleGetProject is the MCP tool handler for the GetProject operation.
func (h *Handler) handleGetProject(ctx context.Context, _ *mcp.CallToolRequest, in getProjectInput) (*mcp.CallToolResult, getProjectOutput, error) {
	var out getProjectOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.GetProject(rc, in.ProjectID)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleGetSessionState is the MCP tool handler for the GetSessionState operation.
func (h *Handler) handleGetSessionState(ctx context.Context, _ *mcp.CallToolRequest, in getSessionStateInput) (*mcp.CallToolResult, getSessionStateOutput, error) {
	var out getSessionStateOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.GetSessionState(rc, in.ProjectID, in.Kind)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleListProjects is the MCP tool handler for the ListProjects operation.
func (h *Handler) handleListProjects(ctx context.Context, _ *mcp.CallToolRequest, in listProjectsInput) (*mcp.CallToolResult, listProjectsOutput, error) {
	var out listProjectsOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.ListProjects(rc, in.Owner)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleRequestArtifactDraft is the MCP tool handler for the RequestArtifactDraft operation.
func (h *Handler) handleRequestArtifactDraft(ctx context.Context, _ *mcp.CallToolRequest, in requestArtifactDraftInput) (*mcp.CallToolResult, requestArtifactDraftOutput, error) {
	var out requestArtifactDraftOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.RequestArtifactDraft(rc, in.ProjectID, in.Kind, in.Feedback)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleSetOperatingModel is the MCP tool handler for the SetOperatingModel operation.
func (h *Handler) handleSetOperatingModel(ctx context.Context, _ *mcp.CallToolRequest, in setOperatingModelInput) (*mcp.CallToolResult, setOperatingModelOutput, error) {
	var out setOperatingModelOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.SetOperatingModel(rc, in.ProjectID, in.Model)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleSetResearchInput is the MCP tool handler for the SetResearchInput operation.
func (h *Handler) handleSetResearchInput(ctx context.Context, _ *mcp.CallToolRequest, in setResearchInputInput) (*mcp.CallToolResult, setResearchInputOutput, error) {
	var out setResearchInputOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.SetResearchInput(rc, in.ProjectID, in.Research)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleAskQuestions is the MCP tool handler for the AskQuestions operation.
func (h *Handler) handleAskQuestions(ctx context.Context, _ *mcp.CallToolRequest, in askQuestionsInput) (*mcp.CallToolResult, askQuestionsOutput, error) {
	var out askQuestionsOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	if err := h.Manager.AskQuestions(rc, in.ProjectID, in.Kind, in.Addressee, in.Questions); err != nil {
		return nil, out, mapManagerError(err)
	}
	return nil, out, nil
}

// handleSetReviewCommentStatus is the MCP tool handler for the SetReviewCommentStatus operation.
func (h *Handler) handleSetReviewCommentStatus(ctx context.Context, _ *mcp.CallToolRequest, in setReviewCommentStatusInput) (*mcp.CallToolResult, setReviewCommentStatusOutput, error) {
	var out setReviewCommentStatusOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	if err := h.Manager.SetReviewCommentStatus(rc, in.ProjectID, in.Kind, in.CommentID, in.Status); err != nil {
		return nil, out, mapManagerError(err)
	}
	return nil, out, nil
}

// handleStartSystemDesign is the MCP tool handler for the StartSystemDesign operation.
func (h *Handler) handleStartSystemDesign(ctx context.Context, _ *mcp.CallToolRequest, in startSystemDesignInput) (*mcp.CallToolResult, startSystemDesignOutput, error) {
	var out startSystemDesignOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.StartSystemDesign(rc, in.ProjectID)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleSubmitReviewDecision is the MCP tool handler for the SubmitReviewDecision operation.
func (h *Handler) handleSubmitReviewDecision(ctx context.Context, _ *mcp.CallToolRequest, in submitReviewDecisionInput) (*mcp.CallToolResult, submitReviewDecisionOutput, error) {
	var out submitReviewDecisionOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	if err := h.Manager.SubmitReviewDecision(rc, in.ProjectID, in.Kind, in.Decision, in.Feedback); err != nil {
		return nil, out, mapManagerError(err)
	}
	return nil, out, nil
}

// --- helpers ---------------------------------------------------------------

// objectSchema infers the base object JSON Schema for a tool input struct via
// the SDK's reflection (the same inference the SDK would run for a nil input
// schema), so nested object/array params keep their structural shape; callers
// then override the required list and any enum properties. It panics on an
// un-inferrable type — a build-time contract error surfaced at server start.
func objectSchema[T any]() *jsonschema.Schema {
	s, err := jsonschema.For[T](nil)
	if err != nil {
		panic(fmt.Sprintf("mcp input schema inference: %v", err))
	}
	if s.Properties == nil {
		s.Properties = map[string]*jsonschema.Schema{}
	}
	return s
}

// relaxRawJSON walks an inferred schema and relaxes every json.RawMessage /
// []byte JSON-carrier property to a permissive (accept-anything) schema. The SDK
// infers such a Go field as an array of 0-255 bytes, which rejects the real JSON
// object/string the manager actually emits or accepts (QA finding F26); the rest
// of the inferred shape is preserved.
func relaxRawJSON(s *jsonschema.Schema) {
	if s == nil {
		return
	}
	if isRawByteArray(s) {
		*s = jsonschema.Schema{}
		return
	}
	for _, p := range s.Properties {
		relaxRawJSON(p)
	}
	relaxRawJSON(s.Items)
	relaxRawJSON(s.AdditionalProperties)
	for _, p := range s.PrefixItems {
		relaxRawJSON(p)
	}
}

// isRawByteArray reports whether a schema is the jsonschema-go signature of a Go
// []byte / json.RawMessage: an array (possibly nullable) whose items are bytes
// (integer, 0..255).
func isRawByteArray(s *jsonschema.Schema) bool {
	isArray := s.Type == "array"
	for _, t := range s.Types {
		if t == "array" {
			isArray = true
		}
	}
	if !isArray || s.Items == nil {
		return false
	}
	it := s.Items
	if it.Type != "integer" {
		return false
	}
	return it.Minimum != nil && *it.Minimum == 0 && it.Maximum != nil && *it.Maximum == 255
}

func mapManagerError(err error) error {
	var me *fwmanager.Error
	if errors.As(err, &me) {
		return fmt.Errorf("%s: %s", me.Kind.String(), me.Detail)
	}
	return err
}
