// cmd/modelgen generates each component's Go model structs + service-contract
// interface from project.json — step 2 of the contract pipeline. The
// `.serviceContracts` map in `.aiarch/state/project.json` is now the OWNER of the
// contracts: each built entry carries a contract document (`title`, `$defs`,
// `interface`) plus self-describing metadata (`component`, `layer`, `goPackage`).
// modelgen turns that document → Go, so project.json is the single source of
// truth and the Go model (`contract.gen.go`) is a generated output. (The former
// per-component `contract.schema.json` seed files have been retired — their
// content now lives in project.json; cmd/schemagen is a deprecated re-seed tool.)
//
// All-Go: the emitter is built directly on github.com/google/jsonschema-go — the
// SAME complete draft 2020-12 implementation used for reflection (bundled
// meta-schemas, $ref/$dynamicRef resolution). No quicktype, no Node, no external
// codegen tool whose bugs we'd inherit. We own the emitter so support is
// exhaustive and failures are explicit, never silent.
//
// For each `.serviceContracts` entry with a non-empty `goPackage` it writes
// `<goPackage>/contract.gen.go` (e.g. internal/resourceaccess/artifact/
// contract.gen.go), in a package named after the goPackage's last segment.
// Unbuilt stub entries (no `goPackage`) are skipped.
//
// Usage:
//
//	cd server && make gen-models                       # all built contracts
//	cd server && go run ./cmd/modelgen ../.aiarch/state/project.json
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/google/jsonschema-go/jsonschema"

	"github.com/mixofreality-studio/archistrator/server/cmd/internal/codegen"
)

// schemaFile names the legacy per-component seed; retained only so the generated
// file's "Code generated by … from <schemaFile>" header byte-matches the prior
// output (the contracts now live in project.json — see the package doc).
const schemaFile = "contract.schema.json"

// projectFile is the default path (relative to the server module root, where the
// gen targets run) to the head-state document that now owns the contracts.
const projectFile = "../.aiarch/state/project.json"

func main() {
	path := projectFile
	if len(os.Args) > 1 {
		path = os.Args[1]
	}
	raw, err := os.ReadFile(path)
	if err != nil {
		fatal("read %s: %v", path, err)
	}
	// Pull each contract entry out of project.json as RAW JSON so $defs property
	// order and interface param order survive untouched (the basis of the
	// byte-identical regen) — exactly as the old per-component file did.
	var top map[string]json.RawMessage
	if err := json.Unmarshal(raw, &top); err != nil {
		fatal("parse %s: %v", path, err)
	}
	var contracts map[string]json.RawMessage
	if err := json.Unmarshal(top["serviceContracts"], &contracts); err != nil {
		fatal("parse .serviceContracts in %s: %v", path, err)
	}
	keys := make([]string, 0, len(contracts))
	for k := range contracts {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	wrote := 0
	for _, k := range keys {
		entry := contracts[k]
		// goPackage selects built entries (stubs have none) AND gives the output
		// dir + package name. Empty ⇒ skip.
		var meta struct {
			GoPackage string `json:"goPackage"`
		}
		if err := json.Unmarshal(entry, &meta); err != nil {
			fatal("parse contract %q: %v", k, err)
		}
		if meta.GoPackage == "" {
			continue
		}
		if err := genOne(entry, meta.GoPackage); err != nil {
			fatal("modelgen %s: %v", k, err)
		}
		wrote++
	}
	if wrote == 0 {
		fatal("no built service contracts (with goPackage) found in %s", path)
	}
}

// genOne emits one component's contract.gen.go from its project.json contract
// entry (raw JSON) into <goPackage>/contract.gen.go. The entry is a superset of
// the old contract.schema.json (it adds component/layer/goPackage/title around the
// same `$defs` + `interface`), so it feeds the UNCHANGED emission path directly:
// the extra metadata keys land in Schema.Extra and are ignored, while $defs and
// interface are read exactly as before — keeping the output byte-identical.
func genOne(raw []byte, goPackage string) error {
	dir := goPackage
	pkg := filepath.Base(goPackage)

	var doc jsonschema.Schema
	if err := json.Unmarshal(raw, &doc); err != nil {
		return fmt.Errorf("parse schema: %w", err)
	}
	// A schema must carry SOMETHING to generate: either model `$defs` OR (in the
	// interface-only mode used by projectstate) just the `interface` descriptor. A
	// truly empty document is an error.
	_, hasIface := doc.Extra["interface"]
	if len(doc.Defs) == 0 && !hasIface {
		return fmt.Errorf("schema has no $defs and no interface")
	}

	// Property order is lost when $defs is unmarshaled into a Go map, so recover it
	// from the raw JSON for clean, stable, diff-friendly output.
	order := propOrder(raw)

	// Emit the type/interface body first so x-go-type bindings can register their
	// imports (collected in pendingImports) before the import block is written.
	pendingImports = map[string]string{}
	var buf bytes.Buffer

	names := make([]string, 0, len(doc.Defs))
	for n := range doc.Defs {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, n := range names {
		if st, ok := sumTypeOf(doc.Defs[n]); ok {
			// A sum `$def` is not a data struct: emit the sealed interface, the
			// per-variant marker + discriminator methods, and the envelope codec.
			// Its variant structs are emitted as ordinary `$def`s in this same loop.
			emitSumType(&buf, st)
			buf.WriteByte('\n')
			continue
		}
		if err := emitType(&buf, n, doc.Defs[n], order[n]); err != nil {
			return fmt.Errorf("emit %s: %w", n, err)
		}
		buf.WriteByte('\n')
	}

	// Interface (the RPC surface) lives under the document's `interface` key,
	// carried via jsonschema-go's Extra map. Re-decode it into the typed
	// descriptor and emit the Go interface.
	if ix, ok := doc.Extra["interface"]; ok {
		ib, err := json.Marshal(ix)
		if err != nil {
			return fmt.Errorf("re-marshal interface: %w", err)
		}
		var iface codegen.Interface
		if err := json.Unmarshal(ib, &iface); err != nil {
			return fmt.Errorf("decode interface: %w", err)
		}
		emitInterface(&buf, iface)
	}

	// Assemble: header + package + (imports collected during body emission) + body.
	var out2 bytes.Buffer
	fmt.Fprintf(&out2, "// Code generated by cmd/modelgen from %s; DO NOT EDIT.\n", schemaFile)
	fmt.Fprintf(&out2, "// Edit the schema and re-run `make gen-models` instead.\n\n")
	fmt.Fprintf(&out2, "package %s\n\n", pkg)
	if len(pendingImports) > 0 {
		imps := make([]string, 0, len(pendingImports))
		for p := range pendingImports {
			imps = append(imps, p)
		}
		sort.Strings(imps)
		out2.WriteString("import (\n")
		for _, p := range imps {
			if a := pendingImports[p]; a != "" {
				fmt.Fprintf(&out2, "\t%s %q\n", a, p)
			} else {
				fmt.Fprintf(&out2, "\t%q\n", p)
			}
		}
		out2.WriteString(")\n\n")
	}
	out2.Write(buf.Bytes())

	src, err := format.Source(out2.Bytes())
	if err != nil {
		return fmt.Errorf("gofmt generated source: %w\n%s", err, out2.String())
	}
	out := filepath.Join(dir, "contract.gen.go")
	if err := os.WriteFile(out, src, 0o644); err != nil {
		return err
	}
	fmt.Fprintf(os.Stderr, "wrote %s (%d models)\n", out, len(names))
	return nil
}

// layerContext maps a Method layer to the per-layer call Context the generator
// prepends to every interface method (aliased import + Go type).
var layerContext = map[string]struct{ alias, path, typ string }{
	"engine":         {"fweng", "github.com/mixofreality-studio/archistrator-platform/framework-go/engine", "fweng.Context"},
	"resourceaccess": {"fwra", "github.com/mixofreality-studio/archistrator-platform/framework-go/resourceaccess", "fwra.Context"},
	"manager":        {"fwm", "github.com/mixofreality-studio/archistrator-platform/framework-go/manager", "fwm.Context"},
	"client":         {"fwc", "github.com/mixofreality-studio/archistrator-platform/framework-go/client", "fwc.Context"},
}

// emitInterface writes the component's service-contract interface and its ops.
// Every method takes the layer's call Context (`rc`) as its first parameter.
func emitInterface(buf *bytes.Buffer, iface codegen.Interface) {
	if iface.Name == "" {
		return
	}
	lc, hasLayer := layerContext[iface.Layer]
	fmt.Fprintf(buf, "// %s is the generated service-contract interface for this component.\n", iface.Name)
	fmt.Fprintf(buf, "type %s interface {\n", iface.Name)
	for _, op := range iface.Operations {
		params := make([]string, 0, len(op.Params)+1)
		if hasLayer {
			params = append(params, "rc "+lc.typ)
			pendingImports[lc.path] = lc.alias
		}
		for _, p := range op.Params {
			t := goType(p.Schema)
			if p.Pointer {
				t = "*" + t
			}
			params = append(params, p.Name+" "+t)
		}
		fmt.Fprintf(buf, "\t%s(%s)%s\n", op.Name, strings.Join(params, ", "), returnClause(op))
	}
	buf.WriteString("}\n\n")
}

// returnClause renders an operation's return signature.
func returnClause(op codegen.Operation) string {
	switch {
	case op.Result != nil && op.Error:
		return " (" + goType(op.Result) + ", error)"
	case op.Result != nil:
		return " " + goType(op.Result)
	case op.Error:
		return " error"
	default:
		return ""
	}
}

// emitType writes one named type. Enum schemas become a named scalar + a const
// block; object schemas become structs; everything else becomes a named alias.
func emitType(buf *bytes.Buffer, name string, s *jsonschema.Schema, order []string) error {
	if len(s.Enum) > 0 && effectiveType(s) != "object" {
		emitEnum(buf, name, s)
		return nil
	}
	if effectiveType(s) != "object" || len(s.Properties) == 0 {
		buf.WriteString("type " + name + " " + goType(s) + "\n")
		return nil
	}
	required := map[string]bool{}
	for _, r := range s.Required {
		required[r] = true
	}
	keys := order
	if len(keys) == 0 { // fallback: stable alphabetical
		for k := range s.Properties {
			keys = append(keys, k)
		}
		sort.Strings(keys)
	}
	fmt.Fprintf(buf, "type %s struct {\n", name)
	for _, k := range keys {
		ps, ok := s.Properties[k]
		if !ok {
			continue
		}
		gt := goType(ps)
		opt := !required[k]
		tag := k
		if opt {
			if isValueType(gt) {
				gt = "*" + gt
			}
			tag += ",omitempty"
		}
		// Go field name: the recorded original (x-go-name) when present, else
		// derived from the wire key. The json tag always carries the wire key.
		goName := exportName(k)
		if ps.Extra != nil {
			if n, ok := ps.Extra["x-go-name"].(string); ok && n != "" {
				goName = n
			}
		}
		fmt.Fprintf(buf, "\t%s %s `json:%q`\n", goName, gt, tag)
	}
	buf.WriteString("}\n")
	return nil
}

// sumTypeOf decodes the `x-go-sumtype` descriptor from a `$def`, if present. A
// sum `$def` carries the descriptor under Extra alongside its `oneOf` variant list.
func sumTypeOf(s *jsonschema.Schema) (codegen.SumType, bool) {
	if s == nil || s.Extra == nil {
		return codegen.SumType{}, false
	}
	raw, ok := s.Extra["x-go-sumtype"]
	if !ok {
		return codegen.SumType{}, false
	}
	b, err := json.Marshal(raw)
	if err != nil {
		return codegen.SumType{}, false
	}
	var st codegen.SumType
	if err := json.Unmarshal(b, &st); err != nil {
		return codegen.SumType{}, false
	}
	return st, true
}

// emitSumType writes a sealed-interface (discriminated-union) type: the sealed
// interface itself (with a //sumtype:decl directive for go-check-sumtype), the
// per-variant marker + discriminator methods that seal the sum, and an envelope
// codec (Marshal<X>/Unmarshal<X>) that round-trips a value through the
// {discriminatorKey: <kind>, "model": <variant>} wire form — byte-identical to the
// hand-written codec.
func emitSumType(buf *bytes.Buffer, st codegen.SumType) {
	pendingImports["encoding/json"] = ""
	pendingImports["fmt"] = ""

	// The sealed interface. //sumtype:decl makes go-check-sumtype enforce
	// exhaustiveness of switches over it.
	fmt.Fprintf(buf, "// %s is the generated sealed sum interface for this contract.\n", st.Iface)
	fmt.Fprintf(buf, "//\n//sumtype:decl\n")
	fmt.Fprintf(buf, "type %s interface {\n", st.Iface)
	fmt.Fprintf(buf, "\tKind() %s\n", st.KindEnum)
	fmt.Fprintf(buf, "\t%s() // unexported marker: seals the sum to this package's variants\n", st.Marker)
	buf.WriteString("}\n\n")

	// Per-variant marker + discriminator methods (pointer receivers — variants are
	// referenced as *T, matching the hand-written convention).
	for _, v := range st.Variants {
		fmt.Fprintf(buf, "func (*%s) %s() {}\n", v.Type, st.Marker)
		fmt.Fprintf(buf, "func (*%s) Kind() %s { return %s }\n\n", v.Type, st.KindEnum, v.KindConst)
	}

	// envelope: the wire form is {discriminatorKey: <kindStr>, "model": <variant json>}.
	// The kind is a plain STRING on the wire (the variant kind strings captured in the
	// descriptor), so the codec is self-contained and byte-identical to the
	// hand-written form WITHOUT depending on a MarshalJSON on the enum (generated enums
	// carry no behavior — founder rule). Kind() on the interface still returns the
	// typed enum for exhaustiveness checking.
	env := st.Iface + "Envelope"
	fmt.Fprintf(buf, "// %s is the wire form of a %s: the string kind discriminator + the\n", env, st.Iface)
	fmt.Fprintf(buf, "// concrete variant's own JSON under \"model\".\n")
	fmt.Fprintf(buf, "type %s struct {\n", env)
	fmt.Fprintf(buf, "\tKind  string `json:%q`\n", st.DiscriminatorKey)
	fmt.Fprintf(buf, "\tModel json.RawMessage `json:%q`\n", "model,omitempty")
	buf.WriteString("}\n\n")

	// kindString<X>: maps a variant's typed discriminator value to its wire string.
	kindStrFn := "kindString" + st.Iface
	fmt.Fprintf(buf, "// %s maps a variant's discriminator value to its wire kind string.\n", kindStrFn)
	fmt.Fprintf(buf, "func %s(k %s) (string, bool) {\n", kindStrFn, st.KindEnum)
	fmt.Fprintf(buf, "\tswitch k {\n")
	for _, v := range st.Variants {
		fmt.Fprintf(buf, "\tcase %s:\n\t\treturn %q, true\n", v.KindConst, v.Kind)
	}
	fmt.Fprintf(buf, "\tdefault:\n\t\treturn \"\", false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")

	// Marshal<X>: encode any variant value to the envelope bytes.
	fmt.Fprintf(buf, "// Marshal%s encodes a %s to its {%q,\"model\"} envelope, byte-identical to\n", st.Iface, st.Iface, st.DiscriminatorKey)
	fmt.Fprintf(buf, "// the hand-written wire form. A nil value encodes as the zero envelope.\n")
	fmt.Fprintf(buf, "func Marshal%s(v %s) ([]byte, error) {\n", st.Iface, st.Iface)
	fmt.Fprintf(buf, "\tif v == nil {\n")
	fmt.Fprintf(buf, "\t\treturn json.Marshal(%s{})\n", env)
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tkind, ok := %s(v.Kind())\n", kindStrFn)
	fmt.Fprintf(buf, "\tif !ok {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"marshal %s: no wire kind for %%v\", v.Kind())\n", st.Iface)
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\traw, err := json.Marshal(v)\n")
	fmt.Fprintf(buf, "\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"marshal %s %%v: %%w\", v.Kind(), err)\n", st.Iface)
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn json.Marshal(%s{Kind: kind, Model: raw})\n", env)
	fmt.Fprintf(buf, "}\n\n")

	// new<X>ForKind: factory selecting the concrete variant by wire kind string.
	factory := "new" + st.Iface + "ForKind"
	fmt.Fprintf(buf, "// %s returns a freshly-allocated zero-value concrete variant for\n", factory)
	fmt.Fprintf(buf, "// the wire kind string, suitable for json.Unmarshal, or (nil,false) if unknown.\n")
	fmt.Fprintf(buf, "func %s(kind string) (%s, bool) {\n", factory, st.Iface)
	fmt.Fprintf(buf, "\tswitch kind {\n")
	for _, v := range st.Variants {
		fmt.Fprintf(buf, "\tcase %q:\n\t\treturn &%s{}, true\n", v.Kind, v.Type)
	}
	fmt.Fprintf(buf, "\tdefault:\n\t\treturn nil, false\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")

	// Unmarshal<X>: decode envelope bytes back to the concrete variant.
	fmt.Fprintf(buf, "// Unmarshal%s decodes a {%q,\"model\"} envelope back into the concrete\n", st.Iface, st.DiscriminatorKey)
	fmt.Fprintf(buf, "// variant selected by its kind. An empty model payload decodes to a nil value.\n")
	fmt.Fprintf(buf, "func Unmarshal%s(data []byte) (%s, error) {\n", st.Iface, st.Iface)
	fmt.Fprintf(buf, "\tvar env %s\n", env)
	fmt.Fprintf(buf, "\tif err := json.Unmarshal(data, &env); err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, err\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif len(env.Model) == 0 {\n")
	fmt.Fprintf(buf, "\t\treturn nil, nil\n")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tv, ok := %s(env.Kind)\n", factory)
	fmt.Fprintf(buf, "\tif !ok {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"unmarshal %s: no variant for kind %%q\", env.Kind)\n", st.Iface)
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\tif err := json.Unmarshal(env.Model, v); err != nil {\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"unmarshal %s %%q: %%w\", env.Kind, err)\n", st.Iface)
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "\treturn v, nil\n")
	fmt.Fprintf(buf, "}\n")
}

// emitEnum writes a named scalar type plus its const block, modeling a JSON
// Schema `enum`. Behavior (String/valid) is NOT emitted here — by founder rule the
// generated type is used AS-IS and any behavior is a free function over the value.
func emitEnum(buf *bytes.Buffer, name string, s *jsonschema.Schema) {
	base := enumBase(s)
	fmt.Fprintf(buf, "type %s %s\n", name, base)

	var names []string
	if raw, ok := s.Extra["x-enum-varnames"].([]any); ok {
		for _, n := range raw {
			if str, ok := n.(string); ok {
				names = append(names, str)
			}
		}
	}
	if len(names) != len(s.Enum) || len(names) == 0 {
		return // no const names to bind — leave the bare type
	}
	buf.WriteString("\nconst (\n")
	for i, v := range s.Enum {
		fmt.Fprintf(buf, "\t%s %s = %s\n", names[i], name, enumLiteral(v, base))
	}
	buf.WriteString(")\n")
}

// enumBase returns the Go underlying type for an enum (x-go-base wins; else mapped
// from the JSON type).
func enumBase(s *jsonschema.Schema) string {
	if b, ok := s.Extra["x-go-base"].(string); ok && b != "" {
		return b
	}
	switch effectiveType(s) {
	case "string":
		return "string"
	case "number":
		return "float64"
	default:
		return "int64"
	}
}

// enumLiteral renders one enum value as a Go literal for the base type.
func enumLiteral(v any, base string) string {
	if base == "string" {
		return fmt.Sprintf("%q", v)
	}
	if f, ok := v.(float64); ok {
		return strconv.FormatInt(int64(f), 10)
	}
	return fmt.Sprintf("%v", v)
}

// pendingImports accumulates package imports needed during a single genOne pass,
// mapping import path -> alias ("" = no alias).
var pendingImports = map[string]string{}

// goType maps a resolved schema node to its Go type.
func goType(s *jsonschema.Schema) string {
	if s == nil {
		return "interface{}"
	}
	// A well-known foundational type (time.Time, uuid.UUID, …) binds directly to
	// its canonical Go type via x-go-type, pulling in x-go-import.
	if s.Extra != nil {
		if gt, ok := s.Extra["x-go-type"].(string); ok && gt != "" {
			if imp, ok := s.Extra["x-go-import"].(string); ok && imp != "" {
				pendingImports[imp] = ""
			}
			return gt
		}
	}
	if s.Ref != "" {
		return refName(s.Ref)
	}
	t := effectiveType(s)
	nullable := hasNull(s)
	switch t {
	case "string":
		return "string"
	case "integer":
		return "int64"
	case "number":
		return "float64"
	case "boolean":
		return "bool"
	case "array":
		return "[]" + goType(s.Items)
	case "object":
		if len(s.Properties) == 0 && s.AdditionalProperties != nil {
			return "map[string]" + goType(s.AdditionalProperties)
		}
		// An open/arbitrary object (e.g. "a JSON Schema"): a generic JSON value.
		return "map[string]interface{}"
	default:
		_ = nullable
		return "interface{}"
	}
}

// effectiveType returns the schema's JSON type, ignoring a "null" member of a
// type union (nullability is handled separately via pointers).
func effectiveType(s *jsonschema.Schema) string {
	if s.Type != "" {
		return s.Type
	}
	for _, t := range s.Types {
		if t != "null" {
			return t
		}
	}
	return ""
}

func hasNull(s *jsonschema.Schema) bool {
	for _, t := range s.Types {
		if t == "null" {
			return true
		}
	}
	return false
}

// isValueType reports whether t is a Go value type that needs a pointer to be
// nilable (slices/maps/interfaces are already nilable).
func isValueType(t string) bool {
	return !strings.HasPrefix(t, "[]") &&
		!strings.HasPrefix(t, "map[") &&
		!strings.HasPrefix(t, "*") &&
		t != "interface{}"
}

// refName extracts the type name from a "#/$defs/Name" reference.
func refName(ref string) string {
	if i := strings.LastIndex(ref, "/"); i >= 0 {
		return ref[i+1:]
	}
	return ref
}

// exportName upper-cases the first rune so the field is exported. Property names
// in our contracts are already Go identifiers; this keeps them valid + exported.
func exportName(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// propOrder recovers per-def property order from the raw schema JSON.
func propOrder(raw []byte) map[string][]string {
	out := map[string][]string{}
	var top map[string]json.RawMessage
	if json.Unmarshal(raw, &top) != nil {
		return out
	}
	var defs map[string]json.RawMessage
	if json.Unmarshal(top["$defs"], &defs) != nil {
		return out
	}
	for name, defRaw := range defs {
		var def map[string]json.RawMessage
		if json.Unmarshal(defRaw, &def) != nil {
			continue
		}
		if props, ok := def["properties"]; ok {
			out[name] = orderedKeys(props)
		}
	}
	return out
}

// orderedKeys returns the keys of a JSON object in document order.
func orderedKeys(raw json.RawMessage) []string {
	dec := json.NewDecoder(bytes.NewReader(raw))
	if _, err := dec.Token(); err != nil { // opening '{'
		return nil
	}
	var keys []string
	for dec.More() {
		tok, err := dec.Token()
		if err != nil {
			return keys
		}
		keys = append(keys, tok.(string))
		var skip json.RawMessage
		if dec.Decode(&skip) != nil {
			return keys
		}
	}
	return keys
}

func fatal(f string, a ...any) {
	fmt.Fprintf(os.Stderr, f+"\n", a...)
	os.Exit(1)
}
