// Code generated by cmd/modelgen from the service-contract interface; DO NOT EDIT.
// Edit project.json's `interface` and re-run `make gen-fakes` instead.

package revenueledgerfake

import (
	"github.com/google/uuid"
	fwra "github.com/mixofreality-studio/archistrator-platform/framework-go/resourceaccess"
	"github.com/mixofreality-studio/archistrator/server/internal/resourceaccess/revenueledger"
)

// FakeRevenueLedgerAccess is a generated test double for revenueledger.RevenueLedgerAccess: set the Fn field(s)
// a test needs; calling a method whose Fn is unset panics.
type FakeRevenueLedgerAccess struct {
	RecordInboundRevenueFn func(rc fwra.Context, entry revenueledger.RevenueEntry) (revenueledger.EntryRef, error)
	RecordReversalFn       func(rc fwra.Context, reversal revenueledger.ReversalEntry) (revenueledger.EntryRef, error)
	ReadRangeFn            func(rc fwra.Context, customerID uuid.UUID, cycleID string) ([]revenueledger.RevenueEntry, error)
}

func (f *FakeRevenueLedgerAccess) RecordInboundRevenue(rc fwra.Context, entry revenueledger.RevenueEntry) (revenueledger.EntryRef, error) {
	if f.RecordInboundRevenueFn == nil {
		panic("FakeRevenueLedgerAccess.RecordInboundRevenueFn not set")
	}
	return f.RecordInboundRevenueFn(rc, entry)
}

func (f *FakeRevenueLedgerAccess) RecordReversal(rc fwra.Context, reversal revenueledger.ReversalEntry) (revenueledger.EntryRef, error) {
	if f.RecordReversalFn == nil {
		panic("FakeRevenueLedgerAccess.RecordReversalFn not set")
	}
	return f.RecordReversalFn(rc, reversal)
}

func (f *FakeRevenueLedgerAccess) ReadRange(rc fwra.Context, customerID uuid.UUID, cycleID string) ([]revenueledger.RevenueEntry, error) {
	if f.ReadRangeFn == nil {
		panic("FakeRevenueLedgerAccess.ReadRangeFn not set")
	}
	return f.ReadRangeFn(rc, customerID, cycleID)
}

var _ revenueledger.RevenueLedgerAccess = (*FakeRevenueLedgerAccess)(nil)
