//go:build configgen

// Command configgen generates the archistrator-server container's env-loaded
// configuration file (cmd/server/config.gen.go) from project.json's deployment
// model via framework-go-app-generator/configgen, plus a tiny env-name const
// file for the systemtests harness (systemtests/internal/harness/envnames.gen.go)
// read straight off the deployment settings/infrastructure declarations.
//
// WORKSPACE-ONLY BRIDGE (release follow-up): unlike cmd/appgen (which drives the
// RELEASED temporalgen/transportgen and so builds under GOWORK=off), configgen is
// UNRELEASED in framework-go-app-generator. This command therefore lives behind
// the `configgen` build tag and is run ONLY via the Go workspace
// (`go run -tags configgen ./cmd/configgen`, no GOWORK=off) — see the Makefile
// `gen-config` target. A no-op stub (stub.go, `//go:build !configgen`) keeps the
// package buildable under ordinary GOWORK=off `go build/vet/test ./...`. Once
// framework-go-app-generator ships configgen in a tag, fold this into cmd/appgen
// tag-free like temporalgen/transportgen and add gen-config-check to CI.
package main

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"

	"github.com/mixofreality-studio/archistrator-platform/framework-go-app-generator/configgen"
	projectmodel "github.com/mixofreality-studio/archistrator-platform/framework-go-projectmodel"
)

const (
	projectFile   = "../.aiarch/state/project.json"
	containerKey  = "archistrator-server"
	envPrefix     = "ARCHISTRATOR"
	serverPackage = "main"
	configOut     = "cmd/server/config.gen.go"
	envNamesOut   = "../systemtests/internal/harness/envnames.gen.go"
)

func main() {
	path := projectFile
	if len(os.Args) > 1 {
		path = os.Args[1]
	}
	m, err := projectmodel.LoadFile(path)
	if err != nil {
		fatal(err)
	}
	for _, w := range m.Warnings {
		fmt.Fprintln(os.Stderr, "configgen warning:", w)
	}

	files, err := configgen.Generate(m, configgen.Config{
		ContainerKey: containerKey,
		EnvPrefix:    envPrefix,
		PackageName:  serverPackage,
	})
	if err != nil {
		fatal(fmt.Errorf("configgen: %w", err))
	}
	src, ok := files["config.gen.go"]
	if !ok {
		fatal(fmt.Errorf("configgen: emitter returned no config.gen.go"))
	}
	// #nosec G306 -- generated source, no secret content; standard 0644 like the other gen targets
	if err := os.WriteFile(configOut, src, 0o600); err != nil {
		fatal(fmt.Errorf("write %s: %w", configOut, err))
	}
	fmt.Printf("configgen: %s → %s (%d bytes)\n", containerKey, configOut, len(src))

	if err := generateEnvNames(m); err != nil {
		fatal(fmt.Errorf("envnames: %w", err))
	}
}

// harnessEnvName is one systemtests-harness env-name const: the Go const name and
// where its value is sourced from the deployment model (a setting name, or an
// infra "<key>.<INPUT>"). Sourcing the value from the model means a rename of the
// var in project.json fails the harness COMPILE (const gone / value moved), not at
// runtime.
type harnessEnvName struct {
	Const    string // emitted Go const name
	Setting  string // deployment setting name (mutually exclusive with Infra*)
	InfraKey string // deployment infra key
	InfraIn  string // deployment infra input token
}

// harnessEnvNames is the fixed set of env-var names the systemtests harness
// binds when booting a server. Each is resolved against the committed deployment
// declarations so the emitted const carries TODAY'S exact var name.
var harnessEnvNames = []harnessEnvName{
	{Const: "EnvPostgresURL", InfraKey: "postgres", InfraIn: "URL"},
	{Const: "EnvTemporalHostPort", Setting: "temporalHostPort"},
	{Const: "EnvTemporalNamespace", Setting: "temporalNamespace"},
	{Const: "EnvListenAddr", Setting: "listenAddr"},
	{Const: "EnvAuthDevMode", Setting: "authDevMode"},
	{Const: "EnvConstructionDryRun", Setting: "constructionDryRun"},
	{Const: "EnvOperationsDryRun", Setting: "operationsDryRun"},
	{Const: "EnvProjectStateGitLocal", Setting: "projectStateGitLocal"},
	{Const: "EnvProjectStateGitRepoURL", Setting: "projectStateGitRepoURL"},
}

// generateEnvNames emits envnames.gen.go — a package-harness const block mapping
// each harnessEnvName to its resolved env var, read directly off m.Deployment.
func generateEnvNames(m *projectmodel.Model) error {
	if m.Deployment == nil {
		return fmt.Errorf("model has no deployment")
	}
	settingEnv := map[string]string{}
	for _, s := range m.Deployment.Settings {
		settingEnv[s.Name] = s.Env
	}
	infraEnv := map[string]map[string]string{}
	for _, i := range m.Deployment.Infrastructure {
		infraEnv[i.Key] = i.Env
	}

	var b []byte
	b = append(b, []byte("// Code generated by configgen. DO NOT EDIT.\n//\n")...)
	b = append(b, []byte("// Env-var names the systemtests harness binds when booting a server,\n")...)
	b = append(b, []byte("// sourced from project.json's deployment declarations so a renamed var\n")...)
	b = append(b, []byte("// fails this harness COMPILE, not at runtime.\n")...)
	b = append(b, []byte("package harness\n\nconst (\n")...)
	for _, n := range harnessEnvNames {
		var val string
		switch {
		case n.Setting != "":
			v, ok := settingEnv[n.Setting]
			if !ok || v == "" {
				return fmt.Errorf("setting %q: no resolved env in deployment", n.Setting)
			}
			val = v
		default:
			m, ok := infraEnv[n.InfraKey]
			if !ok {
				return fmt.Errorf("infra %q: not declared in deployment", n.InfraKey)
			}
			v, ok := m[n.InfraIn]
			if !ok || v == "" {
				return fmt.Errorf("infra %q input %q: no resolved env override in deployment", n.InfraKey, n.InfraIn)
			}
			val = v
		}
		b = append(b, []byte(fmt.Sprintf("\t%s = %q\n", n.Const, val))...)
	}
	b = append(b, []byte(")\n")...)

	out, err := format.Source(b)
	if err != nil {
		return fmt.Errorf("gofmt: %w\n%s", err, b)
	}
	if err := os.WriteFile(envNamesOut, out, 0o600); err != nil {
		return fmt.Errorf("write %s: %w", envNamesOut, err)
	}
	fmt.Printf("configgen: envnames → %s (%d bytes)\n", filepath.Base(envNamesOut), len(out))
	return nil
}

func fatal(err error) { fmt.Fprintln(os.Stderr, "configgen:", err); os.Exit(1) }
