// Code generated by cmd/modelgen from contract.schema.json; DO NOT EDIT.
// Edit the schema and re-run `make gen-models` instead.

package autoscaler

import (
	"github.com/google/uuid"
	fweng "github.com/mixofreality-studio/archistrator-platform/framework-go/engine"
	"time"
)

type AutoscalerMode int

const (
	AutoscalerModeAuto   AutoscalerMode = 0
	AutoscalerModeManual AutoscalerMode = 1
)

type AutoscalerPolicy struct {
	Kind             InfrastructureKind `json:"Kind"`
	Mode             AutoscalerMode     `json:"Mode"`
	MinReplicas      int64              `json:"MinReplicas"`
	MaxReplicas      int64              `json:"MaxReplicas"`
	BaselineReplicas int64              `json:"BaselineReplicas"`
	MaxStepDelta     int64              `json:"MaxStepDelta"`
	IdleThreshold    time.Duration      `json:"IdleThreshold"`
	ScaleUpCPU       float64            `json:"ScaleUpCPU"`
	ScaleDownCPU     float64            `json:"ScaleDownCPU"`
	ScaleDownGrace   time.Duration      `json:"ScaleDownGrace"`
	SLATier          SLATier            `json:"SLATier"`
	Pinned           bool               `json:"Pinned"`
	MaxBurstCap      int64              `json:"MaxBurstCap"`
}

type Decision struct {
	Kind       DecisionKind   `json:"Kind"`
	Delta      int64          `json:"Delta"`
	ToBaseline int64          `json:"ToBaseline"`
	Reason     DecisionReason `json:"Reason"`
}

type DecisionKind int

const (
	DecisionNoChange  DecisionKind = 0
	DecisionScaleUp   DecisionKind = 1
	DecisionScaleDown DecisionKind = 2
	DecisionPause     DecisionKind = 3
	DecisionResume    DecisionKind = 4
)

type DecisionReason struct {
	Code   ReasonCode `json:"Code"`
	Detail string     `json:"Detail"`
}

type DesiredState struct {
	OperatedAppID      uuid.UUID          `json:"OperatedAppID"`
	InfrastructureKind InfrastructureKind `json:"InfrastructureKind"`
	Replicas           int64              `json:"Replicas"`
	LastDecisionAt     time.Time          `json:"LastDecisionAt"`
}

type HealthStatus int

const (
	HealthUnknown   HealthStatus = 0
	HealthHealthy   HealthStatus = 1
	HealthDegraded  HealthStatus = 2
	HealthUnhealthy HealthStatus = 3
)

type InfrastructureKind int

const (
	InfrastructureKindUnknown            InfrastructureKind = 0
	InfrastructureKindGoTemporalPostgres InfrastructureKind = 1
)

type ReasonCode int

const (
	ReasonUnknown         ReasonCode = 0
	ReasonCPUHigh         ReasonCode = 1
	ReasonCPUSustainedLow ReasonCode = 2
	ReasonIdle            ReasonCode = 3
	ReasonTrafficResumed  ReasonCode = 4
	ReasonManualMode      ReasonCode = 5
	ReasonPinned          ReasonCode = 6
	ReasonSLOBurnDown     ReasonCode = 7
	ReasonAlreadyAtMin    ReasonCode = 8
	ReasonAlreadyAtMax    ReasonCode = 9
	ReasonSteady          ReasonCode = 10
)

type SLATier int

const (
	SLATierFree       SLATier = 0
	SLATierPaid       SLATier = 1
	SLATierEnterprise SLATier = 2
)

type SLOStatus int

const (
	SLOUnknown       SLOStatus = 0
	SLOWithinBudget  SLOStatus = 1
	SLOBurningBudget SLOStatus = 2
	SLOOutOfBudget   SLOStatus = 3
)

type Telemetry struct {
	OperatedAppID        uuid.UUID     `json:"OperatedAppID"`
	ObservedAt           time.Time     `json:"ObservedAt"`
	RequestsPerSecond    float64       `json:"RequestsPerSecond"`
	P95LatencyMs         float64       `json:"P95LatencyMs"`
	InflightRequests     int64         `json:"InflightRequests"`
	CurrentReplicas      int64         `json:"CurrentReplicas"`
	CPUUtilization       float64       `json:"CPUUtilization"`
	MemoryUtilization    float64       `json:"MemoryUtilization"`
	Health               HealthStatus  `json:"Health"`
	SLOStatus            SLOStatus     `json:"SLOStatus"`
	TimeSinceLastRequest time.Duration `json:"TimeSinceLastRequest"`
}

// AutoscalerEngine is the generated service-contract interface for this component.
type AutoscalerEngine interface {
	ProposeDesiredState(rc fweng.Context, telemetry Telemetry, currentDesired DesiredState, policy AutoscalerPolicy, infrastructureKind InfrastructureKind) (Decision, error)
}

// AutoscalerEngineImpl is the generated concrete AutoscalerEngine. Engines are pure (no
// dependencies), so the impl carries no fields and the constructor takes none.
// The interface methods are hand-written on this struct.
type AutoscalerEngineImpl struct{}

// NewAutoscalerEngine returns the production AutoscalerEngine.
func NewAutoscalerEngine() AutoscalerEngine { return AutoscalerEngineImpl{} }

var _ AutoscalerEngine = AutoscalerEngineImpl{}
