// Code generated by configgen. DO NOT EDIT.
//
// Env-var names the systemtests harness binds when booting a server,
// sourced from project.json's deployment declarations so a renamed var
// fails this harness COMPILE, not at runtime.
package harness

const (
	EnvPostgresURL            = "ARCHISTRATOR_POSTGRES_URL"
	EnvTemporalHostPort       = "ARCHISTRATOR_TEMPORAL_HOSTPORT"
	EnvTemporalNamespace      = "ARCHISTRATOR_TEMPORAL_NAMESPACE"
	EnvListenAddr             = "ARCHISTRATOR_LISTEN_ADDR"
	EnvAuthDevMode            = "ARCHISTRATOR_AUTH_DEV_MODE"
	EnvConstructionDryRun     = "ARCHISTRATOR_CONSTRUCTION_DRYRUN"
	EnvOperationsDryRun       = "ARCHISTRATOR_OPERATIONS_DRYRUN"
	EnvProjectStateGitLocal   = "ARCHISTRATOR_PROJECT_STATE_GIT_LOCAL"
	EnvProjectStateGitRepoURL = "ARCHISTRATOR_PROJECT_STATE_GIT_REPO_URL"
)
