// Code generated by cmd/modelgen from contract.schema.json; DO NOT EDIT.
// Edit the schema and re-run `make gen-models` instead.

package operatedsystemstate

import (
	"github.com/google/uuid"
	fwra "github.com/mixofreality-studio/archistrator-platform/framework-go/resourceaccess"
)

type AutoscaleAction int

const (
	AutoscaleNoChange  AutoscaleAction = 0
	AutoscaleScaleUp   AutoscaleAction = 1
	AutoscaleScaleDown AutoscaleAction = 2
	AutoscalePause     AutoscaleAction = 3
	AutoscaleResume    AutoscaleAction = 4
)

type AutoscaleDecision struct {
	Action     AutoscaleAction `json:"Action"`
	Delta      int64           `json:"Delta"`
	ToBaseline int64           `json:"ToBaseline"`
}

type DelinquencyAction int

const (
	DelinquencyActionUnknown   DelinquencyAction = 0
	DelinquencyActionPaused    DelinquencyAction = 1
	DelinquencyActionWithdrawn DelinquencyAction = 2
)

type DesiredStateReason int

const (
	ReasonUnknown                 DesiredStateReason = 0
	ReasonDeployAfterConstruction DesiredStateReason = 1
	ReasonOperator                DesiredStateReason = 2
	ReasonAutoscale               DesiredStateReason = 3
	ReasonDelinquency             DesiredStateReason = 4
)

type InFlightScope struct {
	AppIDs     []uuid.UUID `json:"AppIDs"`
	CustomerID *uuid.UUID  `json:"CustomerID,omitempty"`
}

type OperatedSystem struct {
	ID                  uuid.UUID     `json:"ID"`
	Version             Version       `json:"Version"`
	Status              RuntimeStatus `json:"Status"`
	InFlight            bool          `json:"InFlight"`
	DeployableBundleRef string        `json:"DeployableBundleRef"`
}

type OperatedSystemSummary struct {
	ID      uuid.UUID     `json:"ID"`
	Version Version       `json:"Version"`
	Status  RuntimeStatus `json:"Status"`
}

type RuntimeStatus int

const (
	RuntimeStatusUnknown   RuntimeStatus = 0
	RuntimeStatusPending   RuntimeStatus = 1
	RuntimeStatusHealthy   RuntimeStatus = 2
	RuntimeStatusDegraded  RuntimeStatus = 3
	RuntimeStatusWithdrawn RuntimeStatus = 4
)

type Version uint64

// OperatedSystemStateAccess is the generated service-contract interface for this component.
type OperatedSystemStateAccess interface {
	PublishDesiredState(rc fwra.Context, operatedAppID uuid.UUID, expectedVersion Version, reason DesiredStateReason, decision *AutoscaleDecision, idempotencyKey fwra.IdempotencyKey) (Version, error)
	ReadInFlightOperatedApps(rc fwra.Context, scope InFlightScope) ([]OperatedSystemSummary, error)
	ReadOperatedSystem(rc fwra.Context, operatedAppID uuid.UUID) (OperatedSystem, error)
	RecordDelinquencyAction(rc fwra.Context, operatedAppID uuid.UUID, expectedVersion Version, action DelinquencyAction, idempotencyKey fwra.IdempotencyKey) (Version, error)
	RecordRuntimeStatusChange(rc fwra.Context, operatedAppID uuid.UUID, expectedVersion Version, status RuntimeStatus, idempotencyKey fwra.IdempotencyKey) (Version, error)
	WithdrawSystem(rc fwra.Context, operatedAppID uuid.UUID, expectedVersion Version, idempotencyKey fwra.IdempotencyKey) (Version, error)
}

// stubOperatedSystemStateAccess is the generated not-implemented OperatedSystemStateAccess. The component is contracted
// but not yet built, so every method returns a not-implemented error; the bodies
// are replaced when the component is constructed.
type stubOperatedSystemStateAccess struct{}

// NewOperatedSystemStateAccess returns the not-implemented OperatedSystemStateAccess. It takes no arguments
// (the component has no infrastructure binding yet).
func NewOperatedSystemStateAccess() OperatedSystemStateAccess {
	return &stubOperatedSystemStateAccess{}
}

var _ OperatedSystemStateAccess = (*stubOperatedSystemStateAccess)(nil)

func (*stubOperatedSystemStateAccess) PublishDesiredState(_ fwra.Context, _ uuid.UUID, _ Version, _ DesiredStateReason, _ *AutoscaleDecision, _ fwra.IdempotencyKey) (Version, error) {
	var zero Version
	return zero, fwra.New(fwra.Unknown, "not implemented")
}

func (*stubOperatedSystemStateAccess) ReadInFlightOperatedApps(_ fwra.Context, _ InFlightScope) ([]OperatedSystemSummary, error) {
	var zero []OperatedSystemSummary
	return zero, fwra.New(fwra.Unknown, "not implemented")
}

func (*stubOperatedSystemStateAccess) ReadOperatedSystem(_ fwra.Context, _ uuid.UUID) (OperatedSystem, error) {
	var zero OperatedSystem
	return zero, fwra.New(fwra.Unknown, "not implemented")
}

func (*stubOperatedSystemStateAccess) RecordDelinquencyAction(_ fwra.Context, _ uuid.UUID, _ Version, _ DelinquencyAction, _ fwra.IdempotencyKey) (Version, error) {
	var zero Version
	return zero, fwra.New(fwra.Unknown, "not implemented")
}

func (*stubOperatedSystemStateAccess) RecordRuntimeStatusChange(_ fwra.Context, _ uuid.UUID, _ Version, _ RuntimeStatus, _ fwra.IdempotencyKey) (Version, error) {
	var zero Version
	return zero, fwra.New(fwra.Unknown, "not implemented")
}

func (*stubOperatedSystemStateAccess) WithdrawSystem(_ fwra.Context, _ uuid.UUID, _ Version, _ fwra.IdempotencyKey) (Version, error) {
	var zero Version
	return zero, fwra.New(fwra.Unknown, "not implemented")
}
