// Code generated by transportgen. DO NOT EDIT.

package sdk

import (
	"context"
	"fmt"
	"net/http"
)

// BillingCloseBillingCycleRequest is the JSON request body for BillingCloseBillingCycle.
type BillingCloseBillingCycleRequest struct {
	CycleID string `json:"cycleID"`
}

// BillingCloseBillingCycle calls the CloseBillingCycle operation on the Billing manager over HTTP.
func (c *HTTPClient) BillingCloseBillingCycle(ctx context.Context, customerID string, cycleID string) (CloseCycleResult, error) {
	path := fmt.Sprintf("/api/v1/billing/close-billing-cycle/%s", customerID)
	var out CloseCycleResult
	err := c.doRequest(ctx, http.MethodPost, path, BillingCloseBillingCycleRequest{CycleID: cycleID}, &out, http.StatusOK)
	return out, err
}

// BillingOnboardPaymentIntegrationRequest is the JSON request body for BillingOnboardPaymentIntegration.
type BillingOnboardPaymentIntegrationRequest struct {
}

// BillingOnboardPaymentIntegration calls the OnboardPaymentIntegration operation on the Billing manager over HTTP.
func (c *HTTPClient) BillingOnboardPaymentIntegration(ctx context.Context, deployedAppID string) (BillingRef, error) {
	path := fmt.Sprintf("/api/v1/billing/onboard-payment-integration/%s", deployedAppID)
	var out BillingRef
	err := c.doRequest(ctx, http.MethodPost, path, BillingOnboardPaymentIntegrationRequest{}, &out, http.StatusOK)
	return out, err
}

// BillingRecordInboundRevenueRequest is the JSON request body for BillingRecordInboundRevenue.
type BillingRecordInboundRevenueRequest struct {
	Event GatewayRevenueEvent `json:"event"`
}

// BillingRecordInboundRevenue calls the RecordInboundRevenue operation on the Billing manager over HTTP.
func (c *HTTPClient) BillingRecordInboundRevenue(ctx context.Context, event GatewayRevenueEvent) error {
	path := "/api/v1/billing/record-inbound-revenue"
	return c.doRequest(ctx, http.MethodPost, path, BillingRecordInboundRevenueRequest{Event: event}, nil, http.StatusNoContent)
}

// BillingRecordRevenueReversalRequest is the JSON request body for BillingRecordRevenueReversal.
type BillingRecordRevenueReversalRequest struct {
	Event GatewayReversalEvent `json:"event"`
}

// BillingRecordRevenueReversal calls the RecordRevenueReversal operation on the Billing manager over HTTP.
func (c *HTTPClient) BillingRecordRevenueReversal(ctx context.Context, event GatewayReversalEvent) error {
	path := "/api/v1/billing/record-revenue-reversal"
	return c.doRequest(ctx, http.MethodPost, path, BillingRecordRevenueReversalRequest{Event: event}, nil, http.StatusNoContent)
}

// BillingRegisterCustomerRequest is the JSON request body for BillingRegisterCustomer.
type BillingRegisterCustomerRequest struct {
}

// BillingRegisterCustomer calls the RegisterCustomer operation on the Billing manager over HTTP.
func (c *HTTPClient) BillingRegisterCustomer(ctx context.Context, customerID string) (BillingRef, error) {
	path := fmt.Sprintf("/api/v1/billing/register-customer/%s", customerID)
	var out BillingRef
	err := c.doRequest(ctx, http.MethodPost, path, BillingRegisterCustomerRequest{}, &out, http.StatusOK)
	return out, err
}

// BillingRunShortfallSweepRequest is the JSON request body for BillingRunShortfallSweep.
type BillingRunShortfallSweepRequest struct {
	TickID string `json:"tickID"`
}

// BillingRunShortfallSweep calls the RunShortfallSweep operation on the Billing manager over HTTP.
func (c *HTTPClient) BillingRunShortfallSweep(ctx context.Context, tickID string) (ShortfallSweepResult, error) {
	path := "/api/v1/billing/run-shortfall-sweep"
	var out ShortfallSweepResult
	err := c.doRequest(ctx, http.MethodPost, path, BillingRunShortfallSweepRequest{TickID: tickID}, &out, http.StatusOK)
	return out, err
}
