// Code generated by transportgen. DO NOT EDIT.

package sdk

import (
	"context"
	"fmt"
	"net/http"
)

// DeliveryStartProjectRequest is the JSON request body for DeliveryStartProject.
type DeliveryStartProjectRequest struct {
	Owner    OwnerScope      `json:"owner"`
	Name     string          `json:"name"`
	Model    *OperatingModel `json:"model,omitempty"`
	Research *ResearchInput  `json:"research,omitempty"`
	Start    bool            `json:"start"`
}

// DeliveryStartProject calls the StartProject operation on the Delivery manager over HTTP.
func (c *HTTPClient) DeliveryStartProject(ctx context.Context, owner OwnerScope, name string, projectID ProjectID, model *OperatingModel, research *ResearchInput, start bool) (StartProjectResult, error) {
	path := fmt.Sprintf("/api/v1/delivery/start-project/%s", projectID)
	var out StartProjectResult
	err := c.doRequest(ctx, http.MethodPost, path, DeliveryStartProjectRequest{Owner: owner, Name: name, Model: model, Research: research, Start: start}, &out, http.StatusOK)
	return out, err
}

// DeliveryExecuteNextActivityRequest is the JSON request body for DeliveryExecuteNextActivity.
type DeliveryExecuteNextActivityRequest struct {
	TickID string `json:"tickID"`
}

// DeliveryExecuteNextActivity calls the ExecuteNextActivity operation on the Delivery manager over HTTP.
func (c *HTTPClient) DeliveryExecuteNextActivity(ctx context.Context, projectID ProjectID, tickID string) (PumpResult, error) {
	path := fmt.Sprintf("/api/v1/delivery/execute-next-activity/%s", projectID)
	var out PumpResult
	err := c.doRequest(ctx, http.MethodPost, path, DeliveryExecuteNextActivityRequest{TickID: tickID}, &out, http.StatusOK)
	return out, err
}

// DeliveryDispatchActivityTaskRequest is the JSON request body for DeliveryDispatchActivityTask.
type DeliveryDispatchActivityTaskRequest struct {
	TaskID   string          `json:"taskID"`
	Feedback *ReviewFeedback `json:"feedback,omitempty"`
}

// DeliveryDispatchActivityTask calls the DispatchActivityTask operation on the Delivery manager over HTTP.
func (c *HTTPClient) DeliveryDispatchActivityTask(ctx context.Context, projectID ProjectID, activityID ActivityID, taskID string, feedback *ReviewFeedback) (SessionRef, error) {
	path := fmt.Sprintf("/api/v1/delivery/dispatch-activity-task/%s/%s", projectID, activityID)
	var out SessionRef
	err := c.doRequest(ctx, http.MethodPost, path, DeliveryDispatchActivityTaskRequest{TaskID: taskID, Feedback: feedback}, &out, http.StatusOK)
	return out, err
}

// DeliverySubmitReviewDecisionRequest is the JSON request body for DeliverySubmitReviewDecision.
type DeliverySubmitReviewDecisionRequest struct {
	TaskID   string              `json:"taskID"`
	Decision ReviewDecisionInput `json:"decision"`
	Feedback *ReviewFeedback     `json:"feedback,omitempty"`
}

// DeliverySubmitReviewDecision calls the SubmitReviewDecision operation on the Delivery manager over HTTP.
func (c *HTTPClient) DeliverySubmitReviewDecision(ctx context.Context, projectID ProjectID, activityID ActivityID, taskID string, decision ReviewDecisionInput, feedback *ReviewFeedback) error {
	path := fmt.Sprintf("/api/v1/delivery/submit-review-decision/%s/%s", projectID, activityID)
	return c.doRequest(ctx, http.MethodPost, path, DeliverySubmitReviewDecisionRequest{TaskID: taskID, Decision: decision, Feedback: feedback}, nil, http.StatusNoContent)
}

// DeliveryAskQuestionsRequest is the JSON request body for DeliveryAskQuestions.
type DeliveryAskQuestionsRequest struct {
	TaskID    string            `json:"taskID"`
	Addressee string            `json:"addressee"`
	Questions []AnchoredComment `json:"questions"`
}

// DeliveryAskQuestions calls the AskQuestions operation on the Delivery manager over HTTP.
func (c *HTTPClient) DeliveryAskQuestions(ctx context.Context, projectID ProjectID, activityID ActivityID, taskID string, addressee string, questions []AnchoredComment) error {
	path := fmt.Sprintf("/api/v1/delivery/ask-questions/%s/%s", projectID, activityID)
	return c.doRequest(ctx, http.MethodPost, path, DeliveryAskQuestionsRequest{TaskID: taskID, Addressee: addressee, Questions: questions}, nil, http.StatusNoContent)
}

// DeliveryAcknowledgeStaleBasisRequest is the JSON request body for DeliveryAcknowledgeStaleBasis.
type DeliveryAcknowledgeStaleBasisRequest struct {
	TaskID string `json:"taskID"`
	Note   string `json:"note"`
}

// DeliveryAcknowledgeStaleBasis calls the AcknowledgeStaleBasis operation on the Delivery manager over HTTP.
func (c *HTTPClient) DeliveryAcknowledgeStaleBasis(ctx context.Context, projectID ProjectID, activityID ActivityID, taskID string, note string) error {
	path := fmt.Sprintf("/api/v1/delivery/acknowledge-stale-basis/%s/%s", projectID, activityID)
	return c.doRequest(ctx, http.MethodPost, path, DeliveryAcknowledgeStaleBasisRequest{TaskID: taskID, Note: note}, nil, http.StatusNoContent)
}

// DeliverySetProjectRunStateRequest is the JSON request body for DeliverySetProjectRunState.
type DeliverySetProjectRunStateRequest struct {
	RunState ProjectRunState `json:"runState"`
	Reason   string          `json:"reason"`
}

// DeliverySetProjectRunState calls the SetProjectRunState operation on the Delivery manager over HTTP.
func (c *HTTPClient) DeliverySetProjectRunState(ctx context.Context, projectID ProjectID, runState ProjectRunState, reason string) error {
	path := fmt.Sprintf("/api/v1/delivery/set-project-run-state/%s", projectID)
	return c.doRequest(ctx, http.MethodPost, path, DeliverySetProjectRunStateRequest{RunState: runState, Reason: reason}, nil, http.StatusNoContent)
}

// DeliveryOverrideActivityRequest is the JSON request body for DeliveryOverrideActivity.
type DeliveryOverrideActivityRequest struct {
	Override ActivityOverride `json:"override"`
}

// DeliveryOverrideActivity calls the OverrideActivity operation on the Delivery manager over HTTP.
func (c *HTTPClient) DeliveryOverrideActivity(ctx context.Context, projectID ProjectID, activityID ActivityID, override ActivityOverride) error {
	path := fmt.Sprintf("/api/v1/delivery/override-activity/%s/%s", projectID, activityID)
	return c.doRequest(ctx, http.MethodPost, path, DeliveryOverrideActivityRequest{Override: override}, nil, http.StatusNoContent)
}

// DeliveryReplanProjectRequest is the JSON request body for DeliveryReplanProject.
type DeliveryReplanProjectRequest struct {
	TickID string `json:"tickID"`
}

// DeliveryReplanProject calls the ReplanProject operation on the Delivery manager over HTTP.
func (c *HTTPClient) DeliveryReplanProject(ctx context.Context, projectID ProjectID, tickID string) (ReplanSweepResult, error) {
	path := fmt.Sprintf("/api/v1/delivery/replan-project/%s", projectID)
	var out ReplanSweepResult
	err := c.doRequest(ctx, http.MethodPost, path, DeliveryReplanProjectRequest{TickID: tickID}, &out, http.StatusOK)
	return out, err
}

// DeliverySetProjectExecutionPolicyRequest is the JSON request body for DeliverySetProjectExecutionPolicy.
type DeliverySetProjectExecutionPolicyRequest struct {
	Policy ExecutionPolicyInput `json:"policy"`
}

// DeliverySetProjectExecutionPolicy calls the SetProjectExecutionPolicy operation on the Delivery manager over HTTP.
func (c *HTTPClient) DeliverySetProjectExecutionPolicy(ctx context.Context, projectID ProjectID, policy ExecutionPolicyInput) error {
	path := fmt.Sprintf("/api/v1/delivery/set-project-execution-policy/%s", projectID)
	return c.doRequest(ctx, http.MethodPost, path, DeliverySetProjectExecutionPolicyRequest{Policy: policy}, nil, http.StatusNoContent)
}

// DeliveryQueryProjectViewRequest is the JSON request body for DeliveryQueryProjectView.
type DeliveryQueryProjectViewRequest struct {
	Query ProjectViewQuery `json:"query"`
}

// DeliveryQueryProjectView calls the QueryProjectView operation on the Delivery manager over HTTP.
func (c *HTTPClient) DeliveryQueryProjectView(ctx context.Context, query ProjectViewQuery) (ProjectView, error) {
	path := "/api/v1/delivery/query-project-view"
	var out ProjectView
	err := c.doRequest(ctx, http.MethodPost, path, DeliveryQueryProjectViewRequest{Query: query}, &out, http.StatusOK)
	return out, err
}

// DeliveryQueryActivityView calls the QueryActivityView operation on the Delivery manager over HTTP.
func (c *HTTPClient) DeliveryQueryActivityView(ctx context.Context, projectID ProjectID, activityID ActivityID) (ActivityView, error) {
	path := fmt.Sprintf("/api/v1/delivery/query-activity-view/%s/%s", projectID, activityID)
	var out ActivityView
	err := c.doRequest(ctx, http.MethodGet, path, nil, &out, http.StatusOK)
	return out, err
}
