// Code generated by transportgen. DO NOT EDIT.

package sdk

import (
	"context"
)

// OperationsApplyDelinquencyPolicyInput is the MCP tool-call argument object for operationsApplyDelinquencyPolicy.
type OperationsApplyDelinquencyPolicyInput struct {
	CustomerID         string             `json:"customerID"`
	DelinquencyContext DelinquencyContext `json:"delinquencyContext"`
}

// OperationsApplyDelinquencyPolicy calls the operationsApplyDelinquencyPolicy tool on the Operations manager over MCP.
func (c *MCPClient) OperationsApplyDelinquencyPolicy(ctx context.Context, customerID string, delinquencyContext DelinquencyContext) error {
	return c.callTool(ctx, "operationsApplyDelinquencyPolicy", OperationsApplyDelinquencyPolicyInput{CustomerID: customerID, DelinquencyContext: delinquencyContext}, nil)
}

// OperationsDeployAfterConstructionInput is the MCP tool-call argument object for operationsDeployAfterConstruction.
type OperationsDeployAfterConstructionInput struct {
	OperatedAppID string             `json:"operatedAppID"`
	Change        DesiredStateChange `json:"change"`
}

// OperationsDeployAfterConstruction calls the operationsDeployAfterConstruction tool on the Operations manager over MCP.
func (c *MCPClient) OperationsDeployAfterConstruction(ctx context.Context, operatedAppID string, change DesiredStateChange) (DeployResult, error) {
	return mcpCallResult[DeployResult](c, ctx, "operationsDeployAfterConstruction", OperationsDeployAfterConstructionInput{OperatedAppID: operatedAppID, Change: change})
}

// OperationsQueryCostProjectionInput is the MCP tool-call argument object for operationsQueryCostProjection.
type OperationsQueryCostProjectionInput struct {
	OperatedAppID string             `json:"operatedAppID"`
	RequestID     string             `json:"requestID"`
	Points        *ScaleWhatIfPoints `json:"points,omitempty"`
}

// OperationsQueryCostProjection calls the operationsQueryCostProjection tool on the Operations manager over MCP.
func (c *MCPClient) OperationsQueryCostProjection(ctx context.Context, operatedAppID string, requestID string, points *ScaleWhatIfPoints) (CostProjectionSeam, error) {
	return mcpCallResult[CostProjectionSeam](c, ctx, "operationsQueryCostProjection", OperationsQueryCostProjectionInput{OperatedAppID: operatedAppID, RequestID: requestID, Points: points})
}

// OperationsQueryDeploymentHealthInput is the MCP tool-call argument object for operationsQueryDeploymentHealth.
type OperationsQueryDeploymentHealthInput struct {
	OperatedAppID string `json:"operatedAppID"`
}

// OperationsQueryDeploymentHealth calls the operationsQueryDeploymentHealth tool on the Operations manager over MCP.
func (c *MCPClient) OperationsQueryDeploymentHealth(ctx context.Context, operatedAppID string) (DeploymentHealth, error) {
	return mcpCallResult[DeploymentHealth](c, ctx, "operationsQueryDeploymentHealth", OperationsQueryDeploymentHealthInput{OperatedAppID: operatedAppID})
}

// OperationsQueryOperatedSystemViewInput is the MCP tool-call argument object for operationsQueryOperatedSystemView.
type OperationsQueryOperatedSystemViewInput struct {
	OperatedAppID string `json:"operatedAppID"`
	RequestID     string `json:"requestID"`
}

// OperationsQueryOperatedSystemView calls the operationsQueryOperatedSystemView tool on the Operations manager over MCP.
func (c *MCPClient) OperationsQueryOperatedSystemView(ctx context.Context, operatedAppID string, requestID string) (OperatedSystemView, error) {
	return mcpCallResult[OperatedSystemView](c, ctx, "operationsQueryOperatedSystemView", OperationsQueryOperatedSystemViewInput{OperatedAppID: operatedAppID, RequestID: requestID})
}

// OperationsReconcileOperatedStateInput is the MCP tool-call argument object for operationsReconcileOperatedState.
type OperationsReconcileOperatedStateInput struct {
	TickID string          `json:"tickID"`
	Scope  *ReconcileScope `json:"scope,omitempty"`
}

// OperationsReconcileOperatedState calls the operationsReconcileOperatedState tool on the Operations manager over MCP.
func (c *MCPClient) OperationsReconcileOperatedState(ctx context.Context, tickID string, scope *ReconcileScope) (ReconcileResult, error) {
	return mcpCallResult[ReconcileResult](c, ctx, "operationsReconcileOperatedState", OperationsReconcileOperatedStateInput{TickID: tickID, Scope: scope})
}

// OperationsRegisterOperatedAppInput is the MCP tool-call argument object for operationsRegisterOperatedApp.
type OperationsRegisterOperatedAppInput struct {
	OperatedAppID       string `json:"operatedAppID"`
	CustomerID          string `json:"customerID"`
	ProjectRef          string `json:"projectRef"`
	DeployableBundleRef string `json:"deployableBundleRef"`
}

// OperationsRegisterOperatedApp calls the operationsRegisterOperatedApp tool on the Operations manager over MCP.
func (c *MCPClient) OperationsRegisterOperatedApp(ctx context.Context, operatedAppID string, customerID string, projectRef string, deployableBundleRef string) (OperationsVersion, error) {
	return mcpCallResult[OperationsVersion](c, ctx, "operationsRegisterOperatedApp", OperationsRegisterOperatedAppInput{OperatedAppID: operatedAppID, CustomerID: customerID, ProjectRef: projectRef, DeployableBundleRef: deployableBundleRef})
}

// OperationsWithdrawSystemInput is the MCP tool-call argument object for operationsWithdrawSystem.
type OperationsWithdrawSystemInput struct {
	OperatedAppID string         `json:"operatedAppID"`
	ChangeID      string         `json:"changeID"`
	Reason        WithdrawReason `json:"reason"`
}

// OperationsWithdrawSystem calls the operationsWithdrawSystem tool on the Operations manager over MCP.
func (c *MCPClient) OperationsWithdrawSystem(ctx context.Context, operatedAppID string, changeID string, reason WithdrawReason) (WithdrawResult, error) {
	return mcpCallResult[WithdrawResult](c, ctx, "operationsWithdrawSystem", OperationsWithdrawSystemInput{OperatedAppID: operatedAppID, ChangeID: changeID, Reason: reason})
}
