// Code generated by transportgen. DO NOT EDIT.

package sdk

import (
	"context"
)

// BillingCloseBillingCycleInput is the MCP tool-call argument object for billingCloseBillingCycle.
type BillingCloseBillingCycleInput struct {
	CustomerID string `json:"customerID"`
	CycleID    string `json:"cycleID"`
}

// BillingCloseBillingCycle calls the billingCloseBillingCycle tool on the Billing manager over MCP.
func (c *MCPClient) BillingCloseBillingCycle(ctx context.Context, customerID string, cycleID string) (CloseCycleResult, error) {
	return mcpCallResult[CloseCycleResult](c, ctx, "billingCloseBillingCycle", BillingCloseBillingCycleInput{CustomerID: customerID, CycleID: cycleID})
}

// BillingOnboardPaymentIntegrationInput is the MCP tool-call argument object for billingOnboardPaymentIntegration.
type BillingOnboardPaymentIntegrationInput struct {
	DeployedAppID string `json:"deployedAppID"`
}

// BillingOnboardPaymentIntegration calls the billingOnboardPaymentIntegration tool on the Billing manager over MCP.
func (c *MCPClient) BillingOnboardPaymentIntegration(ctx context.Context, deployedAppID string) (BillingRef, error) {
	return mcpCallResult[BillingRef](c, ctx, "billingOnboardPaymentIntegration", BillingOnboardPaymentIntegrationInput{DeployedAppID: deployedAppID})
}

// BillingRecordInboundRevenueInput is the MCP tool-call argument object for billingRecordInboundRevenue.
type BillingRecordInboundRevenueInput struct {
	Event GatewayRevenueEvent `json:"event"`
}

// BillingRecordInboundRevenue calls the billingRecordInboundRevenue tool on the Billing manager over MCP.
func (c *MCPClient) BillingRecordInboundRevenue(ctx context.Context, event GatewayRevenueEvent) error {
	return c.callTool(ctx, "billingRecordInboundRevenue", BillingRecordInboundRevenueInput{Event: event}, nil)
}

// BillingRecordRevenueReversalInput is the MCP tool-call argument object for billingRecordRevenueReversal.
type BillingRecordRevenueReversalInput struct {
	Event GatewayReversalEvent `json:"event"`
}

// BillingRecordRevenueReversal calls the billingRecordRevenueReversal tool on the Billing manager over MCP.
func (c *MCPClient) BillingRecordRevenueReversal(ctx context.Context, event GatewayReversalEvent) error {
	return c.callTool(ctx, "billingRecordRevenueReversal", BillingRecordRevenueReversalInput{Event: event}, nil)
}

// BillingRegisterCustomerInput is the MCP tool-call argument object for billingRegisterCustomer.
type BillingRegisterCustomerInput struct {
	CustomerID string `json:"customerID"`
}

// BillingRegisterCustomer calls the billingRegisterCustomer tool on the Billing manager over MCP.
func (c *MCPClient) BillingRegisterCustomer(ctx context.Context, customerID string) (BillingRef, error) {
	return mcpCallResult[BillingRef](c, ctx, "billingRegisterCustomer", BillingRegisterCustomerInput{CustomerID: customerID})
}

// BillingRunShortfallSweepInput is the MCP tool-call argument object for billingRunShortfallSweep.
type BillingRunShortfallSweepInput struct {
	TickID string `json:"tickID"`
}

// BillingRunShortfallSweep calls the billingRunShortfallSweep tool on the Billing manager over MCP.
func (c *MCPClient) BillingRunShortfallSweep(ctx context.Context, tickID string) (ShortfallSweepResult, error) {
	return mcpCallResult[ShortfallSweepResult](c, ctx, "billingRunShortfallSweep", BillingRunShortfallSweepInput{TickID: tickID})
}
