// Code generated by transportgen. DO NOT EDIT.

package sdk

import (
	"time"
)

type BillingMoney struct {
	MinorUnits int64  `json:"minorUnits"`
	Currency   string `json:"currency"`
}

type BillingRef struct {
	CustomerID string `json:"customerId"`
}

type CloseCycleResult struct {
	CustomerID string           `json:"customerId"`
	CycleID    string           `json:"cycleId"`
	Routed     RoutingDirective `json:"routed"`
	Escalated  bool             `json:"escalated"`
}

type GatewayRevenueEvent struct {
	GatewayEventID string       `json:"gatewayEventId"`
	CustomerID     string       `json:"customerId"`
	CycleID        string       `json:"cycleId"`
	Amount         BillingMoney `json:"amount"`
	OccurredAt     time.Time    `json:"occurredAt"`
}

type GatewayReversalEvent struct {
	GatewayEventID         string       `json:"gatewayEventId"`
	CustomerID             string       `json:"customerId"`
	CycleID                string       `json:"cycleId"`
	Amount                 BillingMoney `json:"amount"`
	ReversesGatewayEventID *string      `json:"reversesGatewayEventId,omitempty"`
	OccurredAt             time.Time    `json:"occurredAt"`
}

type RoutingDirective int

const (
	RoutingDirectiveNoAction RoutingDirective = 0
	RoutingDirectiveCharge   RoutingDirective = 2
)

type ShortfallSweepResult struct {
	SignalledCustomers []string `json:"signalledCustomers"`
}

// RoutingDirectiveName returns the declared varname of a RoutingDirective value.
func RoutingDirectiveName(v RoutingDirective) string {
	switch v {
	case RoutingDirectiveNoAction:
		return "RoutingDirectiveNoAction"
	case RoutingDirectiveCharge:
		return "RoutingDirectiveCharge"
	default:
		return ""
	}
}
