// Code generated by transportgen. DO NOT EDIT.

package sdk

type ActivityID string

type ActivityOverride struct {
	Kind     OverrideKind                  `json:"kind"`
	Notes    string                        `json:"notes"`
	Comments []ConstructionAnchoredComment `json:"comments,omitempty"`
}

type ConstructionAnchoredComment struct {
	JSONPath string `json:"jsonPath"`
	Text     string `json:"text"`
}

type ConstructionReviewFeedback struct {
	Notes    string                        `json:"notes"`
	Comments []ConstructionAnchoredComment `json:"comments,omitempty"`
}

type ConstructionSessionView struct {
	ProjectID     ProjectID         `json:"projectId"`
	ActivityID    *ActivityID       `json:"activityId,omitempty"`
	Stage         ConstructionStage `json:"stage"`
	PipelinePhase *PipelinePhase    `json:"pipelinePhase,omitempty"`
	ReviewSet     *ReviewSet        `json:"reviewSet,omitempty"`
	Variance      *FlaggedVariance  `json:"variance,omitempty"`
}

type ConstructionStage int

const (
	ConstructionStageUnknown ConstructionStage = 0
	StageDispatching         ConstructionStage = 1
	StagePipelineRunning     ConstructionStage = 2
	StageReviewing           ConstructionStage = 3
	StageAwaitingTakeover    ConstructionStage = 4
	StagePaused              ConstructionStage = 5
	StageExited              ConstructionStage = 6
	StageAwaitingApproval    ConstructionStage = 7
)

type FlaggedVariance struct {
	ProjectID  ProjectID  `json:"projectId"`
	ActivityID ActivityID `json:"activityId"`
	Summary    string     `json:"summary"`
}

type OverrideKind int

const (
	OverrideUnknown  OverrideKind = 0
	OverrideTakeover OverrideKind = 1
	OverrideRetry    OverrideKind = 2
	OverrideSkip     OverrideKind = 3
	OverrideReassign OverrideKind = 4
)

type PhaseDecision int

const (
	PhaseDecisionUnknown PhaseDecision = 0
	PhaseApprove         PhaseDecision = 1
	PhaseSendBack        PhaseDecision = 2
)

type PipelinePhase int

const (
	PipelinePhaseUnknown PipelinePhase = 0
	PipelinePending      PipelinePhase = 1
	PipelineRunning      PipelinePhase = 2
	PipelineSucceeded    PipelinePhase = 3
	PipelineFailed       PipelinePhase = 4
	PipelineCancelled    PipelinePhase = 5
)

type PumpResult struct {
	Dispatched bool        `json:"dispatched"`
	ActivityID *ActivityID `json:"activityId,omitempty"`
}

type ReplanSweepResult struct {
	FlaggedVariances []FlaggedVariance `json:"flaggedVariances,omitempty"`
}

type ReviewPolicyInput struct {
	GatedPhasesByType map[string][]string `json:"gatedPhasesByType"`
}

type ReviewSet struct {
	Reviewers []Reviewer `json:"reviewers,omitempty"`
}

type Reviewer struct {
	Role              string  `json:"role"`
	Perspective       string  `json:"perspective"`
	ReferenceArtifact *string `json:"referenceArtifact,omitempty"`
	MayAmend          bool    `json:"mayAmend"`
}

// ConstructionStageName returns the declared varname of a ConstructionStage value.
func ConstructionStageName(v ConstructionStage) string {
	switch v {
	case ConstructionStageUnknown:
		return "ConstructionStageUnknown"
	case StageDispatching:
		return "StageDispatching"
	case StagePipelineRunning:
		return "StagePipelineRunning"
	case StageReviewing:
		return "StageReviewing"
	case StageAwaitingTakeover:
		return "StageAwaitingTakeover"
	case StagePaused:
		return "StagePaused"
	case StageExited:
		return "StageExited"
	case StageAwaitingApproval:
		return "StageAwaitingApproval"
	default:
		return ""
	}
}

// OverrideKindName returns the declared varname of a OverrideKind value.
func OverrideKindName(v OverrideKind) string {
	switch v {
	case OverrideUnknown:
		return "OverrideUnknown"
	case OverrideTakeover:
		return "OverrideTakeover"
	case OverrideRetry:
		return "OverrideRetry"
	case OverrideSkip:
		return "OverrideSkip"
	case OverrideReassign:
		return "OverrideReassign"
	default:
		return ""
	}
}

// PhaseDecisionName returns the declared varname of a PhaseDecision value.
func PhaseDecisionName(v PhaseDecision) string {
	switch v {
	case PhaseDecisionUnknown:
		return "PhaseDecisionUnknown"
	case PhaseApprove:
		return "PhaseApprove"
	case PhaseSendBack:
		return "PhaseSendBack"
	default:
		return ""
	}
}

// PipelinePhaseName returns the declared varname of a PipelinePhase value.
func PipelinePhaseName(v PipelinePhase) string {
	switch v {
	case PipelinePhaseUnknown:
		return "PipelinePhaseUnknown"
	case PipelinePending:
		return "PipelinePending"
	case PipelineRunning:
		return "PipelineRunning"
	case PipelineSucceeded:
		return "PipelineSucceeded"
	case PipelineFailed:
		return "PipelineFailed"
	case PipelineCancelled:
		return "PipelineCancelled"
	default:
		return ""
	}
}
