// Code generated by transportgen. DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

type ActiveRole int

const (
	ActiveRoleNone           ActiveRole = 0
	ActiveRoleArchitect      ActiveRole = 1
	ActiveRoleProductManager ActiveRole = 2
)

type ActiveStep int

const (
	ActiveStepNone       ActiveStep = 0
	ActiveStepDrafting   ActiveStep = 1
	ActiveStepCritiquing ActiveStep = 2
	ActiveStepRevising   ActiveStep = 3
)

type ArtifactKind int

const (
	KindMission              ArtifactKind = 0
	KindGlossary             ArtifactKind = 1
	KindScrubbedRequirements ArtifactKind = 2
	KindVolatilities         ArtifactKind = 3
	KindCoreUseCases         ArtifactKind = 4
	KindSystem               ArtifactKind = 5
	KindOperationalConcepts  ArtifactKind = 6
	KindStandardCheck        ArtifactKind = 7
	KindPlanningAssumptions  ArtifactKind = 8
	KindActivityList         ArtifactKind = 9
	KindNetwork              ArtifactKind = 10
	KindNormalSolution       ArtifactKind = 11
	KindSubcriticalSolution  ArtifactKind = 12
	KindCompressedSolution   ArtifactKind = 13
	KindDecompressedSolution ArtifactKind = 14
	KindRiskModel            ArtifactKind = 15
	KindSdpReview            ArtifactKind = 16
)

type DraftModel struct {
	Kind  string           `json:"kind"`
	Model *json.RawMessage `json:"model,omitempty"`
}

type Finding struct {
	RuleID   RuleID    `json:"ruleId"`
	Severity Severity  `json:"severity"`
	Message  string    `json:"message"`
	Location *Location `json:"location,omitempty"`
}

type Location struct {
	Ordinal int64  `json:"ordinal"`
	Section string `json:"section"`
}

type PhaseAdvanceResult struct {
	Advanced         bool           `json:"advanced"`
	MissingArtifacts []ArtifactKind `json:"missingArtifacts"`
}

type ProjectID string

type ReviewCommentView struct {
	ID         string `json:"id"`
	Anchor     string `json:"anchor"`
	AnchorText string `json:"anchorText"`
	Text       string `json:"text"`
	AuthorRole string `json:"authorRole"`
	Round      int64  `json:"round"`
	Status     string `json:"status"`
	Response   string `json:"response"`
	Type       string `json:"type"`
	Addressee  string `json:"addressee"`
}

type ReviewDecision int

const (
	ReviewDecisionUnknown ReviewDecision = 0
	ReviewApprove         ReviewDecision = 1
	ReviewReject          ReviewDecision = 2
	ReviewWithdraw        ReviewDecision = 3
)

type RuleID string

type SessionRef string

type Severity string

const (
	SeverityInfo    Severity = "info"
	SeverityWarning Severity = "warning"
	SeverityError   Severity = "error"
)

// ActiveRoleName returns the declared varname of a ActiveRole value.
func ActiveRoleName(v ActiveRole) string {
	switch v {
	case ActiveRoleNone:
		return "ActiveRoleNone"
	case ActiveRoleArchitect:
		return "ActiveRoleArchitect"
	case ActiveRoleProductManager:
		return "ActiveRoleProductManager"
	default:
		return ""
	}
}

// ActiveStepName returns the declared varname of a ActiveStep value.
func ActiveStepName(v ActiveStep) string {
	switch v {
	case ActiveStepNone:
		return "ActiveStepNone"
	case ActiveStepDrafting:
		return "ActiveStepDrafting"
	case ActiveStepCritiquing:
		return "ActiveStepCritiquing"
	case ActiveStepRevising:
		return "ActiveStepRevising"
	default:
		return ""
	}
}

// ArtifactKindName returns the declared varname of a ArtifactKind value.
func ArtifactKindName(v ArtifactKind) string {
	switch v {
	case KindMission:
		return "KindMission"
	case KindGlossary:
		return "KindGlossary"
	case KindScrubbedRequirements:
		return "KindScrubbedRequirements"
	case KindVolatilities:
		return "KindVolatilities"
	case KindCoreUseCases:
		return "KindCoreUseCases"
	case KindSystem:
		return "KindSystem"
	case KindOperationalConcepts:
		return "KindOperationalConcepts"
	case KindStandardCheck:
		return "KindStandardCheck"
	case KindPlanningAssumptions:
		return "KindPlanningAssumptions"
	case KindActivityList:
		return "KindActivityList"
	case KindNetwork:
		return "KindNetwork"
	case KindNormalSolution:
		return "KindNormalSolution"
	case KindSubcriticalSolution:
		return "KindSubcriticalSolution"
	case KindCompressedSolution:
		return "KindCompressedSolution"
	case KindDecompressedSolution:
		return "KindDecompressedSolution"
	case KindRiskModel:
		return "KindRiskModel"
	case KindSdpReview:
		return "KindSdpReview"
	default:
		return ""
	}
}

// ReviewDecisionName returns the declared varname of a ReviewDecision value.
func ReviewDecisionName(v ReviewDecision) string {
	switch v {
	case ReviewDecisionUnknown:
		return "ReviewDecisionUnknown"
	case ReviewApprove:
		return "ReviewApprove"
	case ReviewReject:
		return "ReviewReject"
	case ReviewWithdraw:
		return "ReviewWithdraw"
	default:
		return ""
	}
}

// SeverityName returns the declared varname of a Severity value.
func SeverityName(v Severity) string {
	switch v {
	case SeverityInfo:
		return "SeverityInfo"
	case SeverityWarning:
		return "SeverityWarning"
	case SeverityError:
		return "SeverityError"
	default:
		return ""
	}
}
