// Code generated by transportgen. DO NOT EDIT.

package sdk

import "encoding/json"

// These aliases stand in for server in-package types a contract binds via
// x-go-type but does not carry in its $defs; the SDK keeps them opaque so a
// caller can still round-trip the enclosing DTO.
type ProvenanceView = json.RawMessage
type StaleCauseView = json.RawMessage
