// Code generated by transportgen. DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"time"
)

type ActiveRole int

const (
	ActiveRoleNone           ActiveRole = 0
	ActiveRoleArchitect      ActiveRole = 1
	ActiveRoleProductManager ActiveRole = 2
)

type ActiveStep int

const (
	ActiveStepNone       ActiveStep = 0
	ActiveStepDrafting   ActiveStep = 1
	ActiveStepCritiquing ActiveStep = 2
	ActiveStepRevising   ActiveStep = 3
)

type ArtifactKind int

const (
	KindMission              ArtifactKind = 0
	KindGlossary             ArtifactKind = 1
	KindScrubbedRequirements ArtifactKind = 2
	KindVolatilities         ArtifactKind = 3
	KindCoreUseCases         ArtifactKind = 4
	KindSystem               ArtifactKind = 5
	KindOperationalConcepts  ArtifactKind = 6
	KindStandardCheck        ArtifactKind = 7
	KindPlanningAssumptions  ArtifactKind = 8
	KindActivityList         ArtifactKind = 9
	KindNetwork              ArtifactKind = 10
	KindNormalSolution       ArtifactKind = 11
	KindSubcriticalSolution  ArtifactKind = 12
	KindCompressedSolution   ArtifactKind = 13
	KindDecompressedSolution ArtifactKind = 14
	KindRiskModel            ArtifactKind = 15
	KindSdpReview            ArtifactKind = 16
)

type DraftModel struct {
	Kind  string           `json:"kind"`
	Model *json.RawMessage `json:"model,omitempty"`
}

type EpisodeKind int

const (
	EpisodeKindDesign       EpisodeKind = 0
	EpisodeKindConstruction EpisodeKind = 1
	EpisodeKindReview       EpisodeKind = 2
	EpisodeKindRework       EpisodeKind = 3
	EpisodeKindAnswer       EpisodeKind = 4
)

type EpisodeLineage struct {
	WorkflowID string  `json:"workflowId"`
	RunID      string  `json:"runId"`
	ActivityID *string `json:"activityId,omitempty"`
}

type EpisodeOutcome int

const (
	EpisodeSucceeded EpisodeOutcome = 0
	EpisodeFailed    EpisodeOutcome = 1
	EpisodeCancelled EpisodeOutcome = 2
	EpisodeGap       EpisodeOutcome = 3
)

type EpisodeRecordView struct {
	EpisodeID      string           `json:"episodeId"`
	Kind           EpisodeKind      `json:"kind"`
	TargetRef      string           `json:"targetRef"`
	Lineage        *EpisodeLineage  `json:"lineage,omitempty"`
	WorkerClass    *string          `json:"workerClass,omitempty"`
	Model          *string          `json:"model,omitempty"`
	Usage          EpisodeUsage     `json:"usage"`
	StreamedUsage  *EpisodeUsage    `json:"streamedUsage,omitempty"`
	CostUSD        *float64         `json:"costUsd,omitempty"`
	NumTurns       *int64           `json:"numTurns,omitempty"`
	ToolCallCounts map[string]int64 `json:"toolCallCounts,omitempty"`
	SubagentSpans  []SubagentSpan   `json:"subagentSpans,omitempty"`
	StartedAt      time.Time        `json:"startedAt"`
	EndedAt        time.Time        `json:"endedAt"`
	Outcome        EpisodeOutcome   `json:"outcome"`
	GapReason      *string          `json:"gapReason,omitempty"`
	TracePath      *string          `json:"tracePath,omitempty"`
}

type EpisodeTimeline struct {
	Record EpisodeRecordView `json:"record"`
	Events []TimelineEvent   `json:"events"`
}

type EpisodeUsage struct {
	In          int64 `json:"in"`
	Out         int64 `json:"out"`
	CacheRead   int64 `json:"cacheRead"`
	CacheCreate int64 `json:"cacheCreate"`
}

type Finding struct {
	RuleID   RuleID    `json:"ruleId"`
	Severity Severity  `json:"severity"`
	Message  string    `json:"message"`
	Location *Location `json:"location,omitempty"`
}

type Location struct {
	Ordinal int64  `json:"ordinal"`
	Section string `json:"section"`
}

type PhaseAdvanceResult struct {
	Advanced         bool           `json:"advanced"`
	MissingArtifacts []ArtifactKind `json:"missingArtifacts"`
}

type ProjectID string

type ReviewCommentView struct {
	ID         string `json:"id"`
	Anchor     string `json:"anchor"`
	AnchorText string `json:"anchorText"`
	Text       string `json:"text"`
	AuthorRole string `json:"authorRole"`
	Round      int64  `json:"round"`
	Status     string `json:"status"`
	Response   string `json:"response"`
	Type       string `json:"type"`
	Addressee  string `json:"addressee"`
}

type ReviewDecision int

const (
	ReviewDecisionUnknown ReviewDecision = 0
	ReviewApprove         ReviewDecision = 1
	ReviewReject          ReviewDecision = 2
	ReviewWithdraw        ReviewDecision = 3
)

type RuleID string

type SessionRef string

type Severity string

const (
	SeverityInfo    Severity = "info"
	SeverityWarning Severity = "warning"
	SeverityError   Severity = "error"
)

type SubagentSpan struct {
	ToolUseID string     `json:"toolUseId"`
	StartedAt *time.Time `json:"startedAt,omitempty"`
	EndedAt   *time.Time `json:"endedAt,omitempty"`
}

type TimelineEvent struct {
	Seq       int64            `json:"seq"`
	EventType string           `json:"eventType"`
	Raw       *json.RawMessage `json:"raw,omitempty"`
}

// ActiveRoleName returns the declared varname of a ActiveRole value.
func ActiveRoleName(v ActiveRole) string {
	switch v {
	case ActiveRoleNone:
		return "ActiveRoleNone"
	case ActiveRoleArchitect:
		return "ActiveRoleArchitect"
	case ActiveRoleProductManager:
		return "ActiveRoleProductManager"
	default:
		return ""
	}
}

// ActiveStepName returns the declared varname of a ActiveStep value.
func ActiveStepName(v ActiveStep) string {
	switch v {
	case ActiveStepNone:
		return "ActiveStepNone"
	case ActiveStepDrafting:
		return "ActiveStepDrafting"
	case ActiveStepCritiquing:
		return "ActiveStepCritiquing"
	case ActiveStepRevising:
		return "ActiveStepRevising"
	default:
		return ""
	}
}

// ArtifactKindName returns the declared varname of a ArtifactKind value.
func ArtifactKindName(v ArtifactKind) string {
	switch v {
	case KindMission:
		return "KindMission"
	case KindGlossary:
		return "KindGlossary"
	case KindScrubbedRequirements:
		return "KindScrubbedRequirements"
	case KindVolatilities:
		return "KindVolatilities"
	case KindCoreUseCases:
		return "KindCoreUseCases"
	case KindSystem:
		return "KindSystem"
	case KindOperationalConcepts:
		return "KindOperationalConcepts"
	case KindStandardCheck:
		return "KindStandardCheck"
	case KindPlanningAssumptions:
		return "KindPlanningAssumptions"
	case KindActivityList:
		return "KindActivityList"
	case KindNetwork:
		return "KindNetwork"
	case KindNormalSolution:
		return "KindNormalSolution"
	case KindSubcriticalSolution:
		return "KindSubcriticalSolution"
	case KindCompressedSolution:
		return "KindCompressedSolution"
	case KindDecompressedSolution:
		return "KindDecompressedSolution"
	case KindRiskModel:
		return "KindRiskModel"
	case KindSdpReview:
		return "KindSdpReview"
	default:
		return ""
	}
}

// EpisodeKindName returns the declared varname of a EpisodeKind value.
func EpisodeKindName(v EpisodeKind) string {
	switch v {
	case EpisodeKindDesign:
		return "EpisodeKindDesign"
	case EpisodeKindConstruction:
		return "EpisodeKindConstruction"
	case EpisodeKindReview:
		return "EpisodeKindReview"
	case EpisodeKindRework:
		return "EpisodeKindRework"
	case EpisodeKindAnswer:
		return "EpisodeKindAnswer"
	default:
		return ""
	}
}

// EpisodeOutcomeName returns the declared varname of a EpisodeOutcome value.
func EpisodeOutcomeName(v EpisodeOutcome) string {
	switch v {
	case EpisodeSucceeded:
		return "EpisodeSucceeded"
	case EpisodeFailed:
		return "EpisodeFailed"
	case EpisodeCancelled:
		return "EpisodeCancelled"
	case EpisodeGap:
		return "EpisodeGap"
	default:
		return ""
	}
}

// ReviewDecisionName returns the declared varname of a ReviewDecision value.
func ReviewDecisionName(v ReviewDecision) string {
	switch v {
	case ReviewDecisionUnknown:
		return "ReviewDecisionUnknown"
	case ReviewApprove:
		return "ReviewApprove"
	case ReviewReject:
		return "ReviewReject"
	case ReviewWithdraw:
		return "ReviewWithdraw"
	default:
		return ""
	}
}

// SeverityName returns the declared varname of a Severity value.
func SeverityName(v Severity) string {
	switch v {
	case SeverityInfo:
		return "SeverityInfo"
	case SeverityWarning:
		return "SeverityWarning"
	case SeverityError:
		return "SeverityError"
	default:
		return ""
	}
}
