// Code generated by transportgen. DO NOT EDIT.

package sdk

type OptionID string

type ProjectDesignAnchoredComment struct {
	JSONPath   string `json:"jsonPath"`
	Text       string `json:"text"`
	AnchorText string `json:"anchorText"`
}

type ProjectDesignReviewFeedback struct {
	Notes    string                         `json:"notes"`
	Comments []ProjectDesignAnchoredComment `json:"comments,omitempty"`
}

type ProjectDesignSessionStage int

const (
	ProjectDesignSessionStageUnknown ProjectDesignSessionStage = 0
	ProjectDesignStageDrafting       ProjectDesignSessionStage = 1
	ProjectDesignStageAssemblingSDP  ProjectDesignSessionStage = 2
	ProjectDesignStageAwaitingReview ProjectDesignSessionStage = 3
	ProjectDesignStageRedrafting     ProjectDesignSessionStage = 4
	ProjectDesignStageCommitted      ProjectDesignSessionStage = 5
	ProjectDesignStageWithdrawn      ProjectDesignSessionStage = 6
	ProjectDesignStageRefused        ProjectDesignSessionStage = 7
	ProjectDesignStageDraftFailed    ProjectDesignSessionStage = 8
)

type ProjectDesignSessionStateView struct {
	ProjectID     ProjectID                 `json:"projectId"`
	ArtifactKind  ArtifactKind              `json:"artifactKind"`
	Stage         ProjectDesignSessionStage `json:"stage"`
	Draft         DraftModel                `json:"draft"`
	Findings      []Finding                 `json:"findings,omitempty"`
	FailureReason *string                   `json:"failureReason,omitempty"`
	StageName     string                    `json:"stageName"`
	ReviewThread  []ReviewCommentView       `json:"reviewThread,omitempty"`
	ActiveRole    ActiveRole                `json:"activeRole"`
	ActiveStep    ActiveStep                `json:"activeStep"`
	Round         int64                     `json:"round"`
}

type SDPDecision int

const (
	SDPDecisionUnknown SDPDecision = 0
	SDPCommit          SDPDecision = 1
	SDPRejectAll       SDPDecision = 2
)

// SDPDecisionName returns the declared varname of a SDPDecision value.
func SDPDecisionName(v SDPDecision) string {
	switch v {
	case SDPDecisionUnknown:
		return "SDPDecisionUnknown"
	case SDPCommit:
		return "SDPCommit"
	case SDPRejectAll:
		return "SDPRejectAll"
	default:
		return ""
	}
}

// ProjectDesignSessionStageName returns the declared varname of a ProjectDesignSessionStage value.
func ProjectDesignSessionStageName(v ProjectDesignSessionStage) string {
	switch v {
	case ProjectDesignSessionStageUnknown:
		return "ProjectDesignSessionStageUnknown"
	case ProjectDesignStageDrafting:
		return "ProjectDesignStageDrafting"
	case ProjectDesignStageAssemblingSDP:
		return "ProjectDesignStageAssemblingSDP"
	case ProjectDesignStageAwaitingReview:
		return "ProjectDesignStageAwaitingReview"
	case ProjectDesignStageRedrafting:
		return "ProjectDesignStageRedrafting"
	case ProjectDesignStageCommitted:
		return "ProjectDesignStageCommitted"
	case ProjectDesignStageWithdrawn:
		return "ProjectDesignStageWithdrawn"
	case ProjectDesignStageRefused:
		return "ProjectDesignStageRefused"
	case ProjectDesignStageDraftFailed:
		return "ProjectDesignStageDraftFailed"
	default:
		return ""
	}
}
