// Code generated by cmd/modelgen from contract.schema.json; DO NOT EDIT.
// Edit the schema and re-run `make gen-models` instead.

package billingstate

import (
	"github.com/google/uuid"
	fwra "github.com/mixofreality-studio/archistrator-platform/framework-go/resourceaccess"
)

type Billing struct {
	ID            uuid.UUID    `json:"ID"`
	Version       Version      `json:"Version"`
	GatewayBound  bool         `json:"GatewayBound"`
	Registered    bool         `json:"Registered"`
	Terms         BillingTerms `json:"Terms"`
	PayoutAccount string       `json:"PayoutAccount"`
}

type BillingOutcome struct {
	Net       Money            `json:"Net"`
	Directive RoutingDirective `json:"Directive"`
	Escalated bool             `json:"Escalated"`
}

type BillingTerms struct {
	RevenueShareKind int64 `json:"RevenueShareKind"`
	ComputeCostKind  int64 `json:"ComputeCostKind"`
	ScheduleKind     int64 `json:"ScheduleKind"`
	BillingKind      int64 `json:"BillingKind"`
}

type CustomerProfile struct {
	PayoutAccountRef string `json:"PayoutAccountRef"`
}

type CustomerSummary struct {
	ID               uuid.UUID `json:"ID"`
	PauseNotWithdraw bool      `json:"PauseNotWithdraw"`
}

type DelinquencyScope struct {
	ProjectID string `json:"ProjectID"`
}

type GatewayBinding struct {
	ConnectedAccountID string `json:"ConnectedAccountID"`
}

type Money struct {
	MinorUnits int64  `json:"MinorUnits"`
	Currency   string `json:"Currency"`
}

type RoutingDirective int

const (
	RoutingNoAction RoutingDirective = 0
	RoutingPayout   RoutingDirective = 1
	RoutingCharge   RoutingDirective = 2
)

type Version uint64

// BillingStateAccess is the generated service-contract interface for this component.
type BillingStateAccess interface {
	BindGatewayLive(rc fwra.Context, customerID uuid.UUID, expectedVersion Version, binding GatewayBinding, idempotencyKey fwra.IdempotencyKey) (Version, error)
	ReadPersistentlyDelinquentCustomers(rc fwra.Context, scope DelinquencyScope) ([]CustomerSummary, error)
	ReadBilling(rc fwra.Context, customerID uuid.UUID) (Billing, error)
	RegisterCustomer(rc fwra.Context, customerID uuid.UUID, expectedVersion Version, profile CustomerProfile, idempotencyKey fwra.IdempotencyKey) (Version, error)
	ResettleCycle(rc fwra.Context, customerID uuid.UUID, expectedVersion Version, cycle string, correction BillingOutcome, idempotencyKey fwra.IdempotencyKey) (Version, error)
	SettleCycle(rc fwra.Context, customerID uuid.UUID, expectedVersion Version, cycle string, outcome BillingOutcome, idempotencyKey fwra.IdempotencyKey) (Version, error)
}

// stubBillingStateAccess is the generated not-implemented BillingStateAccess. The component is contracted
// but not yet built, so every method returns a not-implemented error; the bodies
// are replaced when the component is constructed.
type stubBillingStateAccess struct{}

// NewBillingStateAccess returns the not-implemented BillingStateAccess. It takes no arguments
// (the component has no infrastructure binding yet).
func NewBillingStateAccess() BillingStateAccess { return &stubBillingStateAccess{} }

var _ BillingStateAccess = (*stubBillingStateAccess)(nil)

func (*stubBillingStateAccess) BindGatewayLive(_ fwra.Context, _ uuid.UUID, _ Version, _ GatewayBinding, _ fwra.IdempotencyKey) (Version, error) {
	var zero Version
	return zero, fwra.New(fwra.Unknown, "not implemented")
}

func (*stubBillingStateAccess) ReadPersistentlyDelinquentCustomers(_ fwra.Context, _ DelinquencyScope) ([]CustomerSummary, error) {
	var zero []CustomerSummary
	return zero, fwra.New(fwra.Unknown, "not implemented")
}

func (*stubBillingStateAccess) ReadBilling(_ fwra.Context, _ uuid.UUID) (Billing, error) {
	var zero Billing
	return zero, fwra.New(fwra.Unknown, "not implemented")
}

func (*stubBillingStateAccess) RegisterCustomer(_ fwra.Context, _ uuid.UUID, _ Version, _ CustomerProfile, _ fwra.IdempotencyKey) (Version, error) {
	var zero Version
	return zero, fwra.New(fwra.Unknown, "not implemented")
}

func (*stubBillingStateAccess) ResettleCycle(_ fwra.Context, _ uuid.UUID, _ Version, _ string, _ BillingOutcome, _ fwra.IdempotencyKey) (Version, error) {
	var zero Version
	return zero, fwra.New(fwra.Unknown, "not implemented")
}

func (*stubBillingStateAccess) SettleCycle(_ fwra.Context, _ uuid.UUID, _ Version, _ string, _ BillingOutcome, _ fwra.IdempotencyKey) (Version, error) {
	var zero Version
	return zero, fwra.New(fwra.Unknown, "not implemented")
}
