// Code generated by cmd/modelgen from the service-contract interface; DO NOT EDIT.
// Edit project.json's `interface` and re-run `make gen-fakes` instead.

package projectstatefake

import (
	fwra "github.com/mixofreality-studio/archistrator-platform/framework-go/resourceaccess"
	"github.com/mixofreality-studio/archistrator/server/internal/resourceaccess/projectstate"
)

// FakeConstructionTransitionAccess is a generated test double for projectstate.ConstructionTransitionAccess: set the Fn field(s)
// a test needs; calling a method whose Fn is unset panics.
type FakeConstructionTransitionAccess struct {
	RecordChangeReviewedFn          func(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, activityID string, cred projectstate.RepoCredential, idempotencyKey fwra.IdempotencyKey) (projectstate.Version, error)
	RecordActivityExitedFn          func(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, activityID string, outcome projectstate.ActivityOutcome, cred projectstate.RepoCredential, idempotencyKey fwra.IdempotencyKey) (projectstate.Version, error)
	RecordActivityFailedFn          func(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, activityID string, reason projectstate.FailureReason, detail string, cred projectstate.RepoCredential, idempotencyKey fwra.IdempotencyKey) (projectstate.Version, error)
	RecordOperatorPausedFn          func(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, reason string, cred projectstate.RepoCredential, idempotencyKey fwra.IdempotencyKey) (projectstate.Version, error)
	RecordReviewPolicyFn            func(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, policy projectstate.ReviewPolicy, cred projectstate.RepoCredential, idempotencyKey fwra.IdempotencyKey) (projectstate.Version, error)
	RecordPhaseStartedFn            func(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, activityID string, phase projectstate.ActivityMethodPhase, cred projectstate.RepoCredential, idempotencyKey fwra.IdempotencyKey) (projectstate.Version, error)
	RecordPhaseCompletedFn          func(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, activityID string, phase projectstate.ActivityMethodPhase, artifactRef string, cred projectstate.RepoCredential, idempotencyKey fwra.IdempotencyKey) (projectstate.Version, error)
	RecordServiceContractProducedFn func(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, component string, contract projectstate.ServiceContract, cred projectstate.RepoCredential, idempotencyKey fwra.IdempotencyKey) (projectstate.Version, error)
	RecordPhaseArtifactProducedFn   func(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, activityID string, mapKey string, payload projectstate.PhaseArtifactPayload, cred projectstate.RepoCredential, idempotencyKey fwra.IdempotencyKey) (projectstate.Version, error)
}

func (f *FakeConstructionTransitionAccess) RecordChangeReviewed(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, activityID string, cred projectstate.RepoCredential, idempotencyKey fwra.IdempotencyKey) (projectstate.Version, error) {
	if f.RecordChangeReviewedFn == nil {
		panic("FakeConstructionTransitionAccess.RecordChangeReviewedFn not set")
	}
	return f.RecordChangeReviewedFn(rc, projectID, expectedVersion, activityID, cred, idempotencyKey)
}

func (f *FakeConstructionTransitionAccess) RecordActivityExited(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, activityID string, outcome projectstate.ActivityOutcome, cred projectstate.RepoCredential, idempotencyKey fwra.IdempotencyKey) (projectstate.Version, error) {
	if f.RecordActivityExitedFn == nil {
		panic("FakeConstructionTransitionAccess.RecordActivityExitedFn not set")
	}
	return f.RecordActivityExitedFn(rc, projectID, expectedVersion, activityID, outcome, cred, idempotencyKey)
}

func (f *FakeConstructionTransitionAccess) RecordActivityFailed(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, activityID string, reason projectstate.FailureReason, detail string, cred projectstate.RepoCredential, idempotencyKey fwra.IdempotencyKey) (projectstate.Version, error) {
	if f.RecordActivityFailedFn == nil {
		panic("FakeConstructionTransitionAccess.RecordActivityFailedFn not set")
	}
	return f.RecordActivityFailedFn(rc, projectID, expectedVersion, activityID, reason, detail, cred, idempotencyKey)
}

func (f *FakeConstructionTransitionAccess) RecordOperatorPaused(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, reason string, cred projectstate.RepoCredential, idempotencyKey fwra.IdempotencyKey) (projectstate.Version, error) {
	if f.RecordOperatorPausedFn == nil {
		panic("FakeConstructionTransitionAccess.RecordOperatorPausedFn not set")
	}
	return f.RecordOperatorPausedFn(rc, projectID, expectedVersion, reason, cred, idempotencyKey)
}

func (f *FakeConstructionTransitionAccess) RecordReviewPolicy(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, policy projectstate.ReviewPolicy, cred projectstate.RepoCredential, idempotencyKey fwra.IdempotencyKey) (projectstate.Version, error) {
	if f.RecordReviewPolicyFn == nil {
		panic("FakeConstructionTransitionAccess.RecordReviewPolicyFn not set")
	}
	return f.RecordReviewPolicyFn(rc, projectID, expectedVersion, policy, cred, idempotencyKey)
}

func (f *FakeConstructionTransitionAccess) RecordPhaseStarted(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, activityID string, phase projectstate.ActivityMethodPhase, cred projectstate.RepoCredential, idempotencyKey fwra.IdempotencyKey) (projectstate.Version, error) {
	if f.RecordPhaseStartedFn == nil {
		panic("FakeConstructionTransitionAccess.RecordPhaseStartedFn not set")
	}
	return f.RecordPhaseStartedFn(rc, projectID, expectedVersion, activityID, phase, cred, idempotencyKey)
}

func (f *FakeConstructionTransitionAccess) RecordPhaseCompleted(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, activityID string, phase projectstate.ActivityMethodPhase, artifactRef string, cred projectstate.RepoCredential, idempotencyKey fwra.IdempotencyKey) (projectstate.Version, error) {
	if f.RecordPhaseCompletedFn == nil {
		panic("FakeConstructionTransitionAccess.RecordPhaseCompletedFn not set")
	}
	return f.RecordPhaseCompletedFn(rc, projectID, expectedVersion, activityID, phase, artifactRef, cred, idempotencyKey)
}

func (f *FakeConstructionTransitionAccess) RecordServiceContractProduced(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, component string, contract projectstate.ServiceContract, cred projectstate.RepoCredential, idempotencyKey fwra.IdempotencyKey) (projectstate.Version, error) {
	if f.RecordServiceContractProducedFn == nil {
		panic("FakeConstructionTransitionAccess.RecordServiceContractProducedFn not set")
	}
	return f.RecordServiceContractProducedFn(rc, projectID, expectedVersion, component, contract, cred, idempotencyKey)
}

func (f *FakeConstructionTransitionAccess) RecordPhaseArtifactProduced(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, activityID string, mapKey string, payload projectstate.PhaseArtifactPayload, cred projectstate.RepoCredential, idempotencyKey fwra.IdempotencyKey) (projectstate.Version, error) {
	if f.RecordPhaseArtifactProducedFn == nil {
		panic("FakeConstructionTransitionAccess.RecordPhaseArtifactProducedFn not set")
	}
	return f.RecordPhaseArtifactProducedFn(rc, projectID, expectedVersion, activityID, mapKey, payload, cred, idempotencyKey)
}

var _ projectstate.ConstructionTransitionAccess = (*FakeConstructionTransitionAccess)(nil)

// FakeDesignSessionAccess is a generated test double for projectstate.DesignSessionAccess: set the Fn field(s)
// a test needs; calling a method whose Fn is unset panics.
type FakeDesignSessionAccess struct {
	ReadProjectOnBranchFn                func(rc fwra.Context, projectID projectstate.ProjectID, branch string) (projectstate.ProjectEnvelope, error)
	StageArtifactForReviewOnBranchFn     func(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, branch string, model projectstate.ModelEnvelope, idempotencyKey fwra.IdempotencyKey) (projectstate.Version, error)
	CommitArtifactWithProvenanceFn       func(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, kind projectstate.ArtifactKind, approvedBy string, draftedBy string) (projectstate.Version, error)
	RejectArtifactOnBranchWithCommentsFn func(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, branch string, kind projectstate.ArtifactKind, notes string, round int64, comments []projectstate.ReviewComment, idempotencyKey fwra.IdempotencyKey) (projectstate.Version, error)
	WithdrawArtifactOnBranchFn           func(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, branch string, kind projectstate.ArtifactKind, notes string, idempotencyKey fwra.IdempotencyKey) (projectstate.Version, error)
	ReconcileBranchFromMainFn            func(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, branch string, kind projectstate.ArtifactKind, idempotencyKey fwra.IdempotencyKey) (projectstate.Version, error)
	SetReviewCommentStatusOnBranchFn     func(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, branch string, kind projectstate.ArtifactKind, commentID string, status string, idempotencyKey fwra.IdempotencyKey) (projectstate.Version, error)
	SeedReviewCommentsOnBranchFn         func(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, branch string, kind projectstate.ArtifactKind, round int64, comments []projectstate.ReviewComment, idempotencyKey fwra.IdempotencyKey) (projectstate.Version, error)
}

func (f *FakeDesignSessionAccess) ReadProjectOnBranch(rc fwra.Context, projectID projectstate.ProjectID, branch string) (projectstate.ProjectEnvelope, error) {
	if f.ReadProjectOnBranchFn == nil {
		panic("FakeDesignSessionAccess.ReadProjectOnBranchFn not set")
	}
	return f.ReadProjectOnBranchFn(rc, projectID, branch)
}

func (f *FakeDesignSessionAccess) StageArtifactForReviewOnBranch(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, branch string, model projectstate.ModelEnvelope, idempotencyKey fwra.IdempotencyKey) (projectstate.Version, error) {
	if f.StageArtifactForReviewOnBranchFn == nil {
		panic("FakeDesignSessionAccess.StageArtifactForReviewOnBranchFn not set")
	}
	return f.StageArtifactForReviewOnBranchFn(rc, projectID, expectedVersion, branch, model, idempotencyKey)
}

func (f *FakeDesignSessionAccess) CommitArtifactWithProvenance(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, kind projectstate.ArtifactKind, approvedBy string, draftedBy string) (projectstate.Version, error) {
	if f.CommitArtifactWithProvenanceFn == nil {
		panic("FakeDesignSessionAccess.CommitArtifactWithProvenanceFn not set")
	}
	return f.CommitArtifactWithProvenanceFn(rc, projectID, expectedVersion, kind, approvedBy, draftedBy)
}

func (f *FakeDesignSessionAccess) RejectArtifactOnBranchWithComments(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, branch string, kind projectstate.ArtifactKind, notes string, round int64, comments []projectstate.ReviewComment, idempotencyKey fwra.IdempotencyKey) (projectstate.Version, error) {
	if f.RejectArtifactOnBranchWithCommentsFn == nil {
		panic("FakeDesignSessionAccess.RejectArtifactOnBranchWithCommentsFn not set")
	}
	return f.RejectArtifactOnBranchWithCommentsFn(rc, projectID, expectedVersion, branch, kind, notes, round, comments, idempotencyKey)
}

func (f *FakeDesignSessionAccess) WithdrawArtifactOnBranch(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, branch string, kind projectstate.ArtifactKind, notes string, idempotencyKey fwra.IdempotencyKey) (projectstate.Version, error) {
	if f.WithdrawArtifactOnBranchFn == nil {
		panic("FakeDesignSessionAccess.WithdrawArtifactOnBranchFn not set")
	}
	return f.WithdrawArtifactOnBranchFn(rc, projectID, expectedVersion, branch, kind, notes, idempotencyKey)
}

func (f *FakeDesignSessionAccess) ReconcileBranchFromMain(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, branch string, kind projectstate.ArtifactKind, idempotencyKey fwra.IdempotencyKey) (projectstate.Version, error) {
	if f.ReconcileBranchFromMainFn == nil {
		panic("FakeDesignSessionAccess.ReconcileBranchFromMainFn not set")
	}
	return f.ReconcileBranchFromMainFn(rc, projectID, expectedVersion, branch, kind, idempotencyKey)
}

func (f *FakeDesignSessionAccess) SetReviewCommentStatusOnBranch(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, branch string, kind projectstate.ArtifactKind, commentID string, status string, idempotencyKey fwra.IdempotencyKey) (projectstate.Version, error) {
	if f.SetReviewCommentStatusOnBranchFn == nil {
		panic("FakeDesignSessionAccess.SetReviewCommentStatusOnBranchFn not set")
	}
	return f.SetReviewCommentStatusOnBranchFn(rc, projectID, expectedVersion, branch, kind, commentID, status, idempotencyKey)
}

func (f *FakeDesignSessionAccess) SeedReviewCommentsOnBranch(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, branch string, kind projectstate.ArtifactKind, round int64, comments []projectstate.ReviewComment, idempotencyKey fwra.IdempotencyKey) (projectstate.Version, error) {
	if f.SeedReviewCommentsOnBranchFn == nil {
		panic("FakeDesignSessionAccess.SeedReviewCommentsOnBranchFn not set")
	}
	return f.SeedReviewCommentsOnBranchFn(rc, projectID, expectedVersion, branch, kind, round, comments, idempotencyKey)
}

var _ projectstate.DesignSessionAccess = (*FakeDesignSessionAccess)(nil)

// FakeGitActivityStatusAccess is a generated test double for projectstate.GitActivityStatusAccess: set the Fn field(s)
// a test needs; calling a method whose Fn is unset panics.
type FakeGitActivityStatusAccess struct {
	RecordActivityBranchOpenedFn func(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, activityID string, branch string, branchRef string, prRef string, crLabel string, isRevert bool, cred projectstate.RepoCredential, idempotencyKey fwra.IdempotencyKey) (projectstate.Version, error)
	RecordActivityCIObservedFn   func(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, activityID string, ci projectstate.CICheckState, cred projectstate.RepoCredential, idempotencyKey fwra.IdempotencyKey) (projectstate.Version, error)
	RecordActivityArchApprovedFn func(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, activityID string, cred projectstate.RepoCredential, idempotencyKey fwra.IdempotencyKey) (projectstate.Version, error)
	RecordActivityMergedFn       func(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, activityID string, cred projectstate.RepoCredential, idempotencyKey fwra.IdempotencyKey) (projectstate.Version, error)
	RecordActivityStartedFn      func(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, activityID string, typ projectstate.ActivityType, variant projectstate.TestingVariant, cred projectstate.RepoCredential, idempotencyKey fwra.IdempotencyKey) (projectstate.Version, error)
	RecordActivityCompletedFn    func(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, activityID string, cred projectstate.RepoCredential, idempotencyKey fwra.IdempotencyKey) (projectstate.Version, error)
}

func (f *FakeGitActivityStatusAccess) RecordActivityBranchOpened(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, activityID string, branch string, branchRef string, prRef string, crLabel string, isRevert bool, cred projectstate.RepoCredential, idempotencyKey fwra.IdempotencyKey) (projectstate.Version, error) {
	if f.RecordActivityBranchOpenedFn == nil {
		panic("FakeGitActivityStatusAccess.RecordActivityBranchOpenedFn not set")
	}
	return f.RecordActivityBranchOpenedFn(rc, projectID, expectedVersion, activityID, branch, branchRef, prRef, crLabel, isRevert, cred, idempotencyKey)
}

func (f *FakeGitActivityStatusAccess) RecordActivityCIObserved(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, activityID string, ci projectstate.CICheckState, cred projectstate.RepoCredential, idempotencyKey fwra.IdempotencyKey) (projectstate.Version, error) {
	if f.RecordActivityCIObservedFn == nil {
		panic("FakeGitActivityStatusAccess.RecordActivityCIObservedFn not set")
	}
	return f.RecordActivityCIObservedFn(rc, projectID, expectedVersion, activityID, ci, cred, idempotencyKey)
}

func (f *FakeGitActivityStatusAccess) RecordActivityArchApproved(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, activityID string, cred projectstate.RepoCredential, idempotencyKey fwra.IdempotencyKey) (projectstate.Version, error) {
	if f.RecordActivityArchApprovedFn == nil {
		panic("FakeGitActivityStatusAccess.RecordActivityArchApprovedFn not set")
	}
	return f.RecordActivityArchApprovedFn(rc, projectID, expectedVersion, activityID, cred, idempotencyKey)
}

func (f *FakeGitActivityStatusAccess) RecordActivityMerged(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, activityID string, cred projectstate.RepoCredential, idempotencyKey fwra.IdempotencyKey) (projectstate.Version, error) {
	if f.RecordActivityMergedFn == nil {
		panic("FakeGitActivityStatusAccess.RecordActivityMergedFn not set")
	}
	return f.RecordActivityMergedFn(rc, projectID, expectedVersion, activityID, cred, idempotencyKey)
}

func (f *FakeGitActivityStatusAccess) RecordActivityStarted(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, activityID string, typ projectstate.ActivityType, variant projectstate.TestingVariant, cred projectstate.RepoCredential, idempotencyKey fwra.IdempotencyKey) (projectstate.Version, error) {
	if f.RecordActivityStartedFn == nil {
		panic("FakeGitActivityStatusAccess.RecordActivityStartedFn not set")
	}
	return f.RecordActivityStartedFn(rc, projectID, expectedVersion, activityID, typ, variant, cred, idempotencyKey)
}

func (f *FakeGitActivityStatusAccess) RecordActivityCompleted(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, activityID string, cred projectstate.RepoCredential, idempotencyKey fwra.IdempotencyKey) (projectstate.Version, error) {
	if f.RecordActivityCompletedFn == nil {
		panic("FakeGitActivityStatusAccess.RecordActivityCompletedFn not set")
	}
	return f.RecordActivityCompletedFn(rc, projectID, expectedVersion, activityID, cred, idempotencyKey)
}

var _ projectstate.GitActivityStatusAccess = (*FakeGitActivityStatusAccess)(nil)

// FakeProjectStateAccess is a generated test double for projectstate.ProjectStateAccess: set the Fn field(s)
// a test needs; calling a method whose Fn is unset panics.
type FakeProjectStateAccess struct {
	AcknowledgeStaleBasisFn func(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, kind projectstate.ArtifactKind, note string, idempotencyKey fwra.IdempotencyKey) (projectstate.Version, error)
	AdvancePhaseFn          func(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version) (projectstate.Version, error)
	CommitArtifactFn        func(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, kind projectstate.ArtifactKind) (projectstate.Version, error)
	CreateProjectFn         func(rc fwra.Context, projectID projectstate.ProjectID, owner projectstate.OwnerScope, name string) (projectstate.Version, error)
	ListProjectsFn          func(rc fwra.Context, owner projectstate.OwnerScope) ([]projectstate.ProjectSummary, error)
	ReadProjectFn           func(rc fwra.Context, projectID projectstate.ProjectID) (projectstate.Project, error)
	ReadProjectVersionFn    func(rc fwra.Context, projectID projectstate.ProjectID) (projectstate.Version, error)
	SetOperatingModelFn     func(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, model projectstate.OperatingModel) (projectstate.Version, error)
	SetResearchInputFn      func(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, research projectstate.ResearchInput) (projectstate.Version, error)
}

func (f *FakeProjectStateAccess) AcknowledgeStaleBasis(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, kind projectstate.ArtifactKind, note string, idempotencyKey fwra.IdempotencyKey) (projectstate.Version, error) {
	if f.AcknowledgeStaleBasisFn == nil {
		panic("FakeProjectStateAccess.AcknowledgeStaleBasisFn not set")
	}
	return f.AcknowledgeStaleBasisFn(rc, projectID, expectedVersion, kind, note, idempotencyKey)
}

func (f *FakeProjectStateAccess) AdvancePhase(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version) (projectstate.Version, error) {
	if f.AdvancePhaseFn == nil {
		panic("FakeProjectStateAccess.AdvancePhaseFn not set")
	}
	return f.AdvancePhaseFn(rc, projectID, expectedVersion)
}

func (f *FakeProjectStateAccess) CommitArtifact(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, kind projectstate.ArtifactKind) (projectstate.Version, error) {
	if f.CommitArtifactFn == nil {
		panic("FakeProjectStateAccess.CommitArtifactFn not set")
	}
	return f.CommitArtifactFn(rc, projectID, expectedVersion, kind)
}

func (f *FakeProjectStateAccess) CreateProject(rc fwra.Context, projectID projectstate.ProjectID, owner projectstate.OwnerScope, name string) (projectstate.Version, error) {
	if f.CreateProjectFn == nil {
		panic("FakeProjectStateAccess.CreateProjectFn not set")
	}
	return f.CreateProjectFn(rc, projectID, owner, name)
}

func (f *FakeProjectStateAccess) ListProjects(rc fwra.Context, owner projectstate.OwnerScope) ([]projectstate.ProjectSummary, error) {
	if f.ListProjectsFn == nil {
		panic("FakeProjectStateAccess.ListProjectsFn not set")
	}
	return f.ListProjectsFn(rc, owner)
}

func (f *FakeProjectStateAccess) ReadProject(rc fwra.Context, projectID projectstate.ProjectID) (projectstate.Project, error) {
	if f.ReadProjectFn == nil {
		panic("FakeProjectStateAccess.ReadProjectFn not set")
	}
	return f.ReadProjectFn(rc, projectID)
}

func (f *FakeProjectStateAccess) ReadProjectVersion(rc fwra.Context, projectID projectstate.ProjectID) (projectstate.Version, error) {
	if f.ReadProjectVersionFn == nil {
		panic("FakeProjectStateAccess.ReadProjectVersionFn not set")
	}
	return f.ReadProjectVersionFn(rc, projectID)
}

func (f *FakeProjectStateAccess) SetOperatingModel(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, model projectstate.OperatingModel) (projectstate.Version, error) {
	if f.SetOperatingModelFn == nil {
		panic("FakeProjectStateAccess.SetOperatingModelFn not set")
	}
	return f.SetOperatingModelFn(rc, projectID, expectedVersion, model)
}

func (f *FakeProjectStateAccess) SetResearchInput(rc fwra.Context, projectID projectstate.ProjectID, expectedVersion projectstate.Version, research projectstate.ResearchInput) (projectstate.Version, error) {
	if f.SetResearchInputFn == nil {
		panic("FakeProjectStateAccess.SetResearchInputFn not set")
	}
	return f.SetResearchInputFn(rc, projectID, expectedVersion, research)
}

var _ projectstate.ProjectStateAccess = (*FakeProjectStateAccess)(nil)
