// Code generated by cmd/modelgen from contract.schema.json; DO NOT EDIT.
// Edit the schema and re-run `make gen-models` instead.

package usagelog

import (
	"github.com/google/uuid"
	fwra "github.com/mixofreality-studio/archistrator-platform/framework-go/resourceaccess"
	"time"
)

type ComputeUnits struct {
	Amount float64 `json:"Amount"`
	Unit   string  `json:"Unit"`
}

type CycleID string

type EntryRef string

type RuntimeEventID string

type UsageEvent struct {
	CustomerID     uuid.UUID      `json:"CustomerID"`
	OperatedAppID  uuid.UUID      `json:"OperatedAppID"`
	CycleID        CycleID        `json:"CycleID"`
	Units          ComputeUnits   `json:"Units"`
	RuntimeEventID RuntimeEventID `json:"RuntimeEventID"`
	RawMeter       []byte         `json:"RawMeter"`
	WindowStart    time.Time      `json:"WindowStart"`
	WindowEnd      time.Time      `json:"WindowEnd"`
	OccurredAt     time.Time      `json:"OccurredAt"`
	RecordedAt     time.Time      `json:"RecordedAt"`
	Ref            EntryRef       `json:"Ref"`
}

type UsageRangeQuery struct {
	CustomerID    uuid.UUID  `json:"CustomerID"`
	CycleID       CycleID    `json:"CycleID"`
	OperatedAppID *uuid.UUID `json:"OperatedAppID,omitempty"`
}

// UsageAccess is the generated service-contract interface for this component.
type UsageAccess interface {
	ReadRange(rc fwra.Context, query UsageRangeQuery) ([]UsageEvent, error)
	RecordComputeUsage(rc fwra.Context, events []UsageEvent) ([]EntryRef, error)
	RecordFinalUsage(rc fwra.Context, events []UsageEvent) ([]EntryRef, error)
}
