// Code generated by temporalgen. DO NOT EDIT.

package operations

import (
	"go.temporal.io/sdk/activity"
	"go.temporal.io/sdk/worker"
	"go.temporal.io/sdk/workflow"
)

// TaskQueue is the manager's Temporal task queue (derived from the contract
// interface name).
const TaskQueue = "operations"

// genWorkerManifest is what the hand-written manager supplies to
// RegisterWorker: the workflow functions (codegen cannot know them), the
// invoker options hook, and the genActivities dep threading.
type genWorkerManifest struct {
	Workflows       []genRegisteredWorkflow
	ActivityOptions func(activityName string) (workflow.ActivityOptions, bool)
	Activities      genActivities
}

type genRegisteredWorkflow struct {
	Name string
	Fn   any
}

// RegisterWorker registers every workflow + generated activity on w.
// Forgetting a generated activity is impossible; workflows are exactly what
// the manifest declares.
func RegisterWorker(w worker.Worker, mf genWorkerManifest) {
	for _, wf := range mf.Workflows {
		w.RegisterWorkflowWithOptions(wf.Fn, workflow.RegisterOptions{Name: wf.Name})
	}
	acts := &mf.Activities
	w.RegisterActivityWithOptions(acts.ArtifactRetrieveConstructionOutput, activity.RegisterOptions{Name: "artifactAccess.retrieveConstructionOutput"})
	w.RegisterActivityWithOptions(acts.ArtifactRetrieveOutputTree, activity.RegisterOptions{Name: "artifactAccess.retrieveOutputTree"})
	w.RegisterActivityWithOptions(acts.ArtifactStoreConstructionOutput, activity.RegisterOptions{Name: "artifactAccess.storeConstructionOutput"})
	w.RegisterActivityWithOptions(acts.MessageBusDeliverSignal, activity.RegisterOptions{Name: "messageBus.deliverSignal"})
	w.RegisterActivityWithOptions(acts.MessageBusRegisterSchedule, activity.RegisterOptions{Name: "messageBus.registerSchedule"})
	w.RegisterActivityWithOptions(acts.OperatedRuntimeGetApplicationHealth, activity.RegisterOptions{Name: "operatedRuntimeAccess.getApplicationHealth"})
	w.RegisterActivityWithOptions(acts.OperatedRuntimeGetSloStatus, activity.RegisterOptions{Name: "operatedRuntimeAccess.getSloStatus"})
	w.RegisterActivityWithOptions(acts.OperatedRuntimePublishDesiredState, activity.RegisterOptions{Name: "operatedRuntimeAccess.publishDesiredState"})
	w.RegisterActivityWithOptions(acts.OperatedRuntimeReadComputeAttribution, activity.RegisterOptions{Name: "operatedRuntimeAccess.readComputeAttribution"})
	w.RegisterActivityWithOptions(acts.OperatedRuntimeWirePaymentConfig, activity.RegisterOptions{Name: "operatedRuntimeAccess.wirePaymentConfig"})
	w.RegisterActivityWithOptions(acts.OperatedRuntimeWithdraw, activity.RegisterOptions{Name: "operatedRuntimeAccess.withdraw"})
	w.RegisterActivityWithOptions(acts.OperatedSystemStatePublishDesiredState, activity.RegisterOptions{Name: "operatedSystemStateAccess.publishDesiredState"})
	w.RegisterActivityWithOptions(acts.OperatedSystemStateReadInFlightOperatedApps, activity.RegisterOptions{Name: "operatedSystemStateAccess.readInFlightOperatedApps"})
	w.RegisterActivityWithOptions(acts.OperatedSystemStateReadOperatedSystem, activity.RegisterOptions{Name: "operatedSystemStateAccess.readOperatedSystem"})
	w.RegisterActivityWithOptions(acts.OperatedSystemStateRecordDelinquencyAction, activity.RegisterOptions{Name: "operatedSystemStateAccess.recordDelinquencyAction"})
	w.RegisterActivityWithOptions(acts.OperatedSystemStateRecordRuntimeStatusChange, activity.RegisterOptions{Name: "operatedSystemStateAccess.recordRuntimeStatusChange"})
	w.RegisterActivityWithOptions(acts.OperatedSystemStateWithdrawSystem, activity.RegisterOptions{Name: "operatedSystemStateAccess.withdrawSystem"})
	w.RegisterActivityWithOptions(acts.UsageReadRange, activity.RegisterOptions{Name: "usageAccess.readRange"})
	w.RegisterActivityWithOptions(acts.UsageRecordComputeUsage, activity.RegisterOptions{Name: "usageAccess.recordComputeUsage"})
	w.RegisterActivityWithOptions(acts.UsageRecordFinalUsage, activity.RegisterOptions{Name: "usageAccess.recordFinalUsage"})
}
