// Code generated by cmd/modelgen from the service-contract interface; DO NOT EDIT.
// Edit project.json's `interface` and re-run `make gen-fakes` instead.

package autoscalerfake

import (
	fweng "github.com/mixofreality-studio/archistrator-platform/framework-go/engine"
	"github.com/mixofreality-studio/archistrator/server/internal/engine/autoscaler"
)

// FakeAutoscalerEngine is a generated test double for autoscaler.AutoscalerEngine: set the Fn field(s)
// a test needs; calling a method whose Fn is unset panics.
type FakeAutoscalerEngine struct {
	ProposeDesiredStateFn func(rc fweng.Context, telemetry autoscaler.Telemetry, currentDesired autoscaler.DesiredState, policy autoscaler.AutoscalerPolicy, infrastructureKind autoscaler.InfrastructureKind) (autoscaler.Decision, error)
}

func (f *FakeAutoscalerEngine) ProposeDesiredState(rc fweng.Context, telemetry autoscaler.Telemetry, currentDesired autoscaler.DesiredState, policy autoscaler.AutoscalerPolicy, infrastructureKind autoscaler.InfrastructureKind) (autoscaler.Decision, error) {
	if f.ProposeDesiredStateFn == nil {
		panic("FakeAutoscalerEngine.ProposeDesiredStateFn not set")
	}
	return f.ProposeDesiredStateFn(rc, telemetry, currentDesired, policy, infrastructureKind)
}

var _ autoscaler.AutoscalerEngine = (*FakeAutoscalerEngine)(nil)
