// Code generated by cmd/modelgen from contract.schema.json; DO NOT EDIT.
// Edit the schema and re-run `make gen-models` instead.

package review

import (
	fweng "github.com/mixofreality-studio/archistrator-platform/framework-go/engine"
)

type ReviewChange struct {
	ActivityID     string `json:"ActivityID"`
	ComponentID    string `json:"ComponentID"`
	ContentAddress string `json:"ContentAddress"`
}

type ReviewSet struct {
	Reviewers []Reviewer `json:"Reviewers"`
}

type Reviewer struct {
	MayAmend          bool   `json:"MayAmend"`
	Perspective       string `json:"Perspective"`
	ReferenceArtifact string `json:"ReferenceArtifact"`
	Role              string `json:"Role"`
}

// ReviewEngine is the generated service-contract interface for this component.
type ReviewEngine interface {
	ProposeReviews(rc fweng.Context, change ReviewChange, componentID string, artifactKind string, architectureGraph string, contracts []string) (ReviewSet, error)
}

// ReviewEngineImpl is the generated concrete ReviewEngine. Engines are pure (no
// dependencies), so the impl carries no fields and the constructor takes none.
// The interface methods are hand-written on this struct.
type ReviewEngineImpl struct{}

// NewReviewEngine returns the production ReviewEngine.
func NewReviewEngine() ReviewEngine { return ReviewEngineImpl{} }

var _ ReviewEngine = ReviewEngineImpl{}
