// Code generated by cmd/modelgen from the service-contract interface; DO NOT EDIT.
// Edit project.json's `interface` and re-run `make gen-fakes` instead.

package usagefake

import (
	fwra "github.com/mixofreality-studio/archistrator-platform/framework-go/resourceaccess"
	"github.com/mixofreality-studio/archistrator/server/internal/resourceaccess/usage"
)

// FakeUsageAccess is a generated test double for usage.UsageAccess: set the Fn field(s)
// a test needs; calling a method whose Fn is unset panics.
type FakeUsageAccess struct {
	ReadRangeFn          func(rc fwra.Context, query usage.UsageRangeQuery) ([]usage.UsageEvent, error)
	RecordComputeUsageFn func(rc fwra.Context, events []usage.UsageEvent) ([]usage.EntryRef, error)
	RecordFinalUsageFn   func(rc fwra.Context, events []usage.UsageEvent) ([]usage.EntryRef, error)
}

func (f *FakeUsageAccess) ReadRange(rc fwra.Context, query usage.UsageRangeQuery) ([]usage.UsageEvent, error) {
	if f.ReadRangeFn == nil {
		panic("FakeUsageAccess.ReadRangeFn not set")
	}
	return f.ReadRangeFn(rc, query)
}

func (f *FakeUsageAccess) RecordComputeUsage(rc fwra.Context, events []usage.UsageEvent) ([]usage.EntryRef, error) {
	if f.RecordComputeUsageFn == nil {
		panic("FakeUsageAccess.RecordComputeUsageFn not set")
	}
	return f.RecordComputeUsageFn(rc, events)
}

func (f *FakeUsageAccess) RecordFinalUsage(rc fwra.Context, events []usage.UsageEvent) ([]usage.EntryRef, error) {
	if f.RecordFinalUsageFn == nil {
		panic("FakeUsageAccess.RecordFinalUsageFn not set")
	}
	return f.RecordFinalUsageFn(rc, events)
}

var _ usage.UsageAccess = (*FakeUsageAccess)(nil)
