// Code generated by cmd/modelgen from contract.schema.json; DO NOT EDIT.
// Edit the schema and re-run `make gen-models` instead.

package constructionpipeline

import (
	fwgithub "github.com/mixofreality-studio/archistrator-platform/framework-go-infrastructure-github"
	fwra "github.com/mixofreality-studio/archistrator-platform/framework-go/resourceaccess"
	"time"
)

type ArtifactRef string

type ConstructionActivityID string

type PipelineHandle string

type PipelineObservation struct {
	Handle     PipelineHandle    `json:"Handle"`
	Phase      PipelinePhase     `json:"Phase"`
	Steps      []StepObservation `json:"Steps"`
	FailedStep string            `json:"FailedStep"`
	Diagnostic string            `json:"Diagnostic"`
	StartedAt  time.Time         `json:"StartedAt"`
	FinishedAt *time.Time        `json:"FinishedAt,omitempty"`
}

type PipelinePhase int

const (
	PhasePending   PipelinePhase = 0
	PhaseRunning   PipelinePhase = 1
	PhaseSucceeded PipelinePhase = 2
	PhaseFailed    PipelinePhase = 3
	PhaseCancelled PipelinePhase = 4
)

type PipelineSpec struct {
	ProjectID      ProjectID              `json:"ProjectID"`
	ActivityID     ConstructionActivityID `json:"ActivityID"`
	Steps          []PipelineStep         `json:"Steps"`
	Edges          []StepDependency       `json:"Edges"`
	WorkspaceRef   ArtifactRef            `json:"WorkspaceRef"`
	DispatchInputs map[string]string      `json:"DispatchInputs"`
	TargetRepo     RepoTarget             `json:"TargetRepo"`
	WorkflowFile   string                 `json:"WorkflowFile"`
}

type PipelineStep struct {
	Name      string          `json:"Name"`
	Toolchain ToolchainRef    `json:"Toolchain"`
	Command   []string        `json:"Command"`
	Resources ResourceRequest `json:"Resources"`
	CacheKeys []string        `json:"CacheKeys"`
}

type ProjectID string

type RepoTarget struct {
	Owner string `json:"Owner"`
	Name  string `json:"Name"`
}

type ResourceRequest struct {
	CPUMillis int64 `json:"CPUMillis"`
	MemMiB    int64 `json:"MemMiB"`
	GPUs      int64 `json:"GPUs"`
}

type StepDependency struct {
	From string `json:"From"`
	To   string `json:"To"`
}

type StepObservation struct {
	Name    string      `json:"Name"`
	Outcome StepOutcome `json:"Outcome"`
}

type StepOutcome int

const (
	StepPending   StepOutcome = 0
	StepRunning   StepOutcome = 1
	StepSucceeded StepOutcome = 2
	StepFailed    StepOutcome = 3
	StepSkipped   StepOutcome = 4
)

type ToolchainRef string

// ConstructionPipelineAccess is the generated service-contract interface for this component.
type ConstructionPipelineAccess interface {
	CancelConstructionPipeline(rc fwra.Context, handle PipelineHandle) error
	ObserveConstructionPipeline(rc fwra.Context, handle PipelineHandle) (PipelineObservation, error)
	SubmitConstructionPipeline(rc fwra.Context, spec PipelineSpec) (PipelineHandle, error)
}

// NewGitHubActionsConstructionPipelineAccess constructs the GitHubActions-backed ConstructionPipelineAccess, delegating to the hand-written,
// unexported builder newGitHubActionsConstructionPipelineAccess in the RA package (which owns the stateful setup).
// The constructor returns the interface, so the concrete impl stays unexported.
func NewGitHubActionsConstructionPipelineAccess(app *fwgithub.AppClient, owner string, repo string, workflowFile string, ref string, installationID int64) (ConstructionPipelineAccess, error) {
	return newGitHubActionsConstructionPipelineAccess(app, owner, repo, workflowFile, ref, installationID)
}
