// Code generated by cmd/modelgen from the service-contract interface; DO NOT EDIT.
// Edit project.json's `interface` and re-run `make gen-fakes` instead.

package projectdesignfake

import (
	fwm "github.com/mixofreality-studio/archistrator-platform/framework-go/manager"
	"github.com/mixofreality-studio/archistrator/server/internal/manager/projectdesign"
)

// FakeProjectDesignManager is a generated test double for projectdesign.ProjectDesignManager: set the Fn field(s)
// a test needs; calling a method whose Fn is unset panics.
type FakeProjectDesignManager struct {
	AdvanceToConstructionFn   func(rc fwm.Context, projectID projectdesign.ProjectID, acknowledgeStale bool) (projectdesign.PhaseAdvanceResult, error)
	GetSessionStateFn         func(rc fwm.Context, projectID projectdesign.ProjectID, kind projectdesign.ArtifactKind) (projectdesign.SessionStateView, error)
	RequestArtifactDraftFn    func(rc fwm.Context, projectID projectdesign.ProjectID, kind projectdesign.ArtifactKind, feedback *projectdesign.ReviewFeedback) (projectdesign.SessionRef, error)
	RequestSDPCommitFn        func(rc fwm.Context, projectID projectdesign.ProjectID) (projectdesign.SessionRef, error)
	AskQuestionsFn            func(rc fwm.Context, projectID projectdesign.ProjectID, kind projectdesign.ArtifactKind, addressee string, questions []projectdesign.AnchoredComment) error
	AcknowledgeStaleBasisFn   func(rc fwm.Context, projectID projectdesign.ProjectID, kind projectdesign.ArtifactKind, note string) error
	SetReviewCommentStatusFn  func(rc fwm.Context, projectID projectdesign.ProjectID, kind projectdesign.ArtifactKind, commentID string, status string) error
	SubmitReviewDecisionFn    func(rc fwm.Context, projectID projectdesign.ProjectID, kind projectdesign.ArtifactKind, decision projectdesign.ReviewDecision, feedback *projectdesign.ReviewFeedback) error
	SubmitSDPDecisionFn       func(rc fwm.Context, projectID projectdesign.ProjectID, decision projectdesign.SDPDecision, optionID *projectdesign.OptionID, feedback *projectdesign.ReviewFeedback) error
	ListEpisodesForArtifactFn func(rc fwm.Context, projectID projectdesign.ProjectID, artifactKind projectdesign.ArtifactKind) ([]projectdesign.EpisodeRecordView, error)
	GetEpisodeTimelineFn      func(rc fwm.Context, projectID projectdesign.ProjectID, episodeID string) (projectdesign.EpisodeTimeline, error)
}

func (f *FakeProjectDesignManager) AdvanceToConstruction(rc fwm.Context, projectID projectdesign.ProjectID, acknowledgeStale bool) (projectdesign.PhaseAdvanceResult, error) {
	if f.AdvanceToConstructionFn == nil {
		panic("FakeProjectDesignManager.AdvanceToConstructionFn not set")
	}
	return f.AdvanceToConstructionFn(rc, projectID, acknowledgeStale)
}

func (f *FakeProjectDesignManager) GetSessionState(rc fwm.Context, projectID projectdesign.ProjectID, kind projectdesign.ArtifactKind) (projectdesign.SessionStateView, error) {
	if f.GetSessionStateFn == nil {
		panic("FakeProjectDesignManager.GetSessionStateFn not set")
	}
	return f.GetSessionStateFn(rc, projectID, kind)
}

func (f *FakeProjectDesignManager) RequestArtifactDraft(rc fwm.Context, projectID projectdesign.ProjectID, kind projectdesign.ArtifactKind, feedback *projectdesign.ReviewFeedback) (projectdesign.SessionRef, error) {
	if f.RequestArtifactDraftFn == nil {
		panic("FakeProjectDesignManager.RequestArtifactDraftFn not set")
	}
	return f.RequestArtifactDraftFn(rc, projectID, kind, feedback)
}

func (f *FakeProjectDesignManager) RequestSDPCommit(rc fwm.Context, projectID projectdesign.ProjectID) (projectdesign.SessionRef, error) {
	if f.RequestSDPCommitFn == nil {
		panic("FakeProjectDesignManager.RequestSDPCommitFn not set")
	}
	return f.RequestSDPCommitFn(rc, projectID)
}

func (f *FakeProjectDesignManager) AskQuestions(rc fwm.Context, projectID projectdesign.ProjectID, kind projectdesign.ArtifactKind, addressee string, questions []projectdesign.AnchoredComment) error {
	if f.AskQuestionsFn == nil {
		panic("FakeProjectDesignManager.AskQuestionsFn not set")
	}
	return f.AskQuestionsFn(rc, projectID, kind, addressee, questions)
}

func (f *FakeProjectDesignManager) AcknowledgeStaleBasis(rc fwm.Context, projectID projectdesign.ProjectID, kind projectdesign.ArtifactKind, note string) error {
	if f.AcknowledgeStaleBasisFn == nil {
		panic("FakeProjectDesignManager.AcknowledgeStaleBasisFn not set")
	}
	return f.AcknowledgeStaleBasisFn(rc, projectID, kind, note)
}

func (f *FakeProjectDesignManager) SetReviewCommentStatus(rc fwm.Context, projectID projectdesign.ProjectID, kind projectdesign.ArtifactKind, commentID string, status string) error {
	if f.SetReviewCommentStatusFn == nil {
		panic("FakeProjectDesignManager.SetReviewCommentStatusFn not set")
	}
	return f.SetReviewCommentStatusFn(rc, projectID, kind, commentID, status)
}

func (f *FakeProjectDesignManager) SubmitReviewDecision(rc fwm.Context, projectID projectdesign.ProjectID, kind projectdesign.ArtifactKind, decision projectdesign.ReviewDecision, feedback *projectdesign.ReviewFeedback) error {
	if f.SubmitReviewDecisionFn == nil {
		panic("FakeProjectDesignManager.SubmitReviewDecisionFn not set")
	}
	return f.SubmitReviewDecisionFn(rc, projectID, kind, decision, feedback)
}

func (f *FakeProjectDesignManager) SubmitSDPDecision(rc fwm.Context, projectID projectdesign.ProjectID, decision projectdesign.SDPDecision, optionID *projectdesign.OptionID, feedback *projectdesign.ReviewFeedback) error {
	if f.SubmitSDPDecisionFn == nil {
		panic("FakeProjectDesignManager.SubmitSDPDecisionFn not set")
	}
	return f.SubmitSDPDecisionFn(rc, projectID, decision, optionID, feedback)
}

func (f *FakeProjectDesignManager) ListEpisodesForArtifact(rc fwm.Context, projectID projectdesign.ProjectID, artifactKind projectdesign.ArtifactKind) ([]projectdesign.EpisodeRecordView, error) {
	if f.ListEpisodesForArtifactFn == nil {
		panic("FakeProjectDesignManager.ListEpisodesForArtifactFn not set")
	}
	return f.ListEpisodesForArtifactFn(rc, projectID, artifactKind)
}

func (f *FakeProjectDesignManager) GetEpisodeTimeline(rc fwm.Context, projectID projectdesign.ProjectID, episodeID string) (projectdesign.EpisodeTimeline, error) {
	if f.GetEpisodeTimelineFn == nil {
		panic("FakeProjectDesignManager.GetEpisodeTimelineFn not set")
	}
	return f.GetEpisodeTimelineFn(rc, projectID, episodeID)
}

var _ projectdesign.ProjectDesignManager = (*FakeProjectDesignManager)(nil)
