// Code generated by cmd/modelgen from the service-contract interface; DO NOT EDIT.
// Edit project.json's `interface` and re-run `make gen-fakes` instead.

package handofffake

import (
	fweng "github.com/mixofreality-studio/archistrator-platform/framework-go/engine"
	"github.com/mixofreality-studio/archistrator/server/internal/engine/handoff"
)

// FakeHandOffEngine is a generated test double for handoff.HandOffEngine: set the Fn field(s)
// a test needs; calling a method whose Fn is unset panics.
type FakeHandOffEngine struct {
	PickWorkerClassFn func(rc fweng.Context, activity handoff.ConstructionActivity, policy handoff.HandOffPolicy) (handoff.WorkerClass, error)
}

func (f *FakeHandOffEngine) PickWorkerClass(rc fweng.Context, activity handoff.ConstructionActivity, policy handoff.HandOffPolicy) (handoff.WorkerClass, error) {
	if f.PickWorkerClassFn == nil {
		panic("FakeHandOffEngine.PickWorkerClassFn not set")
	}
	return f.PickWorkerClassFn(rc, activity, policy)
}

var _ handoff.HandOffEngine = (*FakeHandOffEngine)(nil)
