// Code generated by cmd/modelgen from contract.schema.json; DO NOT EDIT.
// Edit the schema and re-run `make gen-models` instead.

package projectstate

import (
	fwra "github.com/mixofreality-studio/archistrator-platform/framework-go/resourceaccess"
)

// ProjectStateAccess is the generated service-contract interface for this component.
type ProjectStateAccess interface {
	AdvancePhase(rc fwra.Context, projectID ProjectID, expectedVersion Version) (Version, error)
	CommitArtifact(rc fwra.Context, projectID ProjectID, expectedVersion Version, kind ArtifactKind) (Version, error)
	CreateProject(rc fwra.Context, projectID ProjectID, owner OwnerScope, name string) (Version, error)
	ListProjects(rc fwra.Context, owner OwnerScope) ([]ProjectSummary, error)
	ReadProject(rc fwra.Context, projectID ProjectID) (Project, error)
	ReadProjectVersion(rc fwra.Context, projectID ProjectID) (Version, error)
	RejectArtifact(rc fwra.Context, projectID ProjectID, expectedVersion Version, kind ArtifactKind, notes string) (Version, error)
	SetResearchInput(rc fwra.Context, projectID ProjectID, expectedVersion Version, research ResearchInput) (Version, error)
	StageArtifactForReview(rc fwra.Context, projectID ProjectID, expectedVersion Version, model ArtifactModel) (Version, error)
	WithdrawArtifact(rc fwra.Context, projectID ProjectID, expectedVersion Version, kind ArtifactKind, notes string) (Version, error)
}
