/**
 * gen:ops — generate src/api/ops.gen.ts: an OpsClient with two transports (REST
 * over openapi-fetch, MCP over App.callServerTool) behind ONE interface, so
 * hooks become transport-blind between the browser SPA and an MCP-hosted app
 * (see @modelcontextprotocol/ext-apps).
 *
 * Every server OAS path has the mechanical shape
 * `/api/v1/<mgr>/<op>[/{param}...]`, where <mgr> and <op> are single kebab-case
 * path segments. The server's MCP tool name for that same operation is
 * `<camelMgr><PascalOp>` — e.g.
 * `/api/v1/system-design/get-session-state/{projectID}` (GET) binds to tool
 * `systemDesignGetSessionState`. This generator derives that binding for EVERY
 * method+path pair in the OAS; nobody hand-maintains the table, and a path that
 * does not fit the shape fails the build loudly instead of silently mis-binding.
 *
 * Reads the SAME OAS source as gen-api.mjs (../server/api/openapi.yaml) so the
 * REST paths and the OpsClient bindings can never drift from one another.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import yaml from 'js-yaml';

const here = dirname(fileURLToPath(import.meta.url));
const oasPath = join(here, '..', '..', 'server', 'api', 'openapi.yaml');
const outPath = join(here, '..', 'src', 'api', 'ops.gen.ts');

// openapi-fetch's client exposes one method per HTTP verb (GET/POST/PUT/PATCH/
// DELETE); the server OAS currently only uses GET and POST, but all five are
// listed here so a future PUT/PATCH/DELETE endpoint does not need this
// generator to change, only regeneration.
const HTTP_METHODS = ['get', 'post', 'put', 'patch', 'delete'];

function words(kebab) {
  return kebab.split('-').filter((w) => w.length > 0);
}

function pascalCase(kebab) {
  return words(kebab)
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join('');
}

function camelCase(kebab) {
  const p = pascalCase(kebab);
  return p.length > 0 ? p[0].toLowerCase() + p.slice(1) : p;
}

/**
 * Derive the {method, path, tool} binding for every operation in the OAS.
 * opId = camel(mgr) + Pascal(op); duplicate opIds (a derivation collision)
 * abort the build rather than silently overwriting one binding with another.
 */
function deriveBindings(doc) {
  const paths = doc.paths ?? {};
  const bindings = {};
  for (const [pathTemplate, methods] of Object.entries(paths)) {
    const segments = pathTemplate.split('/').filter((s) => s.length > 0);
    // segments: ['api', 'v1', '<mgr>', '<op>', ...optional '{param}' segments]
    if (segments.length < 4 || segments[0] !== 'api' || segments[1] !== 'v1') {
      throw new Error(
        `gen-ops: path does not match the /api/v1/<mgr>/<op>[/{...}] shape: ${pathTemplate}`
      );
    }
    const [, , mgr, op] = segments;
    const opId = camelCase(mgr) + pascalCase(op);
    for (const method of HTTP_METHODS) {
      if (!(method in methods)) continue;
      if (opId in bindings) {
        throw new Error(
          `gen-ops: duplicate derived opId "${opId}" (from ${pathTemplate} ${method.toUpperCase()}) — ` +
            'mgr/op derivation collided with an earlier binding'
        );
      }
      bindings[opId] = { method: method.toUpperCase(), path: pathTemplate, tool: opId };
    }
  }
  // Sort by opId so the emitted table's order is stable across regenerations
  // regardless of the OAS's own key order.
  return Object.fromEntries(Object.entries(bindings).sort(([a], [b]) => a.localeCompare(b)));
}

const source = readFileSync(oasPath, 'utf8');
const doc = yaml.load(source);
const bindings = deriveBindings(doc);

const emitted = `// Code generated by scripts/gen-ops.mjs. DO NOT EDIT.
/**
 * OpsClient — one call surface, two transports:
 *  - restOpsClient: REST over openapi-fetch (the standalone SPA, apiClient).
 *  - mcpOpsClient: MCP tool calls over App.callServerTool (the app hosted
 *    inside an MCP client via @modelcontextprotocol/ext-apps).
 *
 * OP_BINDINGS is mechanically derived from the server OAS at generation time
 * (see scripts/gen-ops.mjs): every '/api/v1/<mgr>/<op>[/{...}]' path yields an
 * OpId '<camelMgr><PascalOp>' bound to its {method, path, tool}. Hooks depend
 * only on OpsClient/OpId — never on which transport is live — via
 * useOpsClient() (src/api/opsContext.tsx).
 */
import type createClient from 'openapi-fetch';
import type { paths } from '../contracts/schema';
import type { App } from '@modelcontextprotocol/ext-apps';
// Runtime (value) import — needs the explicit .ts extension so this module also
// resolves under node --test's native type-stripping loader (which, unlike
// tsc's bundler moduleResolution, requires full specifiers). The type-only
// imports above are erased entirely and never hit Node's resolver, so they
// keep the extensionless convention the rest of the app uses.
import { ApiError, toApiError, type WireError } from '../contracts/errors.ts';

export const OP_BINDINGS = ${JSON.stringify(bindings, null, 2)} as const;

export type OpId = keyof typeof OP_BINDINGS;

/**
 * Structural params for one op call. REST decomposes these into openapi-fetch's
 * \`{ params: { path, query }, body }\`; MCP flattens path+query+body into one
 * tool-arguments object (MCP tools take a single flat arguments record).
 */
export interface OpParams {
  path?: Record<string, string> | undefined;
  query?: Record<string, unknown> | undefined;
  body?: unknown;
}

export interface OpsClient {
  call<R = unknown>(op: OpId, params?: OpParams): Promise<R>;
}

interface RestResult {
  data?: unknown;
  error?: unknown;
  response: Response;
}

type RestFn = (
  path: string,
  options: {
    params: { path?: Record<string, string> | undefined; query?: Record<string, unknown> | undefined };
    body?: unknown;
  }
) => Promise<RestResult>;

// openapi-fetch's client is keyed by HTTP verb (client.GET(...), client.POST(...),
// ...). OP_BINDINGS.method picks the right one at runtime; the cast below is the
// one place that trades static path-safety for the generic, table-driven dispatch
// every op needs (the OAS <-> OP_BINDINGS correspondence is guaranteed by
// gen-ops.mjs deriving both from the same source, not by this cast).
type RestMethodMap = Record<'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE', RestFn>;

export function restOpsClient(client: ReturnType<typeof createClient<paths>>): OpsClient {
  return {
    async call<R = unknown>(op: OpId, params: OpParams = {}): Promise<R> {
      const binding = OP_BINDINGS[op];
      const methods = client as unknown as RestMethodMap;
      const fn = methods[binding.method];
      const { data, error, response } = await fn(binding.path, {
        params: { path: params.path, query: params.query },
        body: params.body,
      });
      if (error !== undefined) throw toApiError(response.status, error as WireError);
      return data as R;
    },
  };
}

/** Best-effort not-found detection over a failed tool call's content blocks: a
 * text block whose text mentions "not found" (case-insensitive) maps the
 * ApiError to 404 so useSessionState's no-session-yet retry/poll suppression
 * keeps working over the MCP transport too. Anything else maps to 500 — MCP
 * tool errors do not carry a structured status code the way REST responses do. */
function isNotFoundToolError(content: unknown): boolean {
  if (!Array.isArray(content)) return false;
  return content.some((block) => {
    if (typeof block !== 'object' || block === null) return false;
    const text = (block as { text?: unknown }).text;
    return typeof text === 'string' && /not found/i.test(text);
  });
}

function toolErrorMessage(content: unknown): string {
  if (!Array.isArray(content)) return 'tool call failed';
  const texts = content
    .map((block) => {
      if (typeof block !== 'object' || block === null) return undefined;
      const text = (block as { text?: unknown }).text;
      return typeof text === 'string' ? text : undefined;
    })
    .filter((text): text is string => text !== undefined);
  return texts.length > 0 ? texts.join(' ') : 'tool call failed';
}

/**
 * MCP flattens path+query+body into one arguments object; unlike REST (where
 * path/query/body are structurally separate), a key present in more than one
 * part would silently be decided by merge order (body over query over path).
 * Guard loudly instead: a collision aborts the call with an ApiError rather
 * than resolving to whichever part happened to merge last.
 */
function assertNoArgCollision(
  opId: string,
  path: Record<string, unknown>,
  query: Record<string, unknown>,
  body: Record<string, unknown>
): void {
  const seen = new Map<string, string[]>();
  for (const [partName, part] of [
    ['path', path],
    ['query', query],
    ['body', body],
  ] as const) {
    for (const key of Object.keys(part)) {
      const parts = seen.get(key) ?? [];
      parts.push(partName);
      seen.set(key, parts);
    }
  }
  const collidingKeys = [...seen.entries()]
    .filter(([, parts]) => parts.length > 1)
    .map(([key]) => key);
  if (collidingKeys.length > 0) {
    throw new ApiError(
      500,
      'argCollision',
      \`argument key collision on \${opId}: \${collidingKeys.join(', ')}\`
    );
  }
}

export function mcpOpsClient(app: App): OpsClient {
  return {
    async call<R = unknown>(op: OpId, params: OpParams = {}): Promise<R> {
      const binding = OP_BINDINGS[op];
      const pathArgs = (params.path ?? {}) as Record<string, unknown>;
      const queryArgs = params.query ?? {};
      const bodyArgs = (params.body ?? {}) as Record<string, unknown>;
      assertNoArgCollision(op, pathArgs, queryArgs, bodyArgs);
      const args = { ...pathArgs, ...queryArgs, ...bodyArgs };
      const result = await app.callServerTool({ name: binding.tool, arguments: args });
      if (result.isError === true) {
        const status = isNotFoundToolError(result.content) ? 404 : 500;
        const code = status === 404 ? 'not_found' : 'internal';
        throw new ApiError(status, code, toolErrorMessage(result.content));
      }
      return (result.structuredContent ?? {}) as R;
    },
  };
}
`;

writeFileSync(outPath, emitted);

// Match gen-api.mjs's practice: format the generated file in place so
// `format:check` stays green after every build (prebuild runs this generator)
// and the committed ops.gen.ts is byte-identical to a fresh regen.
execFileSync('npx', ['prettier', '--write', outPath], {
  stdio: 'inherit',
  cwd: join(here, '..'),
});
