// Code generated by cmd/modelgen from contract.schema.json; DO NOT EDIT.
// Edit the schema and re-run `make gen-models` instead.

package projectdesign

import (
	"encoding/json"
	fwm "github.com/mixofreality-studio/archistrator-platform/framework-go/manager"
	"github.com/mixofreality-studio/archistrator/server/internal/engine/billing"
	"github.com/mixofreality-studio/archistrator/server/internal/engine/estimation"
	"github.com/mixofreality-studio/archistrator/server/internal/engine/operationestimation"
	"github.com/mixofreality-studio/archistrator/server/internal/resourceaccess/agenticjob"
	"github.com/mixofreality-studio/archistrator/server/internal/resourceaccess/episode"
	"github.com/mixofreality-studio/archistrator/server/internal/resourceaccess/projectstate"
	"github.com/mixofreality-studio/archistrator/server/internal/resourceaccess/sourcecontrol"
	"go.temporal.io/sdk/client"
)

type ActiveRole int

const (
	ActiveRoleNone           ActiveRole = 0
	ActiveRoleArchitect      ActiveRole = 1
	ActiveRoleProductManager ActiveRole = 2
)

type ActiveStep int

const (
	ActiveStepNone       ActiveStep = 0
	ActiveStepDrafting   ActiveStep = 1
	ActiveStepCritiquing ActiveStep = 2
	ActiveStepRevising   ActiveStep = 3
)

type AnchoredComment struct {
	JSONPath   string `json:"jsonPath"`
	Text       string `json:"text"`
	AnchorText string `json:"anchorText"`
}

type ArtifactKind int

const (
	KindMission              ArtifactKind = 0
	KindGlossary             ArtifactKind = 1
	KindScrubbedRequirements ArtifactKind = 2
	KindVolatilities         ArtifactKind = 3
	KindCoreUseCases         ArtifactKind = 4
	KindSystem               ArtifactKind = 5
	KindOperationalConcepts  ArtifactKind = 6
	KindStandardCheck        ArtifactKind = 7
	KindPlanningAssumptions  ArtifactKind = 8
	KindActivityList         ArtifactKind = 9
	KindNetwork              ArtifactKind = 10
	KindNormalSolution       ArtifactKind = 11
	KindSubcriticalSolution  ArtifactKind = 12
	KindCompressedSolution   ArtifactKind = 13
	KindDecompressedSolution ArtifactKind = 14
	KindRiskModel            ArtifactKind = 15
	KindSdpReview            ArtifactKind = 16
)

type DraftModel struct {
	Kind  string           `json:"kind"`
	Model *json.RawMessage `json:"model,omitempty"`
}

type Finding struct {
	RuleID   RuleID    `json:"ruleId"`
	Severity Severity  `json:"severity"`
	Message  string    `json:"message"`
	Location *Location `json:"location,omitempty"`
}

type Location struct {
	Ordinal int64  `json:"ordinal"`
	Section string `json:"section"`
}

type OptionID string

type PhaseAdvanceResult struct {
	Advanced         bool           `json:"advanced"`
	MissingArtifacts []ArtifactKind `json:"missingArtifacts"`
}

type ProjectID string

type ReviewCommentView struct {
	ID         string `json:"id"`
	Anchor     string `json:"anchor"`
	AnchorText string `json:"anchorText"`
	Text       string `json:"text"`
	AuthorRole string `json:"authorRole"`
	Round      int64  `json:"round"`
	Status     string `json:"status"`
	Response   string `json:"response"`
	Type       string `json:"type"`
	Addressee  string `json:"addressee"`
}

type ReviewDecision int

const (
	ReviewDecisionUnknown ReviewDecision = 0
	ReviewApprove         ReviewDecision = 1
	ReviewReject          ReviewDecision = 2
	ReviewWithdraw        ReviewDecision = 3
)

type ReviewFeedback struct {
	Notes    string            `json:"notes"`
	Comments []AnchoredComment `json:"comments,omitempty"`
}

type RuleID string

type SDPDecision int

const (
	SDPDecisionUnknown SDPDecision = 0
	SDPCommit          SDPDecision = 1
	SDPRejectAll       SDPDecision = 2
)

type SessionRef string

type SessionStage int

const (
	SessionStageUnknown SessionStage = 0
	StageDrafting       SessionStage = 1
	StageAssemblingSDP  SessionStage = 2
	StageAwaitingReview SessionStage = 3
	StageRedrafting     SessionStage = 4
	StageCommitted      SessionStage = 5
	StageWithdrawn      SessionStage = 6
	StageRefused        SessionStage = 7
	StageDraftFailed    SessionStage = 8
)

type SessionStateView struct {
	ProjectID     ProjectID           `json:"projectId"`
	ArtifactKind  ArtifactKind        `json:"artifactKind"`
	Stage         SessionStage        `json:"stage"`
	Draft         DraftModel          `json:"draft"`
	Findings      []Finding           `json:"findings,omitempty"`
	FailureReason *string             `json:"failureReason,omitempty"`
	StageName     string              `json:"stageName"`
	ReviewThread  []ReviewCommentView `json:"reviewThread,omitempty"`
	ActiveRole    ActiveRole          `json:"activeRole"`
	ActiveStep    ActiveStep          `json:"activeStep"`
	Round         int64               `json:"round"`
}

type Severity string

const (
	SeverityInfo    Severity = "info"
	SeverityWarning Severity = "warning"
	SeverityError   Severity = "error"
)

// ProjectDesignManager is the generated service-contract interface for this component.
type ProjectDesignManager interface {
	AdvanceToConstruction(rc fwm.Context, projectID ProjectID, acknowledgeStale bool) (PhaseAdvanceResult, error)
	GetSessionState(rc fwm.Context, projectID ProjectID, kind ArtifactKind) (SessionStateView, error)
	RequestArtifactDraft(rc fwm.Context, projectID ProjectID, kind ArtifactKind, feedback *ReviewFeedback) (SessionRef, error)
	RequestSDPCommit(rc fwm.Context, projectID ProjectID) (SessionRef, error)
	AskQuestions(rc fwm.Context, projectID ProjectID, kind ArtifactKind, addressee string, questions []AnchoredComment) error
	AcknowledgeStaleBasis(rc fwm.Context, projectID ProjectID, kind ArtifactKind, note string) error
	SetReviewCommentStatus(rc fwm.Context, projectID ProjectID, kind ArtifactKind, commentID string, status string) error
	SubmitReviewDecision(rc fwm.Context, projectID ProjectID, kind ArtifactKind, decision ReviewDecision, feedback *ReviewFeedback) error
	SubmitSDPDecision(rc fwm.Context, projectID ProjectID, decision SDPDecision, optionID *OptionID, feedback *ReviewFeedback) error
}

// NewProjectDesignManager constructs the ProjectDesignManager, delegating to the hand-written, unexported
// builder newProjectDesignManager in the manager package (which owns the stateful facade setup:
// the Temporal client, the deps, and config). The constructor returns the
// interface, so the concrete manager impl stays unexported.
func NewProjectDesignManager(client client.Client, projectState projectstate.ProjectStateAccess, pipeline agenticjob.AgenticJobAccess, rail sourcecontrol.SourceControlAccess, estimator estimation.EstimationEngine, operationEstimator operationestimation.OperationEstimationEngine, billingEstimator billing.BillingEngine, designSession projectstate.DesignSessionAccess, episodes episode.EpisodeAccess, repo func(projectID ProjectID) (sourcecontrol.RepoRef, bool)) ProjectDesignManager {
	return newProjectDesignManager(client, projectState, pipeline, rail, estimator, operationEstimator, billingEstimator, designSession, episodes, repo)
}
