// Code generated by temporalgen. DO NOT EDIT.

package projectdesign

import (
	"go.temporal.io/sdk/activity"
	"go.temporal.io/sdk/worker"
	"go.temporal.io/sdk/workflow"
)

// TaskQueue is the manager's Temporal task queue (derived from the contract
// interface name).
const TaskQueue = "project-design"

// genWorkerManifest is what the hand-written manager supplies to
// RegisterWorker: the workflow functions (codegen cannot know them), any
// hybrid hand-written activities, the invoker options hook, and the
// genActivities dep threading.
type genWorkerManifest struct {
	Workflows        []genRegisteredWorkflow
	CustomActivities []genRegisteredActivity
	ActivityOptions  func(activityName string) (workflow.ActivityOptions, bool)
	Activities       genActivities
}

type genRegisteredWorkflow struct {
	Name string
	Fn   any
}

type genRegisteredActivity struct {
	Name string
	Fn   any
}

// RegisterWorker registers every workflow + generated activity + custom
// activity on w. Forgetting a generated activity is impossible; workflows and
// hybrids are exactly what the manifest declares.
func RegisterWorker(w worker.Worker, mf genWorkerManifest) {
	for _, wf := range mf.Workflows {
		w.RegisterWorkflowWithOptions(wf.Fn, workflow.RegisterOptions{Name: wf.Name})
	}
	acts := &mf.Activities
	w.RegisterActivityWithOptions(acts.PipelineCancelConstructionPipeline, activity.RegisterOptions{Name: "constructionPipelineAccess.cancelConstructionPipeline"})
	w.RegisterActivityWithOptions(acts.PipelineObserveConstructionPipeline, activity.RegisterOptions{Name: "constructionPipelineAccess.observeConstructionPipeline"})
	w.RegisterActivityWithOptions(acts.PipelineSubmitConstructionPipeline, activity.RegisterOptions{Name: "constructionPipelineAccess.submitConstructionPipeline"})
	w.RegisterActivityWithOptions(acts.ProjectStateAdvancePhase, activity.RegisterOptions{Name: "projectStateAccess.advancePhase"})
	w.RegisterActivityWithOptions(acts.ProjectStateCommitArtifact, activity.RegisterOptions{Name: "projectStateAccess.commitArtifact"})
	w.RegisterActivityWithOptions(acts.ProjectStateCreateProject, activity.RegisterOptions{Name: "projectStateAccess.createProject"})
	w.RegisterActivityWithOptions(acts.ProjectStateListProjects, activity.RegisterOptions{Name: "projectStateAccess.listProjects"})
	w.RegisterActivityWithOptions(acts.ProjectStateReadProject, activity.RegisterOptions{Name: "projectStateAccess.readProject"})
	w.RegisterActivityWithOptions(acts.ProjectStateReadProjectVersion, activity.RegisterOptions{Name: "projectStateAccess.readProjectVersion"})
	w.RegisterActivityWithOptions(acts.ProjectStateRejectArtifact, activity.RegisterOptions{Name: "projectStateAccess.rejectArtifact"})
	w.RegisterActivityWithOptions(acts.ProjectStateSetOperatingModel, activity.RegisterOptions{Name: "projectStateAccess.setOperatingModel"})
	w.RegisterActivityWithOptions(acts.ProjectStateSetResearchInput, activity.RegisterOptions{Name: "projectStateAccess.setResearchInput"})
	w.RegisterActivityWithOptions(acts.ProjectStateStageArtifactForReview, activity.RegisterOptions{Name: "projectStateAccess.stageArtifactForReview"})
	w.RegisterActivityWithOptions(acts.ProjectStateWithdrawArtifact, activity.RegisterOptions{Name: "projectStateAccess.withdrawArtifact"})
	w.RegisterActivityWithOptions(acts.RailAdoptProjectRepo, activity.RegisterOptions{Name: "sourceControlAccess.adoptProjectRepo"})
	w.RegisterActivityWithOptions(acts.RailCommitManagedFiles, activity.RegisterOptions{Name: "sourceControlAccess.commitManagedFiles"})
	w.RegisterActivityWithOptions(acts.RailConfigureBranchProtection, activity.RegisterOptions{Name: "sourceControlAccess.configureBranchProtection"})
	w.RegisterActivityWithOptions(acts.RailGetInstallationToken, activity.RegisterOptions{Name: "sourceControlAccess.getInstallationToken"})
	w.RegisterActivityWithOptions(acts.RailGetPullRequestStatus, activity.RegisterOptions{Name: "sourceControlAccess.getPullRequestStatus"})
	w.RegisterActivityWithOptions(acts.RailInstallAuthorizeApp, activity.RegisterOptions{Name: "sourceControlAccess.installAuthorizeApp"})
	w.RegisterActivityWithOptions(acts.RailMergePullRequest, activity.RegisterOptions{Name: "sourceControlAccess.mergePullRequest"})
	w.RegisterActivityWithOptions(acts.RailOpenBranch, activity.RegisterOptions{Name: "sourceControlAccess.openBranch"})
	w.RegisterActivityWithOptions(acts.RailOpenPullRequest, activity.RegisterOptions{Name: "sourceControlAccess.openPullRequest"})
	w.RegisterActivityWithOptions(acts.RailPostReview, activity.RegisterOptions{Name: "sourceControlAccess.postReview"})
	for _, ca := range mf.CustomActivities {
		w.RegisterActivityWithOptions(ca.Fn, activity.RegisterOptions{Name: ca.Name})
	}
}
