// cmd/gen-uiprofiles emits the per-ActivityKind canonical lifecycle phase
// table (id/phase/name/weight/tasks) into
// webApp/src/components/construction/lifecycleTemplates.gen.ts, mechanically
// derived from internal/resourceaccess/projectstate/projectstateaccess.go's
// ProfileFor. This closes a webApp hand-mirror: lifecycleTemplates.ts used to
// hand-author its own per-kind phase breakdown, ported long ago from a frozen
// UX mock — see that file's header for the resolved discrepancy against the
// server's later-ratified canonical 5-phase Profile
// (Requirements/DetailedDesign/TestPlan/Construction/Integration, a WEIGHTED
// SUBSET per activity kind so the shared earned-value formula, Appendix A,
// stays uniform across kinds).
//
// This tool needs no project.json — Profile/ActivityType/TestingVariant are a
// closed, static enumeration, not project data. It writes id/phase/name/
// weight/tasks; the exit-criterion prose (no server-side source) and the
// BuildStatus -> active-phase derivation are hand-written, in
// lifecycleTemplates.ts, which imports this generated file.
//
// Testing emits all FIVE variant profiles the server carries (Plan/Harness/
// Perf/SystemTest/QAProcess — materially different weights) into their own
// consts plus the GENERATED_TESTING_VARIANTS record below, so a testing
// activity's rendered lifecycle matches its actual variant instead of always
// falling back to the Plan (N-STP) shape. Testing is 7 of 40 committed
// activities, so this mattered for most of them.
//
// Every phase also carries its Figure A-1 task vocabulary (TasksForPhase),
// each task flagged gate (its success IS the phase's binary exit criterion,
// GateTaskFor) and conditional (rendered only when a real attempt record
// exists, IsConditionalTask) — so the SPA can render the task breakdown
// without hand-mirroring the server.
//
// Usage (matching the Makefile gen-uiprofiles / gen-uiprofiles-check targets,
// run from server/):
//
//	GOWORK=off go run ./cmd/gen-uiprofiles \
//	  -out ../webApp/src/components/construction/lifecycleTemplates.gen.ts
package main

import (
	"flag"
	"fmt"
	"os"
	"strings"

	"github.com/mixofreality-studio/archistrator/server/internal/resourceaccess/projectstate"
)

// kindSpec pairs a webApp ActivityKind literal + its generated const name with
// the (ActivityType, TestingVariant) cell that produces its Profile.
type kindSpec struct {
	tsKind       string
	constName    string
	activityType projectstate.ActivityType
	variant      projectstate.TestingVariant
}

var kinds = []kindSpec{
	{"service", "SERVICE_PHASES", projectstate.ActivityTypeService, projectstate.TestVariantPlan},
	{"frontend", "FRONTEND_PHASES", projectstate.ActivityTypeFrontend, projectstate.TestVariantPlan},
	{"testing", "TESTING_PHASES", projectstate.ActivityTypeTesting, projectstate.TestVariantPlan},
	{"deployment", "DEPLOYMENT_PHASES", projectstate.ActivityTypeDeployment, projectstate.TestVariantPlan},
	{"documentation", "DOCUMENTATION_PHASES", projectstate.ActivityTypeDocumentation, projectstate.TestVariantPlan},
	{"uiDesign", "UI_DESIGN_PHASES", projectstate.ActivityTypeUIDesign, projectstate.TestVariantPlan},
	{"integration", "INTEGRATION_PHASES", projectstate.ActivityTypeIntegration, projectstate.TestVariantPlan},
}

// testingVariants emits the FIVE testing profiles the server actually carries. The
// generator used to emit only TestVariantPlan, so an N-IT activity rendered the N-STP
// shape — wrong for four of the five, and testing is 7 of 40 committed activities.
var testingVariants = []struct {
	tsVariant string
	constName string
	variant   projectstate.TestingVariant
}{
	{"plan", "TESTING_PLAN_PHASES", projectstate.TestVariantPlan},
	{"harness", "TESTING_HARNESS_PHASES", projectstate.TestVariantHarness},
	{"perf", "TESTING_PERF_PHASES", projectstate.TestVariantPerf},
	{"systemTest", "TESTING_SYSTEM_TEST_PHASES", projectstate.TestVariantSystemTest},
	{"qaProcess", "TESTING_QA_PROCESS_PHASES", projectstate.TestVariantQAProcess},
}

func main() {
	out := flag.String("out", "../webApp/src/components/construction/lifecycleTemplates.gen.ts", "output path for the generated TS file")
	flag.Parse()

	if err := run(*out); err != nil {
		fmt.Fprintf(os.Stderr, "gen-uiprofiles: %v\n", err)
		os.Exit(1)
	}
}

func run(outPath string) error {
	var b strings.Builder
	writeHeader(&b)

	for _, k := range kinds {
		writePhasesConst(&b, k.constName, k.activityType, k.variant)
	}
	writeTemplatesRecord(&b)

	for _, v := range testingVariants {
		writePhasesConst(&b, v.constName, projectstate.ActivityTypeTesting, v.variant)
	}
	writeTestingVariantsRecord(&b)

	return os.WriteFile(outPath, []byte(b.String()), 0o644) //nolint:gosec // generated TS, not a secret
}

func writeHeader(b *strings.Builder) {
	b.WriteString(`// Code generated by server/cmd/gen-uiprofiles. DO NOT EDIT.
// Source: server/internal/resourceaccess/projectstate/projectstateaccess.go (ProfileFor).
//
// id/phase/name/weight/tasks per activity kind, sourced from the server's single
// canonical Profile (Requirements/DetailedDesign/TestPlan/Construction/
// Integration weighted subset) — see lifecycleTemplates.ts for the
// exit-criterion prose and BuildStatus derivation layered on top.

import type { ActivityKind } from './KindBadge';

/** Canonical Method lifecycle phase (Righting Software Appendix A / Table A-1). */
export type LifecyclePhase =
  | 'requirements'
  | 'detailed_design'
  | 'test_plan'
  | 'construction'
  | 'integration';

/** One Figure A-1 task within a lifecycle phase. */
export interface GeneratedTask {
  task: string;
  /** True when this task's success IS the phase's binary exit criterion (App A). */
  gate: boolean;
  /** True when the task is emitted only if a real attempt record exists. */
  conditional: boolean;
}

/** One canonical-phase entry in a kind's profile — id/phase/name/weight/tasks. */
export interface GeneratedPhase {
  id: string;
  phase: LifecyclePhase;
  name: string;
  /** % contribution (App A Table A-1); weights sum to 100 per kind. */
  weight: number;
  tasks: readonly GeneratedTask[];
}

`)
}

func writePhasesConst(
	b *strings.Builder,
	constName string,
	t projectstate.ActivityType,
	v projectstate.TestingVariant,
) {
	profile := projectstate.ProfileFor(t, v)

	fmt.Fprintf(b, "export const %s: readonly GeneratedPhase[] = [\n", constName)
	for _, p := range profile.Phases {
		id := projectstate.CommandFor(t, v, p.Phase)
		b.WriteString("  {\n")
		fmt.Fprintf(b, "    id: %s,\n", tsString(id))
		fmt.Fprintf(b, "    phase: %s,\n", tsString(string(p.Phase)))
		fmt.Fprintf(b, "    name: %s,\n", tsString(p.Label))
		fmt.Fprintf(b, "    weight: %d,\n", p.Weight)
		b.WriteString("    tasks: [\n")
		for _, task := range projectstate.TasksForPhase(p.Phase) {
			fmt.Fprintf(b, "      { task: %s, gate: %t, conditional: %t },\n",
				tsString(string(task)),
				projectstate.GateTaskFor(p.Phase) == task,
				projectstate.IsConditionalTask(task))
		}
		b.WriteString("    ],\n")
		b.WriteString("  },\n")
	}
	b.WriteString("];\n\n")
}

func writeTemplatesRecord(b *strings.Builder) {
	b.WriteString("export const GENERATED_TEMPLATES: Record<ActivityKind, readonly GeneratedPhase[]> = {\n")
	for _, k := range kinds {
		fmt.Fprintf(b, "  %s: %s,\n", k.tsKind, k.constName)
	}
	b.WriteString("};\n\n")
}

// writeTestingVariantsRecord emits a lookup from the webApp TestingVariantName
// literal to that variant's own GeneratedPhase profile, so a variant-aware
// caller can render the right shape instead of the one-size TESTING_PHASES.
func writeTestingVariantsRecord(b *strings.Builder) {
	b.WriteString("export const GENERATED_TESTING_VARIANTS: Record<string, readonly GeneratedPhase[]> = {\n")
	for _, v := range testingVariants {
		fmt.Fprintf(b, "  %s: %s,\n", v.tsVariant, v.constName)
	}
	b.WriteString("};\n")
}

// tsString renders a Go string as a single-quoted TS string literal (matches
// the repo's prettier config: singleQuote true).
func tsString(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "\\'") + "'"
}
