// cmd/gen-uiprofiles emits the per-ActivityKind canonical lifecycle phase
// table (id/phase/name/weight) into
// webApp/src/components/construction/lifecycleTemplates.gen.ts, mechanically
// derived from internal/resourceaccess/projectstate/activityprofile.go's
// ProfileFor. This closes a webApp hand-mirror: lifecycleTemplates.ts used to
// hand-author its own per-kind phase breakdown, ported long ago from a frozen
// UX mock — see that file's header for the resolved discrepancy against the
// server's later-ratified canonical 5-phase Profile
// (Requirements/DetailedDesign/TestPlan/Construction/Integration, a WEIGHTED
// SUBSET per activity kind so the shared earned-value formula, Appendix A,
// stays uniform across kinds).
//
// This tool needs no project.json — Profile/ActivityType/TestingVariant are a
// closed, static enumeration, not project data. It writes ONLY id/phase/
// name/weight; the exit-criterion prose (no server-side source) and the
// BuildStatus -> active-phase derivation are hand-written, in
// lifecycleTemplates.ts, which imports this generated file.
//
// Testing kind uses TestVariantPlan (the zero value / N-STP profile) — the
// webApp lifecycle panel does not vary its display by testing variant today
// (ActivityLifecyclePanel calls phaseStateFor(kind, status) with no variant
// argument), so this generator emits one representative testing profile,
// matching current UI behavior. See the earmark in lifecycleTemplates.ts for
// variant-aware testing profiles as a follow-up.
//
// Usage (matching the Makefile gen-uiprofiles / gen-uiprofiles-check targets,
// run from server/):
//
//	GOWORK=off go run ./cmd/gen-uiprofiles \
//	  -out ../webApp/src/components/construction/lifecycleTemplates.gen.ts
package main

import (
	"flag"
	"fmt"
	"os"
	"strings"

	"github.com/mixofreality-studio/archistrator/server/internal/resourceaccess/projectstate"
)

// kindSpec pairs a webApp ActivityKind literal + its generated const name with
// the (ActivityType, TestingVariant) cell that produces its Profile.
type kindSpec struct {
	tsKind       string
	constName    string
	activityType projectstate.ActivityType
	variant      projectstate.TestingVariant
}

var kinds = []kindSpec{
	{"service", "SERVICE_PHASES", projectstate.ActivityTypeService, projectstate.TestVariantPlan},
	{"frontend", "FRONTEND_PHASES", projectstate.ActivityTypeFrontend, projectstate.TestVariantPlan},
	{"testing", "TESTING_PHASES", projectstate.ActivityTypeTesting, projectstate.TestVariantPlan},
	{"deployment", "DEPLOYMENT_PHASES", projectstate.ActivityTypeDeployment, projectstate.TestVariantPlan},
	{"documentation", "DOCUMENTATION_PHASES", projectstate.ActivityTypeDocumentation, projectstate.TestVariantPlan},
}

func main() {
	out := flag.String("out", "../webApp/src/components/construction/lifecycleTemplates.gen.ts", "output path for the generated TS file")
	flag.Parse()

	if err := run(*out); err != nil {
		fmt.Fprintf(os.Stderr, "gen-uiprofiles: %v\n", err)
		os.Exit(1)
	}
}

func run(outPath string) error {
	var b strings.Builder
	writeHeader(&b)

	for _, k := range kinds {
		writePhasesConst(&b, k)
	}
	writeTemplatesRecord(&b)

	return os.WriteFile(outPath, []byte(b.String()), 0o644) //nolint:gosec // generated TS, not a secret
}

func writeHeader(b *strings.Builder) {
	b.WriteString(`// Code generated by server/cmd/gen-uiprofiles. DO NOT EDIT.
// Source: server/internal/resourceaccess/projectstate/activityprofile.go (ProfileFor).
//
// id/phase/name/weight per activity kind, sourced from the server's single
// canonical Profile (Requirements/DetailedDesign/TestPlan/Construction/
// Integration weighted subset) — see lifecycleTemplates.ts for the
// exit-criterion prose and BuildStatus derivation layered on top.

import type { ActivityKind } from './KindBadge';

/** Canonical Method lifecycle phase (Righting Software Appendix A / Table A-1). */
export type CanonicalPhase =
  | 'requirements'
  | 'detailed_design'
  | 'test_plan'
  | 'construction'
  | 'integration';

/** One canonical-phase entry in a kind's profile — id/phase/name/weight sourced from the server Profile. */
export interface GeneratedPhase {
  id: string;
  phase: CanonicalPhase;
  name: string;
  /** % contribution (App A Table A-1); weights sum to 100 per kind. */
  weight: number;
}

`)
}

// prettierPrintWidth matches webApp/.prettierrc's printWidth: 100 — object
// literals that would exceed it on one line are wrapped one field per line,
// matching prettier's own wrap decision (verified against `npx prettier
// --check` over this generator's output; see the package doc).
const prettierPrintWidth = 100

func writePhasesConst(b *strings.Builder, k kindSpec) {
	profile := projectstate.ProfileFor(k.activityType, k.variant)

	fmt.Fprintf(b, "export const %s: readonly GeneratedPhase[] = [\n", k.constName)
	for _, p := range profile.Phases {
		id := projectstate.CommandFor(k.activityType, k.variant, p.Phase)
		fields := []string{
			"id: " + tsString(id),
			"phase: " + tsString(string(p.Phase)),
			"name: " + tsString(p.Label),
			fmt.Sprintf("weight: %d", p.Weight),
		}
		writeObjectLiteral(b, fields)
	}
	b.WriteString("];\n\n")
}

// writeObjectLiteral writes one array element (indent 2) as a single-line
// `{ f1, f2 },` when it fits prettierPrintWidth, else one field per line
// (indent 4) with a trailing comma, closing `},` at indent 2.
func writeObjectLiteral(b *strings.Builder, fields []string) {
	oneLine := "  { " + strings.Join(fields, ", ") + " },"
	if len(oneLine) <= prettierPrintWidth {
		b.WriteString(oneLine)
		b.WriteString("\n")
		return
	}
	b.WriteString("  {\n")
	for _, f := range fields {
		fmt.Fprintf(b, "    %s,\n", f)
	}
	b.WriteString("  },\n")
}

func writeTemplatesRecord(b *strings.Builder) {
	b.WriteString("export const GENERATED_TEMPLATES: Record<ActivityKind, readonly GeneratedPhase[]> = {\n")
	for _, k := range kinds {
		fmt.Fprintf(b, "  %s: %s,\n", k.tsKind, k.constName)
	}
	b.WriteString("};\n")
}

// tsString renders a Go string as a single-quoted TS string literal (matches
// the repo's prettier config: singleQuote true).
func tsString(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "\\'") + "'"
}
