// Code generated by cmd/modelgen from the service-contract interface; DO NOT EDIT.
// Edit project.json's `interface` and re-run `make gen-fakes` instead.

package durableexecutionfake

import (
	fwra "github.com/mixofreality-studio/archistrator-platform/framework-go/resourceaccess"
	"github.com/mixofreality-studio/archistrator/server/internal/resourceaccess/durableexecution"
)

// FakeDurableExecutionAccess is a generated test double for durableexecution.DurableExecutionAccess: set the Fn field(s)
// a test needs; calling a method whose Fn is unset panics.
type FakeDurableExecutionAccess struct {
	DeliverSignalFn          func(rc fwra.Context, targetExecutionID durableexecution.ExecutionID, signalName durableexecution.SignalName, payload durableexecution.ExecutionPayload) error
	QueryExecutionStateFn    func(rc fwra.Context, executionID durableexecution.ExecutionID, queryName durableexecution.QueryName, args durableexecution.ExecutionPayload) (durableexecution.ExecutionStateView, error)
	RegisterScheduleFn       func(rc fwra.Context, scheduleID durableexecution.ScheduleID, spec durableexecution.ScheduleSpec) error
	StartOrSignalExecutionFn func(rc fwra.Context, executionKind durableexecution.ExecutionKind, executionID durableexecution.ExecutionID, signalName durableexecution.SignalName, payload durableexecution.ExecutionPayload) (durableexecution.ExecutionHandle, error)
}

func (f *FakeDurableExecutionAccess) DeliverSignal(rc fwra.Context, targetExecutionID durableexecution.ExecutionID, signalName durableexecution.SignalName, payload durableexecution.ExecutionPayload) error {
	if f.DeliverSignalFn == nil {
		panic("FakeDurableExecutionAccess.DeliverSignalFn not set")
	}
	return f.DeliverSignalFn(rc, targetExecutionID, signalName, payload)
}

func (f *FakeDurableExecutionAccess) QueryExecutionState(rc fwra.Context, executionID durableexecution.ExecutionID, queryName durableexecution.QueryName, args durableexecution.ExecutionPayload) (durableexecution.ExecutionStateView, error) {
	if f.QueryExecutionStateFn == nil {
		panic("FakeDurableExecutionAccess.QueryExecutionStateFn not set")
	}
	return f.QueryExecutionStateFn(rc, executionID, queryName, args)
}

func (f *FakeDurableExecutionAccess) RegisterSchedule(rc fwra.Context, scheduleID durableexecution.ScheduleID, spec durableexecution.ScheduleSpec) error {
	if f.RegisterScheduleFn == nil {
		panic("FakeDurableExecutionAccess.RegisterScheduleFn not set")
	}
	return f.RegisterScheduleFn(rc, scheduleID, spec)
}

func (f *FakeDurableExecutionAccess) StartOrSignalExecution(rc fwra.Context, executionKind durableexecution.ExecutionKind, executionID durableexecution.ExecutionID, signalName durableexecution.SignalName, payload durableexecution.ExecutionPayload) (durableexecution.ExecutionHandle, error) {
	if f.StartOrSignalExecutionFn == nil {
		panic("FakeDurableExecutionAccess.StartOrSignalExecutionFn not set")
	}
	return f.StartOrSignalExecutionFn(rc, executionKind, executionID, signalName, payload)
}

var _ durableexecution.DurableExecutionAccess = (*FakeDurableExecutionAccess)(nil)
