// Code generated by composegen. DO NOT EDIT.

package main

// Web-exposed managers are DRIVER-CONFIGURED (Config.WebExposedManagers),
// NOT derived from System relationships: constructionManager, operationsManager, projectDesignManager, systemDesignManager.

import (
	"context"
	"errors"
	"log/slog"
	"net/http"
	"os/signal"
	"syscall"
	"time"

	"github.com/mixofreality-studio/archistrator-platform/framework-go-infrastructure-github"
	otelinfra "github.com/mixofreality-studio/archistrator-platform/framework-go-infrastructure-otel"
	postgresinfra "github.com/mixofreality-studio/archistrator-platform/framework-go-infrastructure-postgres"
	temporalprop "github.com/mixofreality-studio/archistrator-platform/framework-go-infrastructure-temporal"
	security "github.com/mixofreality-studio/archistrator-platform/framework-go/utilities/security"
	telemetry "github.com/mixofreality-studio/archistrator-platform/framework-go/utilities/telemetry"
	web "github.com/mixofreality-studio/archistrator/server/internal/client/web"
	constructionweb "github.com/mixofreality-studio/archistrator/server/internal/client/web/construction"
	operationsweb "github.com/mixofreality-studio/archistrator/server/internal/client/web/operations"
	projectdesignweb "github.com/mixofreality-studio/archistrator/server/internal/client/web/projectdesign"
	systemdesignweb "github.com/mixofreality-studio/archistrator/server/internal/client/web/systemdesign"
	"github.com/mixofreality-studio/archistrator/server/internal/engine/autoscaler"
	enginebilling "github.com/mixofreality-studio/archistrator/server/internal/engine/billing"
	"github.com/mixofreality-studio/archistrator/server/internal/engine/estimation"
	"github.com/mixofreality-studio/archistrator/server/internal/engine/handoff"
	"github.com/mixofreality-studio/archistrator/server/internal/engine/intervention"
	"github.com/mixofreality-studio/archistrator/server/internal/engine/operationestimation"
	"github.com/mixofreality-studio/archistrator/server/internal/engine/review"
	managerbilling "github.com/mixofreality-studio/archistrator/server/internal/manager/billing"
	"github.com/mixofreality-studio/archistrator/server/internal/manager/construction"
	"github.com/mixofreality-studio/archistrator/server/internal/manager/operations"
	"github.com/mixofreality-studio/archistrator/server/internal/manager/projectdesign"
	"github.com/mixofreality-studio/archistrator/server/internal/manager/systemdesign"
	"github.com/mixofreality-studio/archistrator/server/internal/resourceaccess/artifact"
	"github.com/mixofreality-studio/archistrator/server/internal/resourceaccess/billingstate"
	"github.com/mixofreality-studio/archistrator/server/internal/resourceaccess/constructionpipeline"
	"github.com/mixofreality-studio/archistrator/server/internal/resourceaccess/merchantgateway"
	"github.com/mixofreality-studio/archistrator/server/internal/resourceaccess/operatedruntime"
	"github.com/mixofreality-studio/archistrator/server/internal/resourceaccess/operatedsystemstate"
	"github.com/mixofreality-studio/archistrator/server/internal/resourceaccess/projectstate"
	"github.com/mixofreality-studio/archistrator/server/internal/resourceaccess/sourcecontrol"
	"github.com/mixofreality-studio/archistrator/server/internal/resourceaccess/usage"
	otelhttp "go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"
	"go.temporal.io/sdk/client"
	temporalotel "go.temporal.io/sdk/contrib/opentelemetry"
	"go.temporal.io/sdk/interceptor"
	tlog "go.temporal.io/sdk/log"
	"go.temporal.io/sdk/worker"
	"go.temporal.io/sdk/workflow"
)

// serviceName is the OTel service.name + span-name root for this container.
const serviceName = "archistrator-server"

// WebManagers is the typed bundle of web-exposed managers the composition
// root threads through the logging wrap and into the transports.
type WebManagers struct {
	ConstructionManager  construction.ConstructionManager
	OperationsManager    operations.OperationsManager
	ProjectDesignManager projectdesign.ProjectDesignManager
	SystemDesignManager  systemdesign.SystemDesignManager
}

// Hooks is the composition-root policy seam: the genuinely-compositional
// decisions the deployment model cannot express. The hand hooks.go implements
// it; RunGenerated calls it.
type Hooks interface {
	// ResolveProfile maps the loaded config (legacy toggles) to the active
	// deployment profile whose per-binding variants are constructed.
	ResolveProfile(cfg *Config) string

	// TemporalLogger adapts the composition-root slog.Logger onto the Temporal
	// SDK logger the client + embedded workers log through.
	TemporalLogger(logger *slog.Logger) tlog.Logger

	// PolicyDecisionPoint is the authorization PDP the security Utility is built
	// with (application policy — not model-derivable).
	PolicyDecisionPoint() security.PolicyDecisionPoint

	// TokenValidator is the access-token validator for the auth boundary; nil
	// selects the dev-principal / deny middleware path. IdP-specific.
	TokenValidator(ctx context.Context, cfg *Config) (security.Validator, error)

	// DevConfig is the auth dev-mode config threaded into NewServer and the auth
	// middleware (the config_adapter seam).
	DevConfig(cfg *Config) web.DevConfig

	// WrapManagers optionally decorates the web-exposed managers (e.g. the
	// composition-root logging seam) before they are bound to the transports.
	// Return the argument unchanged for no wrapping.
	WrapManagers(managers WebManagers) WebManagers

	// ExtraMounts contributes composition-root-only routes (e.g. /api/userinfo,
	// /mcp) onto the root mux, behind the same auth boundary. The wrapped
	// managers are supplied for transports the generated server does not mount.
	ExtraMounts(root *http.ServeMux, cfg *Config, dev web.DevConfig, validator security.Validator, managers WebManagers)

	// ArtifactAccessGitHubCloudArgs supplies the artifactAccess GitHubCloud variant's constructor
	// arguments the deployment model cannot express (composition-root ports /
	// typed values). Read from cfg; the returned tuple is spread into the
	// generated variant constructor call.
	ArtifactAccessGitHubCloudArgs(cfg *Config) (string, string, string, string, string, int64)

	// ConstructionPipelineAccessGitHubActionsArgs supplies the constructionPipelineAccess GitHubActions variant's constructor
	// arguments the deployment model cannot express (composition-root ports /
	// typed values). Read from cfg; the returned tuple is spread into the
	// generated variant constructor call.
	ConstructionPipelineAccessGitHubActionsArgs(cfg *Config) (*github.AppClient, string, string, string, string, int64)

	// ProjectStateAccessGitHubArgs supplies the projectStateAccess GitHub variant's constructor
	// arguments the deployment model cannot express (composition-root ports /
	// typed values). Read from cfg; the returned tuple is spread into the
	// generated variant constructor call.
	ProjectStateAccessGitHubArgs(cfg *Config) (string, string, projectstate.ProjectCatalog, projectstate.CredentialMinter)

	// SourceControlAccessGitHubArgs supplies the sourceControlAccess GitHub variant's constructor
	// arguments the deployment model cannot express (composition-root ports /
	// typed values). Read from cfg; the returned tuple is spread into the
	// generated variant constructor call.
	SourceControlAccessGitHubArgs(cfg *Config) (*github.AppClient, string, string, bool)

	// FinalizeArtifactAccess is called immediately after artifactAccess's construction
	// (presence optional-dormant). Return v unchanged unless
	// composition policy needs to swap or wrap it (e.g. a construction
	// dry-run stub swap-in) — the identity implementation is always correct.
	FinalizeArtifactAccess(cfg *Config, v artifact.ArtifactAccess) artifact.ArtifactAccess

	// FinalizeConstructionPipelineAccess is called immediately after constructionPipelineAccess's construction
	// (presence optional-dormant). Return v unchanged unless
	// composition policy needs to swap or wrap it (e.g. a construction
	// dry-run stub swap-in) — the identity implementation is always correct.
	FinalizeConstructionPipelineAccess(cfg *Config, v constructionpipeline.ConstructionPipelineAccess) constructionpipeline.ConstructionPipelineAccess

	// FinalizeSourceControlAccess is called immediately after sourceControlAccess's construction
	// (presence optional-dormant). Return v unchanged unless
	// composition policy needs to swap or wrap it (e.g. a construction
	// dry-run stub swap-in) — the identity implementation is always correct.
	FinalizeSourceControlAccess(cfg *Config, v sourcecontrol.SourceControlAccess) sourcecontrol.SourceControlAccess

	// RegisterConstructionManagerWorker reports whether to register the ConstructionManager
	// Temporal Worker. The manager has ≥1 optional-dormant dependency, so its
	// Worker registration is composition-root policy (return true to always
	// register; gate on the dep presence / a dry-run stub otherwise).
	RegisterConstructionManagerWorker(cfg *Config) bool

	// RegisterOperationsManagerWorker reports whether to register the OperationsManager
	// Temporal Worker. The manager has ≥1 optional-dormant dependency, so its
	// Worker registration is composition-root policy (return true to always
	// register; gate on the dep presence / a dry-run stub otherwise).
	RegisterOperationsManagerWorker(cfg *Config) bool

	// RegisterProjectDesignManagerWorker reports whether to register the ProjectDesignManager
	// Temporal Worker. The manager has ≥1 optional-dormant dependency, so its
	// Worker registration is composition-root policy (return true to always
	// register; gate on the dep presence / a dry-run stub otherwise).
	RegisterProjectDesignManagerWorker(cfg *Config) bool

	// RegisterSystemDesignManagerWorker reports whether to register the SystemDesignManager
	// Temporal Worker. The manager has ≥1 optional-dormant dependency, so its
	// Worker registration is composition-root policy (return true to always
	// register; gate on the dep presence / a dry-run stub otherwise).
	RegisterSystemDesignManagerWorker(cfg *Config) bool

	// ConstructionManagerConstructionTransition supplies a composition-root value the deployment model
	// cannot express (a func-typed resolver, or a scalar/interface dep with no
	// setting/binding link). Return the zero value (nil for an interface) for a
	// dependency that stays unbuilt in the active profile.
	ConstructionManagerConstructionTransition() projectstate.ConstructionTransitionAccess

	// ConstructionManagerGitActivityStatus supplies a composition-root value the deployment model
	// cannot express (a func-typed resolver, or a scalar/interface dep with no
	// setting/binding link). Return the zero value (nil for an interface) for a
	// dependency that stays unbuilt in the active profile.
	ConstructionManagerGitActivityStatus() projectstate.GitActivityStatusAccess

	// ConstructionManagerEscalationWaitTimeout supplies a composition-root value the deployment model
	// cannot express (a func-typed resolver, or a scalar/interface dep with no
	// setting/binding link). Return the zero value (nil for an interface) for a
	// dependency that stays unbuilt in the active profile.
	ConstructionManagerEscalationWaitTimeout() time.Duration

	// ConstructionManagerInterventionMode supplies a composition-root value the deployment model
	// cannot express (a func-typed resolver, or a scalar/interface dep with no
	// setting/binding link). Return the zero value (nil for an interface) for a
	// dependency that stays unbuilt in the active profile.
	ConstructionManagerInterventionMode() string

	// ProjectDesignManagerRepo supplies a composition-root value the deployment model
	// cannot express (a func-typed resolver, or a scalar/interface dep with no
	// setting/binding link). Return the zero value (nil for an interface) for a
	// dependency that stays unbuilt in the active profile.
	ProjectDesignManagerRepo() func(projectID projectdesign.ProjectID) (sourcecontrol.RepoRef, bool)

	// SystemDesignManagerRepo supplies a composition-root value the deployment model
	// cannot express (a func-typed resolver, or a scalar/interface dep with no
	// setting/binding link). Return the zero value (nil for an interface) for a
	// dependency that stays unbuilt in the active profile.
	SystemDesignManagerRepo() func(projectID systemdesign.ProjectID) (sourcecontrol.RepoRef, bool)

	// SystemDesignManagerRepoBase supplies a composition-root value the deployment model
	// cannot express (a func-typed resolver, or a scalar/interface dep with no
	// setting/binding link). Return the zero value (nil for an interface) for a
	// dependency that stays unbuilt in the active profile.
	SystemDesignManagerRepoBase() string
}

// RunGenerated performs the container's boot walk: signal context → telemetry
// → Temporal client → Postgres pool → ResourceAccess bindings → Engines →
// Managers + Workers → HTTP server, with graceful shutdown. All policy is
// delegated to hooks; everything else is derived from the model.
func RunGenerated(cfg *Config, hooks Hooks, logger *slog.Logger) error {
	// Root context cancelled on the first SIGINT/SIGTERM.
	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	// Active deployment profile — the binding variant switches key off this.
	profile := hooks.ResolveProfile(cfg)

	// Telemetry — the OTLP satellite builds the Provider; the utilities facade
	// installs it as the OTel globals + a W3C propagator and bridges slog. MUST
	// precede the Temporal dial + the HTTP wrap so both pick up the globals.
	telemetryProvider, err := otelinfra.NewProvider(ctx, otelinfra.Options{ServiceName: serviceName})
	if err != nil {
		return err
	}
	shutdownTelemetry := telemetry.Install(telemetryProvider, telemetry.Options{ServiceName: serviceName, Logger: logger})
	defer func() {
		shutdownCtx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()
		if err := shutdownTelemetry(shutdownCtx); err != nil {
			logger.Error("telemetry shutdown failed", "err", err)
		}
	}()

	// Temporal control-plane client — the Managers own it; the embedded Workers
	// poll their task queues. Principal propagator + OTel tracing interceptor +
	// metrics handler bind the control plane to the installed globals.
	tracingInterceptor, err := temporalotel.NewTracingInterceptor(temporalotel.TracerOptions{})
	if err != nil {
		return err
	}
	tc, err := client.DialContext(ctx, client.Options{
		HostPort:           cfg.TemporalHostport,
		Namespace:          cfg.TemporalNamespace,
		Logger:             hooks.TemporalLogger(logger),
		ContextPropagators: []workflow.ContextPropagator{temporalprop.NewPrincipalPropagator()},
		Interceptors:       []interceptor.ClientInterceptor{tracingInterceptor},
		MetricsHandler:     temporalotel.NewMetricsHandler(temporalotel.MetricsHandlerOptions{}),
	})
	if err != nil {
		return err
	}
	defer tc.Close()
	logger.Info("temporal client dialed", "hostPort", cfg.TemporalHostport, "namespace", cfg.TemporalNamespace)

	// Postgres pool — the shared satellite the postgres-backed RAs are built on.
	pool, err := postgresinfra.NewPool(ctx, cfg.PostgresURL)
	if err != nil {
		return err
	}
	defer pool.Close()

	// ResourceAccess — one binding per component, variant-selected by profile.
	var artifactAccess artifact.ArtifactAccess
	switch profile {
	case "cloud":
		v, err := artifact.NewGitHubCloudArtifactAccess(hooks.ArtifactAccessGitHubCloudArgs(cfg))
		if err != nil {
			return err
		}
		artifactAccess = v
		logger.Info("artifactAccess (GitHubCloud) ready")
	case "local":
		artifactAccess = artifact.NewGitLocalArtifactAccess(cfg.ArtifactRepoURL)
		logger.Info("artifactAccess (GitLocal) ready")
	}
	artifactAccess = hooks.FinalizeArtifactAccess(cfg, artifactAccess)
	billingStateAccess := billingstate.NewBillingStateAccess()
	logger.Info("billingStateAccess (stub) ready")
	var constructionPipelineAccess constructionpipeline.ConstructionPipelineAccess
	switch profile {
	case "cloud":
		v, err := constructionpipeline.NewGitHubActionsConstructionPipelineAccess(hooks.ConstructionPipelineAccessGitHubActionsArgs(cfg))
		if err != nil {
			return err
		}
		constructionPipelineAccess = v
		logger.Info("constructionPipelineAccess (GitHubActions) ready")
	}
	constructionPipelineAccess = hooks.FinalizeConstructionPipelineAccess(cfg, constructionPipelineAccess)
	merchantGatewayAccess := merchantgateway.NewMerchantGatewayAccess()
	logger.Info("merchantGatewayAccess (stub) ready")
	var operatedRuntimeAccess operatedruntime.OperatedRuntimeAccess
	switch profile {
	case "cloud":
		operatedRuntimeAccess = operatedruntime.NewRealOperatedRuntimeAccess()
		logger.Info("operatedRuntimeAccess (Real) ready")
	case "local":
		operatedRuntimeAccess = operatedruntime.NewLocalOperatedRuntimeAccess()
		logger.Info("operatedRuntimeAccess (Local) ready")
	default:
		return errors.New("operatedRuntimeAccess: no ResourceAccess variant for the active profile")
	}
	var operatedSystemStateAccess operatedsystemstate.OperatedSystemStateAccess
	switch profile {
	case "cloud":
		v, err := operatedsystemstate.NewPostgresOperatedSystemStateAccess(ctx, pool)
		if err != nil {
			return err
		}
		operatedSystemStateAccess = v
		logger.Info("operatedSystemStateAccess (Postgres) ready")
	case "local":
		v, err := operatedsystemstate.NewPostgresOperatedSystemStateAccess(ctx, pool)
		if err != nil {
			return err
		}
		operatedSystemStateAccess = v
		logger.Info("operatedSystemStateAccess (Postgres) ready")
	default:
		return errors.New("operatedSystemStateAccess: no ResourceAccess variant for the active profile")
	}
	var projectStateAccess projectstate.ProjectStateAccess
	switch profile {
	case "cloud":
		v, err := projectstate.NewGitHubProjectStateAccess(hooks.ProjectStateAccessGitHubArgs(cfg))
		if err != nil {
			return err
		}
		projectStateAccess = v
		logger.Info("projectStateAccess (GitHub) ready")
	case "local":
		projectStateAccess = projectstate.NewGitLocalProjectStateAccess(cfg.ProjectStateGitRepoURL)
		logger.Info("projectStateAccess (GitLocal) ready")
	default:
		return errors.New("projectStateAccess: no ResourceAccess variant for the active profile")
	}
	var sourceControlAccess sourcecontrol.SourceControlAccess
	switch profile {
	case "cloud":
		v, err := sourcecontrol.NewGitHubSourceControlAccess(hooks.SourceControlAccessGitHubArgs(cfg))
		if err != nil {
			return err
		}
		sourceControlAccess = v
		logger.Info("sourceControlAccess (GitHub) ready")
	}
	sourceControlAccess = hooks.FinalizeSourceControlAccess(cfg, sourceControlAccess)
	var usageAccess usage.UsageAccess
	switch profile {
	case "cloud":
		v, err := usage.NewPostgresUsageAccess(ctx, pool)
		if err != nil {
			return err
		}
		usageAccess = v
		logger.Info("usageAccess (Postgres) ready")
	case "local":
		v, err := usage.NewPostgresUsageAccess(ctx, pool)
		if err != nil {
			return err
		}
		usageAccess = v
		logger.Info("usageAccess (Postgres) ready")
	default:
		return errors.New("usageAccess: no ResourceAccess variant for the active profile")
	}

	// Engines — pure, deterministic, dependency-free.
	autoscalerEngine := autoscaler.NewAutoscalerEngine()
	billingEngine := enginebilling.NewBillingEngine()
	estimationEngine := estimation.NewEstimationEngine()
	handOffEngine := handoff.NewHandOffEngine()
	interventionEngine := intervention.NewInterventionEngine()
	operationEstimationEngine := operationestimation.NewOperationEstimationEngine()
	reviewEngine := review.NewReviewEngine()

	// Managers — generated DI constructors + one embedded Worker each.
	billingManager := managerbilling.NewBillingManager(tc, billingStateAccess, usageAccess, merchantGatewayAccess, nil, billingEngine, interventionEngine)
	wBillingManager := worker.New(tc, managerbilling.TaskQueue, worker.Options{})
	managerbilling.RegisterManagerWorker(wBillingManager, billingManager)
	if err := wBillingManager.Start(); err != nil {
		return err
	}
	defer wBillingManager.Stop()
	logger.Info("embedded temporal worker started", "taskQueue", managerbilling.TaskQueue)
	constructionManager := construction.NewConstructionManager(tc, projectStateAccess, artifactAccess, handOffEngine, interventionEngine, reviewEngine, constructionPipelineAccess, sourceControlAccess, hooks.ConstructionManagerConstructionTransition(), hooks.ConstructionManagerGitActivityStatus(), hooks.ConstructionManagerEscalationWaitTimeout(), hooks.ConstructionManagerInterventionMode())
	if hooks.RegisterConstructionManagerWorker(cfg) {
		wConstructionManager := worker.New(tc, construction.TaskQueue, worker.Options{})
		construction.RegisterManagerWorker(wConstructionManager, constructionManager)
		if err := wConstructionManager.Start(); err != nil {
			return err
		}
		defer wConstructionManager.Stop()
		logger.Info("embedded temporal worker started", "taskQueue", construction.TaskQueue)
	} else {
		logger.Warn("constructionManager Worker NOT registered — optional-dormant dependencies absent (RegisterConstructionManagerWorker gate returned false)")
	}
	operationsManager := operations.NewOperationsManager(tc, operatedSystemStateAccess, operatedRuntimeAccess, usageAccess, artifactAccess, nil, interventionEngine, autoscalerEngine, operationEstimationEngine)
	if hooks.RegisterOperationsManagerWorker(cfg) {
		wOperationsManager := worker.New(tc, operations.TaskQueue, worker.Options{})
		operations.RegisterManagerWorker(wOperationsManager, operationsManager)
		if err := wOperationsManager.Start(); err != nil {
			return err
		}
		defer wOperationsManager.Stop()
		logger.Info("embedded temporal worker started", "taskQueue", operations.TaskQueue)
	} else {
		logger.Warn("operationsManager Worker NOT registered — optional-dormant dependencies absent (RegisterOperationsManagerWorker gate returned false)")
	}
	projectDesignManager := projectdesign.NewProjectDesignManager(tc, projectStateAccess, constructionPipelineAccess, sourceControlAccess, estimationEngine, operationEstimationEngine, billingEngine, hooks.ProjectDesignManagerRepo())
	if hooks.RegisterProjectDesignManagerWorker(cfg) {
		wProjectDesignManager := worker.New(tc, projectdesign.TaskQueue, worker.Options{})
		projectdesign.RegisterManagerWorker(wProjectDesignManager, projectDesignManager)
		if err := wProjectDesignManager.Start(); err != nil {
			return err
		}
		defer wProjectDesignManager.Stop()
		logger.Info("embedded temporal worker started", "taskQueue", projectdesign.TaskQueue)
	} else {
		logger.Warn("projectDesignManager Worker NOT registered — optional-dormant dependencies absent (RegisterProjectDesignManagerWorker gate returned false)")
	}
	systemDesignManager := systemdesign.NewSystemDesignManager(tc, projectStateAccess, constructionPipelineAccess, sourceControlAccess, hooks.SystemDesignManagerRepo(), estimationEngine, hooks.SystemDesignManagerRepoBase())
	if hooks.RegisterSystemDesignManagerWorker(cfg) {
		wSystemDesignManager := worker.New(tc, systemdesign.TaskQueue, worker.Options{})
		systemdesign.RegisterManagerWorker(wSystemDesignManager, systemDesignManager)
		if err := wSystemDesignManager.Start(); err != nil {
			return err
		}
		defer wSystemDesignManager.Stop()
		logger.Info("embedded temporal worker started", "taskQueue", systemdesign.TaskQueue)
	} else {
		logger.Warn("systemDesignManager Worker NOT registered — optional-dormant dependencies absent (RegisterSystemDesignManagerWorker gate returned false)")
	}

	// Security Utility + auth boundary.
	sec := security.New(security.WithPolicyDecisionPoint(hooks.PolicyDecisionPoint()))
	validator, err := hooks.TokenValidator(ctx, cfg)
	if err != nil {
		return err
	}
	dev := hooks.DevConfig(cfg)

	webManagers := WebManagers{
		ConstructionManager:  constructionManager,
		OperationsManager:    operationsManager,
		ProjectDesignManager: projectDesignManager,
		SystemDesignManager:  systemDesignManager,
	}
	webManagers = hooks.WrapManagers(webManagers)

	genServer := web.NewServer(dev, validator,
		&constructionweb.Handler{Manager: webManagers.ConstructionManager, Security: sec},
		&operationsweb.Handler{Manager: webManagers.OperationsManager, Security: sec},
		&projectdesignweb.Handler{Manager: webManagers.ProjectDesignManager, Security: sec},
		&systemdesignweb.Handler{Manager: webManagers.SystemDesignManager, Security: sec},
	)
	root := http.NewServeMux()
	root.Handle("/", genServer)
	hooks.ExtraMounts(root, cfg, dev, validator, webManagers)
	handler := otelhttp.NewHandler(root, serviceName)
	srv := &http.Server{
		Addr:              cfg.ListenAddr,
		Handler:           handler,
		ReadHeaderTimeout: 10 * time.Second,
	}

	serverErr := make(chan error, 1)
	go func() {
		logger.Info("http server listening", "addr", cfg.ListenAddr)
		if err := srv.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			serverErr <- err
		}
	}()

	select {
	case <-ctx.Done():
		logger.Info("shutdown signal received; draining")
	case err := <-serverErr:
		return err
	}

	shutdownCtx, cancel := context.WithTimeout(context.Background(), cfg.ShutdownTimeout)
	defer cancel()
	if err := srv.Shutdown(shutdownCtx); err != nil {
		logger.Error("http graceful shutdown failed", "err", err)
		return err
	}
	logger.Info("http server stopped cleanly")
	return nil
}
