// Code generated by cmd/modelgen from the service-contract interface; DO NOT EDIT.
// Edit project.json's `interface` and re-run `make gen-fakes` instead.

package operationestimationfake

import (
	fweng "github.com/mixofreality-studio/archistrator-platform/framework-go/engine"
	"github.com/mixofreality-studio/archistrator/server/internal/engine/operationestimation"
)

// FakeOperationEstimationEngine is a generated test double for operationestimation.OperationEstimationEngine: set the Fn field(s)
// a test needs; calling a method whose Fn is unset panics.
type FakeOperationEstimationEngine struct {
	EstimateForOptionFn     func(rc fweng.Context, option operationestimation.ProjectOption, declaredUsage operationestimation.UsageAssumption, infrastructureKind operationestimation.InfrastructureKind) (operationestimation.OperationForecast, error)
	ProjectForOperatedAppFn func(rc fweng.Context, observedUsage operationestimation.ObservedUsage, infrastructureKind operationestimation.InfrastructureKind, scaleWhatIfPoints []operationestimation.ScalePoint) (operationestimation.CostProjection, error)
}

func (f *FakeOperationEstimationEngine) EstimateForOption(rc fweng.Context, option operationestimation.ProjectOption, declaredUsage operationestimation.UsageAssumption, infrastructureKind operationestimation.InfrastructureKind) (operationestimation.OperationForecast, error) {
	if f.EstimateForOptionFn == nil {
		panic("FakeOperationEstimationEngine.EstimateForOptionFn not set")
	}
	return f.EstimateForOptionFn(rc, option, declaredUsage, infrastructureKind)
}

func (f *FakeOperationEstimationEngine) ProjectForOperatedApp(rc fweng.Context, observedUsage operationestimation.ObservedUsage, infrastructureKind operationestimation.InfrastructureKind, scaleWhatIfPoints []operationestimation.ScalePoint) (operationestimation.CostProjection, error) {
	if f.ProjectForOperatedAppFn == nil {
		panic("FakeOperationEstimationEngine.ProjectForOperatedAppFn not set")
	}
	return f.ProjectForOperatedAppFn(rc, observedUsage, infrastructureKind, scaleWhatIfPoints)
}

var _ operationestimation.OperationEstimationEngine = (*FakeOperationEstimationEngine)(nil)
